"use client";

import { useRouter } from "next/navigation";
import { useEffect, useState, useTransition } from "react";
import { saveLockgmProfileAction } from "./actions";
import type { LockgmProfile } from "@/lib/lockgm/identity";

type AttributionFields = {
  source: string;
  referralCode: string;
  campaign: string;
};

const FIELD_CLASS =
  "mt-2 w-full rounded-md border border-[color:var(--lg-line)] bg-[color:var(--lg-bg)] px-3 py-3 text-base text-[color:var(--lg-text)] outline-none focus:border-[color:var(--lg-accent)]";

export function LockgmProfileForm({
  profile,
  email,
  emailVerified,
  initialAttribution,
}: {
  profile: LockgmProfile;
  email: string;
  emailVerified: boolean;
  initialAttribution: AttributionFields;
}) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [displayName, setDisplayName] = useState(profile.displayName);
  const [legalName, setLegalName] = useState(profile.legalName);
  const [attribution, setAttribution] =
    useState<AttributionFields>(initialAttribution);
  const [consented, setConsented] = useState(
    Boolean(profile.attributionConsentAt),
  );
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let timeout: number | undefined;
    try {
      const raw = window.localStorage.getItem("lockgm_attribution_v1");
      if (!raw) return;
      const stored = JSON.parse(raw) as Partial<AttributionFields>;
      timeout = window.setTimeout(() => {
        setAttribution((current) => ({
          source: current.source || String(stored.source ?? ""),
          referralCode:
            current.referralCode || String(stored.referralCode ?? ""),
          campaign: current.campaign || String(stored.campaign ?? ""),
        }));
      }, 0);
    } catch {
      // Browser storage is an optional convenience, not part of identity.
    }
    return () => {
      if (timeout) window.clearTimeout(timeout);
    };
  }, []);

  function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const formData = new FormData(event.currentTarget);
    setMessage(null);
    setError(null);

    startTransition(async () => {
      const result = await saveLockgmProfileAction(formData);
      if (!result.ok) {
        setError(result.error);
        return;
      }
      setMessage("Profile saved. Your GM ID will stay the same.");
      router.refresh();
    });
  }

  return (
    <form onSubmit={submit} className="space-y-8">
      <section className="border border-[color:var(--lg-line)] bg-[color:var(--lg-panel)] p-5 sm:p-6">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <p className="lockgm-display text-sm font-bold tracking-[0.16em] text-[color:var(--lg-accent)]">
              PUBLIC RÉSUMÉ IDENTITY
            </p>
            <h2 className="mt-2 lockgm-display text-2xl font-bold">
              The name other GMs will see
            </h2>
          </div>
          <div className="border border-[color:var(--lg-accent)]/40 px-3 py-2 text-right">
            <p className="text-[10px] font-bold tracking-[0.16em] text-[color:var(--lg-mute)] uppercase">
              Stable GM ID
            </p>
            <p className="mt-1 lockgm-display text-xl font-bold text-[color:var(--lg-accent)]">
              {profile.gmId}
            </p>
          </div>
        </div>
        <p className="mt-4 max-w-2xl text-sm leading-relaxed text-[color:var(--lg-mute)]">
          Use a name you are comfortable attaching to future reports, draft
          calls, and achievements. Your GM ID is generated by LockedGM and is
          not a government identifier.
        </p>
        <label className="mt-6 block text-sm font-semibold" htmlFor="displayName">
          Public display name
          <input
            id="displayName"
            name="displayName"
            value={displayName}
            onChange={(event) => setDisplayName(event.target.value)}
            maxLength={80}
            required
            className={FIELD_CLASS}
            placeholder="Taylor Morgan"
          />
        </label>
      </section>

      <section className="border border-[color:var(--lg-line)] p-5 sm:p-6">
        <p className="lockgm-display text-sm font-bold tracking-[0.16em] text-[color:var(--lg-accent)]">
          ACCOUNT CHECK
        </p>
        <h2 className="mt-2 lockgm-display text-2xl font-bold">
          Verified account identity
        </h2>
        <p className="mt-3 text-sm leading-relaxed text-[color:var(--lg-mute)]">
          The signed-in email is used to keep your account attributable. A
          verified email/account identity is what lets future draft records
          and achievements be credited to this stable GM ID.
        </p>
        <div className="mt-5 flex flex-wrap items-center gap-3 text-sm">
          <span className="font-semibold">{email}</span>
          {emailVerified ? (
            <span className="rounded-full bg-[color:var(--lg-accent)]/15 px-2.5 py-1 text-xs font-bold text-[color:var(--lg-accent)]">
              Verified account
            </span>
          ) : (
            <span className="rounded-full border border-[color:var(--lg-line)] px-2.5 py-1 text-xs font-bold text-[color:var(--lg-mute)]">
              Email not verified in LockedGM
            </span>
          )}
        </div>
        <p className="mt-3 text-xs text-[color:var(--lg-mute)]">
          Password signup is available today. Google sign-in can provide a
          verified email when enabled; no government ID is collected.
        </p>
      </section>

      <section className="border border-[color:var(--lg-line)] p-5 sm:p-6">
        <p className="lockgm-display text-sm font-bold tracking-[0.16em] text-[color:var(--lg-accent)]">
          PRIVATE ACCOUNT DETAILS
        </p>
        <h2 className="mt-2 lockgm-display text-2xl font-bold">
          Optional legal name
        </h2>
        <p className="mt-3 max-w-2xl text-sm leading-relaxed text-[color:var(--lg-mute)]">
          This stays private to your account and authenticated LockedGM admins.
          It is not shown on public résumés. Do not enter a government ID
          number, Social Security number, date of birth, passport, or identity
          document here.
        </p>
        <label className="mt-6 block text-sm font-semibold" htmlFor="legalName">
          Legal name (optional, private)
          <input
            id="legalName"
            name="legalName"
            value={legalName}
            onChange={(event) => setLegalName(event.target.value)}
            maxLength={160}
            className={FIELD_CLASS}
            placeholder="Only if you want to keep this on your account"
          />
        </label>
      </section>

      <section className="border border-[color:var(--lg-line)] bg-[color:var(--lg-panel)] p-5 sm:p-6">
        <p className="lockgm-display text-sm font-bold tracking-[0.16em] text-[color:var(--lg-accent)]">
          SOURCE & REFERRAL
        </p>
        <h2 className="mt-2 lockgm-display text-2xl font-bold">
          How did you find LockedGM?
        </h2>
        <p className="mt-3 max-w-2xl text-sm leading-relaxed text-[color:var(--lg-mute)]">
          These fields can be prefilled from campaign links or this browser.
          LockedGM saves them to your account only when you give the consent
          below. Attribution is used for product and referral reporting and is
          not part of your public profile.
        </p>
        <div className="mt-6 grid gap-4 sm:grid-cols-3">
          <label className="text-sm font-semibold" htmlFor="attributionSource">
            Source
            <input
              id="attributionSource"
              name="attributionSource"
              value={attribution.source}
              onChange={(event) =>
                setAttribution((current) => ({
                  ...current,
                  source: event.target.value,
                }))
              }
              maxLength={120}
              className={FIELD_CLASS}
              placeholder="newsletter"
            />
          </label>
          <label className="text-sm font-semibold" htmlFor="campaign">
            Campaign
            <input
              id="campaign"
              name="campaign"
              value={attribution.campaign}
              onChange={(event) =>
                setAttribution((current) => ({
                  ...current,
                  campaign: event.target.value,
                }))
              }
              maxLength={120}
              className={FIELD_CLASS}
              placeholder="fall-draft"
            />
          </label>
          <label className="text-sm font-semibold" htmlFor="referralCode">
            Referral code
            <input
              id="referralCode"
              name="referralCode"
              value={attribution.referralCode}
              onChange={(event) =>
                setAttribution((current) => ({
                  ...current,
                  referralCode: event.target.value,
                }))
              }
              maxLength={120}
              className={FIELD_CLASS}
              placeholder="GMFRIEND"
            />
          </label>
        </div>
        <label className="mt-6 flex items-start gap-3 text-sm leading-relaxed">
          <input
            type="checkbox"
            name="attributionConsent"
            checked={consented}
            onChange={(event) => setConsented(event.target.checked)}
            className="mt-1 size-4 accent-[color:var(--lg-accent)]"
          />
          <span>
            I agree that LockedGM may save this source, campaign, and referral
            attribution to my account. I can remove it by unchecking this box.
          </span>
        </label>
      </section>

      <div className="flex flex-wrap items-center gap-4">
        <button
          type="submit"
          disabled={pending}
          className="inline-flex h-12 items-center rounded-md bg-[color:var(--lg-accent)] px-6 text-sm font-bold text-[color:var(--lg-bg)] disabled:opacity-50"
        >
          {pending ? "Saving profile…" : "Save LockedGM profile"}
        </button>
        {message ? (
          <p className="text-sm font-semibold text-[color:var(--lg-accent)]" role="status">
            {message}
          </p>
        ) : null}
        {error ? (
          <p className="text-sm font-semibold text-[color:var(--lg-warn)]" role="alert">
            {error}
          </p>
        ) : null}
      </div>
    </form>
  );
}
