import type { LoosePlayer, LooseTeam } from "../roster-build";
import { bat, pit } from "./pack-helpers";

const players: LoosePlayer[] = [
  {
    id: "cal82-carew",
    name: "Rod Carew",
    bats: "L",
    throws: "R",
    positions: ["1B"],
    batter: bat(18, 8, 14, 12, 13, 11, 2, -1),
  },
  {
    id: "cal82-jackson",
    name: "Reggie Jackson",
    bats: "L",
    throws: "L",
    positions: ["RF", "DH"],
    batter: bat(13, 17, 13, 9, 10, 12, 2, -1),
  },
  {
    id: "cal82-decinces",
    name: "Doug DeCinces",
    bats: "R",
    throws: "R",
    positions: ["3B"],
    batter: bat(14, 15, 12, 9, 14, 13, 0, 1),
  },
  {
    id: "cal82-downing",
    name: "Brian Downing",
    bats: "R",
    throws: "R",
    positions: ["LF"],
    batter: bat(14, 13, 14, 8, 12, 11, 0, 0),
  },
  {
    id: "cal82-grich",
    name: "Bobby Grich",
    bats: "R",
    throws: "R",
    positions: ["2B"],
    batter: bat(13, 13, 13, 10, 16, 14, 0, 1),
  },
  {
    id: "cal82-baylor",
    name: "Don Baylor",
    bats: "R",
    throws: "R",
    positions: ["DH", "LF"],
    batter: bat(13, 15, 12, 9, 9, 10, 0, 1),
  },
  {
    id: "cal82-lynn",
    name: "Fred Lynn",
    bats: "L",
    throws: "L",
    positions: ["CF"],
    batter: bat(14, 14, 13, 11, 14, 14, 2, -1),
  },
  {
    id: "cal82-boone",
    name: "Bob Boone",
    bats: "R",
    throws: "R",
    positions: ["C"],
    batter: bat(12, 8, 11, 5, 15, 14, 0, 0),
  },
  {
    id: "cal82-foli",
    name: "Tim Foli",
    bats: "R",
    throws: "R",
    positions: ["SS"],
    batter: bat(12, 6, 9, 10, 15, 14, 0, 0),
  },
  {
    id: "cal82-beniquez",
    name: "Juan Beníquez",
    bats: "R",
    throws: "R",
    positions: ["CF", "LF", "RF"],
    batter: bat(13, 10, 10, 12, 12, 12, 0, 0),
  },
  {
    id: "cal82-forsch",
    name: "Ken Forsch",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(14, 15, 13, 16, 0, 0), role: "SP" },
  },
  {
    id: "cal82-john",
    name: "Tommy John",
    bats: "R",
    throws: "L",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(13, 16, 15, 16, 1, 0), role: "SP" },
  },
  {
    id: "cal82-kison",
    name: "Bruce Kison",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(14, 12, 12, 15, 0, 1), role: "SP" },
  },
  {
    id: "cal82-witt",
    name: "Mike Witt",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(15, 12, 11, 15, 0, 0), role: "SP" },
  },
  {
    id: "cal82-sanchez",
    name: "Luis Sánchez",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(15, 13, 11, 9, 0, 1), role: "RP" },
  },
  {
    id: "cal82-hassler",
    name: "Andy Hassler",
    bats: "L",
    throws: "L",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(12, 12, 13, 8, 1, 0), role: "RP" },
  },
  {
    id: "cal82-goltz",
    name: "Dave Goltz",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(12, 12, 12, 10, 0, 0), role: "RP" },
  },
];

/** 1982 California Angels — AL West champs (public roster grounding; LockedGM grades). */
export const ANGELS_1982_LOOSE: LooseTeam = {
  id: "angels-1982",
  year: 1982,
  city: "California",
  nickname: "Angels",
  abbrev: "CAL '82",
  blurb:
    "Carew, Jackson, DeCinces, Grich — LockedGM pack for the 1982 AL West champions.",
  salaryCap: 92,
  lineup: [
    "cal82-downing",
    "cal82-carew",
    "cal82-lynn",
    "cal82-jackson",
    "cal82-baylor",
    "cal82-decinces",
    "cal82-grich",
    "cal82-boone",
    "cal82-foli",
  ],
  defense: {
    C: "cal82-boone",
    "1B": "cal82-carew",
    "2B": "cal82-grich",
    "3B": "cal82-decinces",
    SS: "cal82-foli",
    LF: "cal82-downing",
    CF: "cal82-lynn",
    RF: "cal82-jackson",
  },
  rotation: ["cal82-forsch", "cal82-john", "cal82-kison", "cal82-witt"],
  bullpen: ["cal82-sanchez", "cal82-hassler", "cal82-goltz"],
  players,
};
