import type { LoosePlayer, LooseTeam } from "../roster-build";
import { bat, pit } from "./pack-helpers";

const players: LoosePlayer[] = [
  {
    id: "tor85-bell",
    name: "George Bell",
    bats: "R",
    throws: "R",
    positions: ["LF", "DH"],
    batter: bat(15, 16, 11, 11, 11, 14, 0, 1),
  },
  {
    id: "tor85-barfield",
    name: "Jesse Barfield",
    bats: "R",
    throws: "R",
    positions: ["RF"],
    batter: bat(14, 16, 12, 10, 14, 18, 0, 1),
  },
  {
    id: "tor85-moseby",
    name: "Lloyd Moseby",
    bats: "L",
    throws: "R",
    positions: ["CF"],
    batter: bat(14, 13, 12, 15, 14, 14, 2, -1),
  },
  {
    id: "tor85-upshaw",
    name: "Willie Upshaw",
    bats: "L",
    throws: "L",
    positions: ["1B"],
    batter: bat(14, 13, 12, 9, 12, 11, 2, -1),
  },
  {
    id: "tor85-fernandez",
    name: "Tony Fernández",
    bats: "S",
    throws: "R",
    positions: ["SS"],
    batter: bat(15, 9, 11, 14, 16, 15, 0, 0),
  },
  {
    id: "tor85-garcia",
    name: "Dámaso García",
    bats: "R",
    throws: "R",
    positions: ["2B"],
    batter: bat(14, 8, 9, 14, 13, 12, 0, 0),
  },
  {
    id: "tor85-mulliniks",
    name: "Rance Mulliniks",
    bats: "L",
    throws: "R",
    positions: ["3B", "DH"],
    batter: bat(14, 11, 13, 8, 12, 12, 2, -1),
  },
  {
    id: "tor85-whitt",
    name: "Ernie Whitt",
    bats: "L",
    throws: "R",
    positions: ["C"],
    batter: bat(13, 12, 11, 6, 13, 13, 1, -1),
  },
  {
    id: "tor85-johnson",
    name: "Cliff Johnson",
    bats: "R",
    throws: "R",
    positions: ["DH", "1B"],
    batter: bat(13, 14, 12, 5, 8, 9, 0, 1),
  },
  {
    id: "tor85-iorg",
    name: "Garth Iorg",
    bats: "R",
    throws: "R",
    positions: ["3B", "2B"],
    batter: bat(12, 8, 9, 9, 12, 11, 0, 0),
  },
  {
    id: "tor85-stieb",
    name: "Dave Stieb",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(17, 14, 13, 17, 0, 1), role: "SP" },
  },
  {
    id: "tor85-key",
    name: "Jimmy Key",
    bats: "R",
    throws: "L",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(15, 16, 12, 16, 1, 0), role: "SP" },
  },
  {
    id: "tor85-alexander",
    name: "Doyle Alexander",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(14, 15, 11, 15, 0, 0), role: "SP" },
  },
  {
    id: "tor85-clancy",
    name: "Jim Clancy",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(13, 12, 12, 15, 0, 0), role: "SP" },
  },
  {
    id: "tor85-henke",
    name: "Tom Henke",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(17, 13, 10, 9, 0, 1), role: "RP" },
  },
  {
    id: "tor85-caudill",
    name: "Bill Caudill",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(13, 11, 11, 8, 0, 0), role: "RP" },
  },
  {
    id: "tor85-lavelle",
    name: "Gary Lavelle",
    bats: "S",
    throws: "L",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(12, 13, 12, 8, 1, 0), role: "RP" },
  },
];

/** 1985 Toronto Blue Jays — AL East champs (public roster grounding; LockGM grades). */
export const BLUE_JAYS_1985_LOOSE: LooseTeam = {
  id: "blue-jays-1985",
  year: 1985,
  city: "Toronto",
  nickname: "Blue Jays",
  abbrev: "TOR '85",
  blurb:
    "AL East champs with Bell, Barfield, Moseby, and Stieb — LockGM 1985 playoff experiment pack.",
  salaryCap: 92,
  lineup: [
    "tor85-garcia",
    "tor85-moseby",
    "tor85-upshaw",
    "tor85-bell",
    "tor85-barfield",
    "tor85-johnson",
    "tor85-mulliniks",
    "tor85-whitt",
    "tor85-fernandez",
  ],
  defense: {
    C: "tor85-whitt",
    "1B": "tor85-upshaw",
    "2B": "tor85-garcia",
    "3B": "tor85-mulliniks",
    SS: "tor85-fernandez",
    LF: "tor85-bell",
    CF: "tor85-moseby",
    RF: "tor85-barfield",
  },
  rotation: ["tor85-stieb", "tor85-key", "tor85-alexander", "tor85-clancy"],
  bullpen: ["tor85-henke", "tor85-caudill", "tor85-lavelle"],
  players,
};
