import type { LoosePlayer, LooseTeam } from "../roster-build";
import { bat, pit } from "./pack-helpers";

const players: LoosePlayer[] = [
  {
    id: "atl82-murphy",
    name: "Dale Murphy",
    bats: "R",
    throws: "R",
    positions: ["CF"],
    batter: bat(15, 17, 13, 13, 15, 15, 0, 1),
  },
  {
    id: "atl82-horner",
    name: "Bob Horner",
    bats: "R",
    throws: "R",
    positions: ["3B", "1B"],
    batter: bat(14, 17, 11, 7, 11, 12, 0, 1),
  },
  {
    id: "atl82-chambliss",
    name: "Chris Chambliss",
    bats: "L",
    throws: "R",
    positions: ["1B"],
    batter: bat(14, 12, 11, 7, 13, 11, 1, -1),
  },
  {
    id: "atl82-hubbard",
    name: "Glenn Hubbard",
    bats: "R",
    throws: "R",
    positions: ["2B"],
    batter: bat(13, 9, 12, 10, 15, 13, 0, 0),
  },
  {
    id: "atl82-ramirez",
    name: "Rafael Ramírez",
    bats: "R",
    throws: "R",
    positions: ["SS"],
    batter: bat(13, 9, 9, 12, 13, 14, 0, 0),
  },
  {
    id: "atl82-washington",
    name: "Claudell Washington",
    bats: "L",
    throws: "L",
    positions: ["RF", "LF"],
    batter: bat(14, 12, 10, 14, 12, 13, 2, -1),
  },
  {
    id: "atl82-butler",
    name: "Brett Butler",
    bats: "L",
    throws: "L",
    positions: ["LF", "CF"],
    batter: bat(14, 6, 13, 17, 13, 11, 2, -1),
  },
  {
    id: "atl82-benedict",
    name: "Bruce Benedict",
    bats: "R",
    throws: "R",
    positions: ["C"],
    batter: bat(12, 6, 11, 5, 14, 13, 0, 0),
  },
  {
    id: "atl82-whisenton",
    name: "Larry Whisenton",
    bats: "L",
    throws: "L",
    positions: ["LF", "RF"],
    batter: bat(12, 10, 11, 11, 11, 11, 1, -1),
  },
  {
    id: "atl82-royster",
    name: "Jerry Royster",
    bats: "R",
    throws: "R",
    positions: ["3B", "2B", "SS", "LF"],
    batter: bat(12, 8, 10, 13, 12, 12, 0, 0),
  },
  {
    id: "atl82-niekro",
    name: "Phil Niekro",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(6, 3, 5, 5, 8, 8),
    pitcher: { ...pit(15, 14, 12, 17, 0, 0), role: "SP" },
  },
  {
    id: "atl82-perez",
    name: "Pascual Pérez",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(14, 12, 11, 15, 0, 1), role: "SP" },
  },
  {
    id: "atl82-mahler",
    name: "Rick Mahler",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(13, 13, 13, 15, 0, 0), role: "SP" },
  },
  {
    id: "atl82-walk",
    name: "Bob Walk",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(13, 12, 12, 14, 0, 0), role: "SP" },
  },
  {
    id: "atl82-garber",
    name: "Gene Garber",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(14, 15, 13, 9, 0, 0), role: "RP" },
  },
  {
    id: "atl82-bedrosian",
    name: "Steve Bedrosian",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(15, 12, 11, 9, 0, 1), role: "RP" },
  },
  {
    id: "atl82-camp",
    name: "Rick Camp",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(12, 13, 12, 8, 0, 0), role: "RP" },
  },
];

/** 1982 Atlanta Braves — NL West champs (public roster grounding; LockedGM grades). */
export const BRAVES_1982_LOOSE: LooseTeam = {
  id: "braves-1982",
  year: 1982,
  city: "Atlanta",
  nickname: "Braves",
  abbrev: "ATL '82",
  blurb:
    "Murphy MVP season with Horner and knuckleball Niekro — LockedGM 1982 NLCS experiment pack.",
  salaryCap: 92,
  lineup: [
    "atl82-butler",
    "atl82-ramirez",
    "atl82-washington",
    "atl82-murphy",
    "atl82-horner",
    "atl82-chambliss",
    "atl82-hubbard",
    "atl82-benedict",
    "atl82-whisenton",
  ],
  defense: {
    C: "atl82-benedict",
    "1B": "atl82-chambliss",
    "2B": "atl82-hubbard",
    "3B": "atl82-horner",
    SS: "atl82-ramirez",
    LF: "atl82-butler",
    CF: "atl82-murphy",
    RF: "atl82-washington",
  },
  rotation: ["atl82-niekro", "atl82-perez", "atl82-mahler", "atl82-walk"],
  bullpen: ["atl82-garber", "atl82-bedrosian", "atl82-camp"],
  players,
};
