import type { LoosePlayer, LooseTeam } from "../roster-build";
import { bat, pit } from "./pack-helpers";

const players: LoosePlayer[] = [
  {
    id: "mil82-molitor",
    name: "Paul Molitor",
    bats: "R",
    throws: "R",
    positions: ["3B", "DH"],
    batter: bat(17, 12, 13, 16, 13, 13, 1, 0),
  },
  {
    id: "mil82-yount",
    name: "Robin Yount",
    bats: "R",
    throws: "R",
    positions: ["SS"],
    batter: bat(17, 14, 12, 14, 16, 15, 0, 1),
  },
  {
    id: "mil82-cooper",
    name: "Cecil Cooper",
    bats: "L",
    throws: "L",
    positions: ["1B"],
    batter: bat(16, 14, 11, 8, 12, 10, 2, -1),
  },
  {
    id: "mil82-simmons",
    name: "Ted Simmons",
    bats: "S",
    throws: "R",
    positions: ["C", "DH"],
    batter: bat(15, 13, 12, 6, 12, 14, 0, 0),
  },
  {
    id: "mil82-thomas",
    name: "Gorman Thomas",
    bats: "R",
    throws: "R",
    positions: ["CF", "DH"],
    batter: bat(12, 17, 12, 8, 10, 12, 0, 1),
  },
  {
    id: "mil82-oglivie",
    name: "Ben Oglivie",
    bats: "L",
    throws: "L",
    positions: ["LF"],
    batter: bat(14, 15, 11, 9, 11, 12, 2, -1),
  },
  {
    id: "mil82-moore",
    name: "Charlie Moore",
    bats: "R",
    throws: "R",
    positions: ["RF", "C"],
    batter: bat(13, 9, 10, 11, 12, 14, 0, 0),
  },
  {
    id: "mil82-gantner",
    name: "Jim Gantner",
    bats: "L",
    throws: "R",
    positions: ["2B"],
    batter: bat(13, 7, 10, 11, 14, 12, 1, -1),
  },
  {
    id: "mil82-money",
    name: "Don Money",
    bats: "R",
    throws: "R",
    positions: ["DH", "3B", "1B"],
    batter: bat(13, 12, 11, 7, 11, 11, 0, 0),
  },
  {
    id: "mil82-howell",
    name: "Roy Howell",
    bats: "L",
    throws: "R",
    positions: ["3B", "DH"],
    batter: bat(12, 11, 10, 8, 11, 11, 1, -1),
  },
  {
    id: "mil82-vuckovich",
    name: "Pete Vuckovich",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(16, 13, 13, 17, 0, 1), role: "SP" },
  },
  {
    id: "mil82-caldwell",
    name: "Mike Caldwell",
    bats: "R",
    throws: "L",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(14, 15, 14, 16, 1, 0), role: "SP" },
  },
  {
    id: "mil82-sutton",
    name: "Don Sutton",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(15, 16, 11, 16, 0, 0), role: "SP" },
  },
  {
    id: "mil82-haas",
    name: "Moose Haas",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(13, 13, 11, 15, 0, 0), role: "SP" },
  },
  {
    id: "mil82-fingers",
    name: "Rollie Fingers",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(16, 15, 11, 9, 0, 1), role: "RP" },
  },
  {
    id: "mil82-bernard",
    name: "Dwight Bernard",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(12, 13, 11, 8, 0, 0), role: "RP" },
  },
  {
    id: "mil82-ladd",
    name: "Pete Ladd",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(14, 12, 12, 8, 0, 0), role: "RP" },
  },
  {
    id: "mil82-mcclure",
    name: "Bob McClure",
    bats: "R",
    throws: "L",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(12, 12, 12, 12, 1, 0), role: "RP" },
  },
  {
    id: "mil82-slaton",
    name: "Jim Slaton",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(12, 13, 13, 14, 0, 0), role: "RP" },
  },
];

/** 1982 Milwaukee Brewers — AL East champs (public roster grounding; LockedGM grades). */
export const BREWERS_1982_LOOSE: LooseTeam = {
  id: "brewers-1982",
  year: 1982,
  city: "Milwaukee",
  nickname: "Brewers",
  abbrev: "MIL '82",
  blurb:
    "Harvey's Wallbangers: Yount, Molitor, Thomas, Vuckovich — LockedGM 1982 pack with a Kuenn fireman pen (Fingers, Bernard, Ladd, McClure, Slaton).",
  salaryCap: 92,
  lineup: [
    "mil82-molitor",
    "mil82-yount",
    "mil82-cooper",
    "mil82-simmons",
    "mil82-thomas",
    "mil82-oglivie",
    "mil82-moore",
    "mil82-gantner",
    "mil82-money",
  ],
  defense: {
    C: "mil82-simmons",
    "1B": "mil82-cooper",
    "2B": "mil82-gantner",
    "3B": "mil82-molitor",
    SS: "mil82-yount",
    LF: "mil82-oglivie",
    CF: "mil82-thomas",
    RF: "mil82-moore",
  },
  rotation: [
    "mil82-vuckovich",
    "mil82-caldwell",
    "mil82-sutton",
    "mil82-haas",
  ],
  bullpen: [
    "mil82-fingers",
    "mil82-bernard",
    "mil82-ladd",
    "mil82-mcclure",
    "mil82-slaton",
  ],
  players,
};
