import type { BatterRatings, PitcherRatings } from "../types";
import type { LoosePlayer, LooseTeam } from "../roster-build";

function bat(
  contact: number,
  power: number,
  eye: number,
  speed: number,
  defense: number,
  arm: number,
  platoonVsL = 0,
  platoonVsR = 0,
): BatterRatings {
  return { contact, power, eye, speed, defense, arm, platoonVsL, platoonVsR };
}

function pit(
  stuff: number,
  control: number,
  gb: number,
  stamina: number,
  platoonVsL = 0,
  platoonVsR = 0,
): PitcherRatings {
  return { stuff, control, gb, stamina, platoonVsL, platoonVsR };
}

const players: LoosePlayer[] = [
  {
    id: "mil85-molitor",
    name: "Paul Molitor",
    bats: "R",
    throws: "R",
    positions: ["3B", "DH"],
    batter: bat(17, 12, 13, 16, 12, 12, 1, 0),
  },
  {
    id: "mil85-yount",
    name: "Robin Yount",
    bats: "R",
    throws: "R",
    positions: ["CF", "SS"],
    batter: bat(16, 13, 12, 14, 15, 14, 0, 1),
  },
  {
    id: "mil85-cooper",
    name: "Cecil Cooper",
    bats: "L",
    throws: "L",
    positions: ["1B"],
    batter: bat(15, 14, 11, 8, 12, 10, 2, -1),
  },
  {
    id: "mil85-simmons",
    name: "Ted Simmons",
    bats: "S",
    throws: "R",
    positions: ["C", "DH"],
    batter: bat(14, 12, 12, 6, 11, 13, 0, 0),
  },
  {
    id: "mil85-oglivie",
    name: "Ben Oglivie",
    bats: "L",
    throws: "L",
    positions: ["LF"],
    batter: bat(13, 14, 11, 9, 11, 12, 2, -1),
  },
  {
    id: "mil85-brouhard",
    name: "Mark Brouhard",
    bats: "R",
    throws: "R",
    positions: ["RF", "LF"],
    batter: bat(12, 12, 9, 10, 10, 11, 0, 0),
  },
  {
    id: "mil85-gantner",
    name: "Jim Gantner",
    bats: "L",
    throws: "R",
    positions: ["2B"],
    batter: bat(13, 7, 10, 11, 14, 12, 1, -1),
  },
  {
    id: "mil85-riles",
    name: "Ernest Riles",
    bats: "L",
    throws: "R",
    positions: ["SS"],
    batter: bat(13, 9, 10, 12, 13, 13, 1, 0),
  },
  {
    id: "mil85-manning",
    name: "Rick Manning",
    bats: "L",
    throws: "R",
    positions: ["CF", "RF"],
    batter: bat(12, 8, 10, 13, 14, 12, 1, -1),
  },
  {
    id: "mil85-higuera",
    name: "Teddy Higuera",
    bats: "S",
    throws: "L",
    positions: ["P"],
    batter: bat(6, 3, 5, 6, 8, 8),
    pitcher: { ...pit(16, 14, 12, 17, 1, 0), role: "SP" },
  },
  {
    id: "mil85-haas",
    name: "Moose Haas",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(13, 13, 11, 15, 0, 0), role: "SP" },
  },
  {
    id: "mil85-darwin",
    name: "Danny Darwin",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(14, 12, 10, 14, 0, 1), role: "SP" },
  },
  {
    id: "mil85-cocanower",
    name: "Jaime Cocanower",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(11, 11, 12, 13, 0, 0), role: "SP" },
  },
  {
    id: "mil85-fingers",
    name: "Rollie Fingers",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(15, 14, 11, 9, 0, 1), role: "RP" },
  },
  {
    id: "mil85-searage",
    name: "Ray Searage",
    bats: "L",
    throws: "L",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(12, 12, 13, 8, 1, 0), role: "RP" },
  },
  {
    id: "mil85-gibson",
    name: "Bob Gibson",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(11, 11, 12, 8, 0, 0), role: "RP" },
  },
];

/** 1985 Milwaukee Brewers — abbreviated classic pack (public roster/history). */
export const BREWERS_1985_LOOSE: LooseTeam = {
  id: "brewers-1985",
  year: 1985,
  city: "Milwaukee",
  nickname: "Brewers",
  abbrev: "MIL '85",
  blurb:
    "County Stadium crew built around Yount and Molitor — LockGM classic experiment pack.",
  salaryCap: 92,
  lineup: [
    "mil85-molitor",
    "mil85-yount",
    "mil85-cooper",
    "mil85-simmons",
    "mil85-oglivie",
    "mil85-brouhard",
    "mil85-gantner",
    "mil85-riles",
    "mil85-manning",
  ],
  defense: {
    C: "mil85-simmons",
    "1B": "mil85-cooper",
    "2B": "mil85-gantner",
    "3B": "mil85-molitor",
    SS: "mil85-riles",
    LF: "mil85-oglivie",
    CF: "mil85-yount",
    RF: "mil85-brouhard",
  },
  rotation: ["mil85-higuera", "mil85-haas", "mil85-darwin", "mil85-cocanower"],
  bullpen: ["mil85-fingers", "mil85-searage", "mil85-gibson"],
  players,
};
