import type { LoosePlayer, LooseTeam } from "../roster-build";
import { bat, pit } from "./pack-helpers";

const players: LoosePlayer[] = [
  {
    id: "stl85-coleman",
    name: "Vince Coleman",
    bats: "S",
    throws: "R",
    positions: ["LF"],
    batter: bat(14, 7, 11, 20, 13, 12, 0, 0),
  },
  {
    id: "stl85-mcgee",
    name: "Willie McGee",
    bats: "S",
    throws: "R",
    positions: ["CF"],
    batter: bat(17, 12, 10, 16, 16, 14, 0, 0),
  },
  {
    id: "stl85-herr",
    name: "Tom Herr",
    bats: "S",
    throws: "R",
    positions: ["2B"],
    batter: bat(15, 10, 13, 12, 14, 13, 0, 0),
  },
  {
    id: "stl85-clark",
    name: "Jack Clark",
    bats: "R",
    throws: "R",
    positions: ["1B"],
    batter: bat(14, 17, 15, 7, 11, 12, 0, 1),
  },
  {
    id: "stl85-ozzie",
    name: "Ozzie Smith",
    bats: "S",
    throws: "R",
    positions: ["SS"],
    batter: bat(14, 8, 13, 15, 19, 16, 0, 0),
  },
  {
    id: "stl85-pendleton",
    name: "Terry Pendleton",
    bats: "S",
    throws: "R",
    positions: ["3B"],
    batter: bat(13, 9, 10, 12, 15, 14, 0, 0),
  },
  {
    id: "stl85-vanslyke",
    name: "Andy Van Slyke",
    bats: "L",
    throws: "R",
    positions: ["RF", "CF"],
    batter: bat(13, 13, 12, 14, 15, 15, 2, -1),
  },
  {
    id: "stl85-porter",
    name: "Darrell Porter",
    bats: "L",
    throws: "R",
    positions: ["C"],
    batter: bat(12, 11, 13, 5, 13, 13, 1, -1),
  },
  {
    id: "stl85-cedeno",
    name: "César Cedeño",
    bats: "R",
    throws: "R",
    positions: ["1B", "LF", "RF"],
    batter: bat(13, 11, 10, 13, 12, 13, 0, 0),
  },
  {
    id: "stl85-nieto",
    name: "Tom Nieto",
    bats: "R",
    throws: "R",
    positions: ["C"],
    batter: bat(11, 7, 9, 5, 12, 12, 0, 0),
  },
  {
    id: "stl85-tudor",
    name: "John Tudor",
    bats: "L",
    throws: "L",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(17, 17, 14, 17, 1, 0), role: "SP" },
  },
  {
    id: "stl85-andujar",
    name: "Joaquín Andújar",
    bats: "S",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(15, 12, 13, 16, 0, 0), role: "SP" },
  },
  {
    id: "stl85-cox",
    name: "Danny Cox",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(14, 13, 12, 15, 0, 0), role: "SP" },
  },
  {
    id: "stl85-forsch",
    name: "Bob Forsch",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(6, 4, 5, 5, 8, 8),
    pitcher: { ...pit(12, 13, 12, 14, 0, 0), role: "SP" },
  },
  {
    id: "stl85-worrell",
    name: "Todd Worrell",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(16, 13, 11, 9, 0, 1), role: "RP" },
  },
  {
    id: "stl85-dayley",
    name: "Ken Dayley",
    bats: "L",
    throws: "L",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(14, 12, 12, 8, 1, 0), role: "RP" },
  },
  {
    id: "stl85-lahti",
    name: "Jeff Lahti",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(13, 13, 13, 8, 0, 0), role: "RP" },
  },
];

/** 1985 St. Louis Cardinals — NL East champs (public roster grounding; LockedGM grades). */
export const CARDINALS_1985_LOOSE: LooseTeam = {
  id: "cardinals-1985",
  year: 1985,
  city: "St. Louis",
  nickname: "Cardinals",
  abbrev: "STL '85",
  blurb:
    "Whitey-ball speed: Coleman, McGee, Ozzie, Tudor — LockedGM 1985 NLCS/WS experiment pack.",
  salaryCap: 92,
  lineup: [
    "stl85-coleman",
    "stl85-mcgee",
    "stl85-herr",
    "stl85-clark",
    "stl85-pendleton",
    "stl85-vanslyke",
    "stl85-ozzie",
    "stl85-porter",
    "stl85-cedeno",
  ],
  defense: {
    C: "stl85-porter",
    "1B": "stl85-clark",
    "2B": "stl85-herr",
    "3B": "stl85-pendleton",
    SS: "stl85-ozzie",
    LF: "stl85-coleman",
    CF: "stl85-mcgee",
    RF: "stl85-vanslyke",
  },
  rotation: ["stl85-tudor", "stl85-andujar", "stl85-cox", "stl85-forsch"],
  bullpen: ["stl85-worrell", "stl85-dayley", "stl85-lahti"],
  players,
};
