import type { LoosePlayer, LooseTeam } from "../roster-build";
import { bat, pit } from "./pack-helpers";

const players: LoosePlayer[] = [
  {
    id: "stl82-lsmith",
    name: "Lonnie Smith",
    bats: "R",
    throws: "R",
    positions: ["LF"],
    batter: bat(15, 10, 12, 18, 12, 12, 0, 0),
  },
  {
    id: "stl82-herr",
    name: "Tom Herr",
    bats: "S",
    throws: "R",
    positions: ["2B"],
    batter: bat(14, 9, 12, 12, 14, 13, 0, 0),
  },
  {
    id: "stl82-hendrick",
    name: "George Hendrick",
    bats: "R",
    throws: "R",
    positions: ["RF", "1B"],
    batter: bat(15, 14, 11, 9, 12, 13, 0, 1),
  },
  {
    id: "stl82-mcgee",
    name: "Willie McGee",
    bats: "S",
    throws: "R",
    positions: ["CF"],
    batter: bat(15, 11, 10, 16, 15, 14, 0, 0),
  },
  {
    id: "stl82-porter",
    name: "Darrell Porter",
    bats: "L",
    throws: "R",
    positions: ["C"],
    batter: bat(13, 12, 14, 5, 13, 13, 1, -1),
  },
  {
    id: "stl82-oberkfell",
    name: "Ken Oberkfell",
    bats: "L",
    throws: "R",
    positions: ["3B", "2B"],
    batter: bat(14, 8, 12, 11, 13, 12, 1, -1),
  },
  {
    id: "stl82-ozzie",
    name: "Ozzie Smith",
    bats: "S",
    throws: "R",
    positions: ["SS"],
    batter: bat(13, 7, 12, 15, 19, 16, 0, 0),
  },
  {
    id: "stl82-tenace",
    name: "Gene Tenace",
    bats: "R",
    throws: "R",
    positions: ["1B", "C"],
    batter: bat(11, 13, 16, 5, 11, 12, 0, 1),
  },
  {
    id: "stl82-iorg",
    name: "Dane Iorg",
    bats: "L",
    throws: "R",
    positions: ["1B", "LF", "RF"],
    batter: bat(14, 10, 10, 8, 11, 11, 1, -1),
  },
  {
    id: "stl82-green",
    name: "David Green",
    bats: "R",
    throws: "R",
    positions: ["RF", "CF", "1B"],
    batter: bat(13, 11, 9, 14, 12, 13, 0, 0),
  },
  {
    id: "stl82-andujar",
    name: "Joaquín Andújar",
    bats: "S",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(16, 12, 13, 17, 0, 0), role: "SP" },
  },
  {
    id: "stl82-forsch",
    name: "Bob Forsch",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(6, 4, 5, 5, 8, 8),
    pitcher: { ...pit(13, 14, 12, 15, 0, 0), role: "SP" },
  },
  {
    id: "stl82-stuper",
    name: "John Stuper",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(13, 13, 12, 15, 0, 0), role: "SP" },
  },
  {
    id: "stl82-mura",
    name: "Steve Mura",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(12, 12, 11, 14, 0, 0), role: "SP" },
  },
  {
    id: "stl82-sutter",
    name: "Bruce Sutter",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(18, 14, 14, 9, 0, 1), role: "RP" },
  },
  {
    id: "stl82-kaat",
    name: "Jim Kaat",
    bats: "L",
    throws: "L",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(12, 14, 13, 8, 1, 0), role: "RP" },
  },
  {
    id: "stl82-littell",
    name: "Mark Littell",
    bats: "L",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(13, 12, 11, 8, 0, 0), role: "RP" },
  },
];

/** 1982 St. Louis Cardinals — NL East / WS champs (public roster grounding; LockedGM grades). */
export const CARDINALS_1982_LOOSE: LooseTeam = {
  id: "cardinals-1982",
  year: 1982,
  city: "St. Louis",
  nickname: "Cardinals",
  abbrev: "STL '82",
  blurb:
    "Whitey Herzog speed & Sutter: Lonnie, Ozzie, McGee, Andújar — LockedGM 1982 NLCS/WS pack.",
  salaryCap: 92,
  lineup: [
    "stl82-lsmith",
    "stl82-herr",
    "stl82-hendrick",
    "stl82-mcgee",
    "stl82-porter",
    "stl82-oberkfell",
    "stl82-tenace",
    "stl82-ozzie",
    "stl82-iorg",
  ],
  defense: {
    C: "stl82-porter",
    "1B": "stl82-tenace",
    "2B": "stl82-herr",
    "3B": "stl82-oberkfell",
    SS: "stl82-ozzie",
    LF: "stl82-lsmith",
    CF: "stl82-mcgee",
    RF: "stl82-hendrick",
  },
  rotation: ["stl82-andujar", "stl82-forsch", "stl82-stuper", "stl82-mura"],
  bullpen: ["stl82-sutter", "stl82-kaat", "stl82-littell"],
  players,
};
