import type { LoosePlayer, LooseTeam } from "../roster-build";
import { bat, pit } from "./pack-helpers";

const players: LoosePlayer[] = [
  {
    id: "lad85-sax",
    name: "Steve Sax",
    bats: "R",
    throws: "R",
    positions: ["2B"],
    batter: bat(15, 8, 11, 16, 12, 12, 0, 0),
  },
  {
    id: "lad85-guerrero",
    name: "Pedro Guerrero",
    bats: "R",
    throws: "R",
    positions: ["LF", "3B", "1B"],
    batter: bat(15, 16, 12, 11, 11, 12, 0, 1),
  },
  {
    id: "lad85-marshall",
    name: "Mike Marshall",
    bats: "R",
    throws: "R",
    positions: ["RF", "1B"],
    batter: bat(14, 15, 11, 9, 11, 13, 0, 1),
  },
  {
    id: "lad85-madlock",
    name: "Bill Madlock",
    bats: "R",
    throws: "R",
    positions: ["3B"],
    batter: bat(15, 11, 12, 9, 12, 12, 0, 0),
  },
  {
    id: "lad85-scioscia",
    name: "Mike Scioscia",
    bats: "L",
    throws: "R",
    positions: ["C"],
    batter: bat(13, 9, 12, 6, 15, 14, 1, -1),
  },
  {
    id: "lad85-duncan",
    name: "Mariano Duncan",
    bats: "R",
    throws: "R",
    positions: ["SS"],
    batter: bat(13, 9, 9, 15, 13, 13, 0, 0),
  },
  {
    id: "lad85-landreaux",
    name: "Ken Landreaux",
    bats: "L",
    throws: "R",
    positions: ["CF"],
    batter: bat(13, 10, 11, 13, 13, 13, 1, -1),
  },
  {
    id: "lad85-brock",
    name: "Greg Brock",
    bats: "L",
    throws: "R",
    positions: ["1B"],
    batter: bat(12, 13, 12, 7, 12, 11, 2, -1),
  },
  {
    id: "lad85-cabell",
    name: "Enos Cabell",
    bats: "R",
    throws: "R",
    positions: ["1B", "3B"],
    batter: bat(13, 9, 9, 11, 11, 11, 0, 0),
  },
  {
    id: "lad85-whitfield",
    name: "Terry Whitfield",
    bats: "L",
    throws: "R",
    positions: ["LF", "RF"],
    batter: bat(12, 10, 10, 10, 11, 12, 1, -1),
  },
  {
    id: "lad85-hershiser",
    name: "Orel Hershiser",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(6, 3, 5, 5, 8, 8),
    pitcher: { ...pit(17, 16, 14, 17, 0, 1), role: "SP" },
  },
  {
    id: "lad85-fernando",
    name: "Fernando Valenzuela",
    bats: "L",
    throws: "L",
    positions: ["P"],
    batter: bat(7, 5, 6, 5, 8, 8),
    pitcher: { ...pit(16, 14, 15, 18, 1, 0), role: "SP" },
  },
  {
    id: "lad85-welch",
    name: "Bob Welch",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(15, 13, 12, 16, 0, 0), role: "SP" },
  },
  {
    id: "lad85-reuss",
    name: "Jerry Reuss",
    bats: "L",
    throws: "L",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(13, 13, 13, 15, 1, 0), role: "SP" },
  },
  {
    id: "lad85-niedenfuer",
    name: "Tom Niedenfuer",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(15, 13, 11, 9, 0, 1), role: "RP" },
  },
  {
    id: "lad85-howell",
    name: "Ken Howell",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(14, 11, 10, 8, 0, 0), role: "RP" },
  },
  {
    id: "lad85-pena",
    name: "Alejandro Peña",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(13, 12, 11, 8, 0, 0), role: "RP" },
  },
];

/** 1985 Los Angeles Dodgers — NL West champs (public roster grounding; LockGM grades). */
export const DODGERS_1985_LOOSE: LooseTeam = {
  id: "dodgers-1985",
  year: 1985,
  city: "Los Angeles",
  nickname: "Dodgers",
  abbrev: "LAD '85",
  blurb:
    "Guerrero, Hershiser, Fernando — LockGM pack for the 1985 NL West champions.",
  salaryCap: 92,
  lineup: [
    "lad85-sax",
    "lad85-duncan",
    "lad85-guerrero",
    "lad85-marshall",
    "lad85-madlock",
    "lad85-landreaux",
    "lad85-brock",
    "lad85-scioscia",
    "lad85-cabell",
  ],
  defense: {
    C: "lad85-scioscia",
    "1B": "lad85-brock",
    "2B": "lad85-sax",
    "3B": "lad85-madlock",
    SS: "lad85-duncan",
    LF: "lad85-guerrero",
    CF: "lad85-landreaux",
    RF: "lad85-marshall",
  },
  rotation: [
    "lad85-hershiser",
    "lad85-fernando",
    "lad85-welch",
    "lad85-reuss",
  ],
  bullpen: ["lad85-niedenfuer", "lad85-howell", "lad85-pena"],
  players,
};
