/**
 * 2026 MLB Opening Day packs — public lineup/rotation context, LockedGM grades.
 * Five-man staffs (year 2026 ≥ 1994 modern cutoff).
 */
import type { ClassicTeam } from "../types";
import { finalizeClassicTeam } from "../roster-build";
import {
  applyCallupPatch,
  MLB_2026_CALLUPS,
} from "./mlb-2026-callups";
import {
  buildMlb2026Team,
  type Mlb26Spec,
} from "./mlb-2026-build";

const SPECS: Mlb26Spec[] = [
  {
    id: "yankees-2026",
    pfx: "nyy26",
    city: "New York",
    nickname: "Yankees",
    abbrev: "NYY",
    blurb:
      "2026 Bronx club — Judge and Bellinger in the grass, Fried on Opening Day. LockedGM five-man experiment pack.",
    lineup: [
      "Trent Grisham",
      "Aaron Judge",
      "Cody Bellinger",
      "Ben Rice",
      "Giancarlo Stanton",
      "Jazz Chisholm Jr.",
      "Jose Caballero",
      "Ryan McMahon",
      "Austin Wells",
    ],
    defense: {
      C: "Austin Wells",
      "1B": "Ben Rice",
      "2B": "Jazz Chisholm Jr.",
      "3B": "Ryan McMahon",
      SS: "Jose Caballero",
      LF: "Cody Bellinger",
      CF: "Trent Grisham",
      RF: "Aaron Judge",
    },
    rotation: [
      "Max Fried",
      "Cam Schlittler",
      "Will Warren",
      "Ryan Weathers",
      "Luis Gil",
    ],
    bullpen: ["Fernando Cruz", "Tim Hill", "Ian Hamilton"],
    bats: [
      { name: "Trent Grisham", bats: "L", pos: ["CF"], g: [13, 15, 14, 14, 13, 12, 2, -1] },
      { name: "Aaron Judge", bats: "R", pos: ["RF", "DH"], g: [16, 20, 18, 10, 12, 16, 0, 1] },
      { name: "Cody Bellinger", bats: "L", pos: ["LF", "CF", "1B"], g: [14, 15, 12, 13, 14, 13, 1, -1] },
      { name: "Ben Rice", bats: "L", pos: ["1B", "C", "DH"], g: [13, 14, 12, 9, 11, 11, 1, -1] },
      { name: "Giancarlo Stanton", bats: "R", pos: ["DH"], g: [12, 18, 12, 6, 8, 14, 0, 1] },
      { name: "Jazz Chisholm Jr.", bats: "L", pos: ["2B", "3B"], g: [13, 14, 11, 16, 12, 12, 1, -1] },
      { name: "Jose Caballero", bats: "R", pos: ["SS", "2B"], g: [12, 9, 11, 16, 13, 12] },
      { name: "Ryan McMahon", bats: "L", pos: ["3B"], g: [11, 13, 13, 9, 14, 14, 1, -2] },
      { name: "Austin Wells", bats: "L", pos: ["C"], g: [12, 13, 12, 8, 13, 13, 1, -1] },
    ],
    pits: [
      { name: "Max Fried", throws: "L", role: "SP", g: [17, 16, 14, 16, 1, 0] },
      { name: "Cam Schlittler", throws: "R", role: "SP", g: [14, 13, 11, 14] },
      { name: "Will Warren", throws: "R", role: "SP", g: [13, 12, 12, 14] },
      { name: "Ryan Weathers", throws: "L", role: "SP", g: [13, 12, 11, 13, 1, 0] },
      { name: "Luis Gil", throws: "R", role: "SP", g: [15, 11, 10, 14] },
      { name: "Fernando Cruz", throws: "R", role: "RP", g: [16, 12, 9, 8] },
      { name: "Tim Hill", throws: "L", role: "RP", g: [12, 14, 16, 7, 1, 0] },
      { name: "Ian Hamilton", throws: "R", role: "RP", g: [13, 12, 11, 8] },
    ],
  },
  {
    id: "dodgers-2026",
    pfx: "lad26",
    city: "Los Angeles",
    nickname: "Dodgers",
    abbrev: "LAD",
    blurb:
      "2026 Dodgers — Ohtani, Tucker, Betts, Freeman, and a five-man that still runs Yamamoto out front. LockedGM experiment pack.",
    lineup: [
      "Shohei Ohtani",
      "Kyle Tucker",
      "Mookie Betts",
      "Freddie Freeman",
      "Will Smith",
      "Max Muncy",
      "Teoscar Hernandez",
      "Andy Pages",
      "Miguel Rojas",
    ],
    defense: {
      C: "Will Smith",
      "1B": "Freddie Freeman",
      "2B": "Miguel Rojas",
      "3B": "Max Muncy",
      SS: "Mookie Betts",
      LF: "Teoscar Hernandez",
      CF: "Andy Pages",
      RF: "Kyle Tucker",
    },
    rotation: [
      "Yoshinobu Yamamoto",
      "Emmet Sheehan",
      "Tyler Glasnow",
      "Roki Sasaki",
      "Shohei Ohtani",
    ],
    bullpen: ["Tanner Scott", "Alex Vesia", "Blake Treinen"],
    bats: [
      { name: "Shohei Ohtani", bats: "L", throws: "R", pos: ["DH", "P"], g: [16, 19, 16, 14, 10, 12, 2, -1] },
      { name: "Kyle Tucker", bats: "L", pos: ["RF"], g: [16, 16, 16, 13, 14, 14, 1, -1] },
      { name: "Mookie Betts", bats: "R", pos: ["SS", "RF", "2B"], g: [16, 14, 15, 14, 16, 15, 0, 1] },
      { name: "Freddie Freeman", bats: "L", pos: ["1B"], g: [17, 14, 15, 10, 14, 12, 1, -1] },
      { name: "Will Smith", bats: "R", pos: ["C"], g: [14, 14, 15, 8, 14, 14] },
      { name: "Max Muncy", bats: "L", pos: ["3B"], g: [11, 15, 16, 7, 11, 12, 1, -2] },
      { name: "Teoscar Hernandez", bats: "R", pos: ["LF", "RF"], g: [13, 16, 10, 11, 11, 13] },
      { name: "Andy Pages", bats: "R", pos: ["CF", "RF"], g: [13, 14, 11, 12, 13, 13] },
      { name: "Miguel Rojas", bats: "R", pos: ["2B", "SS"], g: [13, 8, 11, 10, 15, 13] },
    ],
    pits: [
      { name: "Yoshinobu Yamamoto", throws: "R", role: "SP", g: [18, 16, 11, 15] },
      { name: "Emmet Sheehan", throws: "R", role: "SP", g: [15, 13, 10, 13] },
      { name: "Tyler Glasnow", throws: "R", role: "SP", g: [18, 13, 12, 13] },
      { name: "Roki Sasaki", throws: "R", role: "SP", g: [17, 12, 10, 13] },
      { name: "Shohei Ohtani", throws: "R", role: "SP", g: [19, 15, 10, 14] },
      { name: "Tanner Scott", throws: "L", role: "RP", g: [17, 12, 13, 8, 1, 0] },
      { name: "Alex Vesia", throws: "L", role: "RP", g: [15, 13, 10, 7, 1, 0] },
      { name: "Blake Treinen", throws: "R", role: "RP", g: [14, 13, 14, 7] },
    ],
  },
  {
    id: "blue-jays-2026",
    pfx: "tor26",
    city: "Toronto",
    nickname: "Blue Jays",
    abbrev: "TOR",
    blurb:
      "2026 Jays — Vladdy in the middle, Gausman and Cease up front after Bichette left town. LockedGM five-man pack.",
    lineup: [
      "George Springer",
      "Nathan Lukes",
      "Vladimir Guerrero Jr.",
      "Addison Barger",
      "Alejandro Kirk",
      "Daulton Varsho",
      "Kazuma Okamoto",
      "Ernie Clement",
      "Andres Gimenez",
    ],
    defense: {
      C: "Alejandro Kirk",
      "1B": "Vladimir Guerrero Jr.",
      "2B": "Ernie Clement",
      "3B": "Kazuma Okamoto",
      SS: "Andres Gimenez",
      LF: "Nathan Lukes",
      CF: "Daulton Varsho",
      RF: "Addison Barger",
    },
    rotation: [
      "Kevin Gausman",
      "Dylan Cease",
      "Eric Lauer",
      "Cody Ponce",
      "Max Scherzer",
    ],
    bullpen: ["Jeff Hoffman", "Yimi Garcia", "Brendon Little"],
    bats: [
      { name: "George Springer", bats: "R", pos: ["DH", "RF"], g: [13, 14, 13, 11, 11, 12] },
      { name: "Nathan Lukes", bats: "L", pos: ["LF", "RF"], g: [13, 10, 12, 12, 12, 11, 1, -1] },
      { name: "Vladimir Guerrero Jr.", bats: "R", pos: ["1B", "DH"], g: [16, 17, 14, 8, 11, 12] },
      { name: "Addison Barger", bats: "L", pos: ["RF", "3B"], g: [12, 14, 11, 11, 11, 13, 1, -1] },
      { name: "Alejandro Kirk", bats: "R", pos: ["C"], g: [14, 12, 14, 6, 13, 13] },
      { name: "Daulton Varsho", bats: "L", pos: ["CF"], g: [11, 13, 11, 14, 16, 14, 1, -1] },
      { name: "Kazuma Okamoto", bats: "R", pos: ["3B"], g: [13, 14, 12, 9, 12, 13] },
      { name: "Ernie Clement", bats: "R", pos: ["2B", "3B", "SS"], g: [13, 9, 10, 12, 13, 12] },
      { name: "Andres Gimenez", bats: "L", pos: ["SS", "2B"], g: [13, 10, 11, 15, 16, 14, 1, -1] },
    ],
    pits: [
      { name: "Kevin Gausman", throws: "R", role: "SP", g: [16, 15, 11, 16] },
      { name: "Dylan Cease", throws: "R", role: "SP", g: [17, 12, 10, 15] },
      { name: "Eric Lauer", throws: "L", role: "SP", g: [13, 13, 11, 13, 1, 0] },
      { name: "Cody Ponce", throws: "R", role: "SP", g: [13, 12, 12, 13] },
      { name: "Max Scherzer", throws: "R", role: "SP", g: [14, 14, 10, 12] },
      { name: "Jeff Hoffman", throws: "R", role: "RP", g: [16, 13, 11, 8] },
      { name: "Yimi Garcia", throws: "R", role: "RP", g: [14, 13, 12, 7] },
      { name: "Brendon Little", throws: "L", role: "RP", g: [13, 12, 13, 7, 1, 0] },
    ],
  },
  {
    id: "orioles-2026",
    pfx: "bal26",
    city: "Baltimore",
    nickname: "Orioles",
    abbrev: "BAL",
    blurb:
      "2026 Orioles — Henderson and Alonso in the heart, Holliday opening on the IL. LockedGM five-man pack.",
    lineup: [
      "Taylor Ward",
      "Gunnar Henderson",
      "Pete Alonso",
      "Adley Rutschman",
      "Samuel Basallo",
      "Tyler O'Neill",
      "Colton Cowser",
      "Coby Mayo",
      "Blaze Alexander",
    ],
    defense: {
      C: "Adley Rutschman",
      "1B": "Pete Alonso",
      "2B": "Blaze Alexander",
      "3B": "Coby Mayo",
      SS: "Gunnar Henderson",
      LF: "Taylor Ward",
      CF: "Colton Cowser",
      RF: "Tyler O'Neill",
    },
    rotation: [
      "Trevor Rogers",
      "Kyle Bradish",
      "Shane Baz",
      "Chris Bassitt",
      "Zach Eflin",
    ],
    bullpen: ["Felix Bautista", "Yennier Cano", "Keegan Akin"],
    bats: [
      { name: "Taylor Ward", bats: "R", pos: ["LF"], g: [13, 14, 13, 10, 12, 13] },
      { name: "Gunnar Henderson", bats: "L", pos: ["SS", "3B"], g: [15, 16, 14, 15, 14, 14, 1, -1] },
      { name: "Pete Alonso", bats: "R", pos: ["1B", "DH"], g: [13, 18, 14, 7, 11, 12] },
      { name: "Adley Rutschman", bats: "S", pos: ["C"], g: [14, 13, 16, 8, 14, 14] },
      { name: "Samuel Basallo", bats: "L", pos: ["DH", "C"], g: [13, 15, 12, 9, 10, 13, 1, -1] },
      { name: "Tyler O'Neill", bats: "R", pos: ["RF", "LF"], g: [12, 16, 12, 12, 12, 13] },
      { name: "Colton Cowser", bats: "L", pos: ["CF", "LF"], g: [12, 13, 13, 13, 13, 12, 1, -1] },
      { name: "Coby Mayo", bats: "R", pos: ["3B", "1B"], g: [12, 15, 12, 8, 11, 13] },
      { name: "Blaze Alexander", bats: "R", pos: ["2B", "SS", "3B"], g: [12, 11, 11, 12, 12, 12] },
    ],
    pits: [
      { name: "Trevor Rogers", throws: "L", role: "SP", g: [15, 14, 12, 15, 1, 0] },
      { name: "Kyle Bradish", throws: "R", role: "SP", g: [16, 14, 13, 14] },
      { name: "Shane Baz", throws: "R", role: "SP", g: [15, 12, 11, 14] },
      { name: "Chris Bassitt", throws: "R", role: "SP", g: [13, 14, 13, 15] },
      { name: "Zach Eflin", throws: "R", role: "SP", g: [13, 15, 14, 14] },
      { name: "Felix Bautista", throws: "R", role: "RP", g: [19, 12, 10, 8] },
      { name: "Yennier Cano", throws: "R", role: "RP", g: [14, 13, 15, 8] },
      { name: "Keegan Akin", throws: "L", role: "RP", g: [13, 13, 12, 7, 1, 0] },
    ],
  },
  {
    id: "rays-2026",
    pfx: "tb26",
    city: "Tampa Bay",
    nickname: "Rays",
    abbrev: "TB",
    blurb:
      "2026 Rays — Díaz, Aranda, and Caminero set the table; Rasmussen leads a patched five-man. LockedGM pack.",
    lineup: [
      "Yandy Diaz",
      "Ryan Vilade",
      "Jonathan Aranda",
      "Junior Caminero",
      "Ben Williamson",
      "Jonny DeLuca",
      "Nick Fortes",
      "Cedric Mullins",
      "Carson Williams",
    ],
    defense: {
      C: "Nick Fortes",
      "1B": "Jonathan Aranda",
      "2B": "Ben Williamson",
      "3B": "Junior Caminero",
      SS: "Carson Williams",
      LF: "Ryan Vilade",
      CF: "Cedric Mullins",
      RF: "Jonny DeLuca",
    },
    rotation: [
      "Drew Rasmussen",
      "Joe Boyle",
      "Steven Matz",
      "Nick Martinez",
      "Shane McClanahan",
    ],
    bullpen: ["Pete Fairbanks", "Garrett Cleavinger", "Edwin Uceta"],
    bats: [
      { name: "Yandy Diaz", bats: "R", pos: ["DH", "1B"], g: [16, 14, 14, 8, 11, 11] },
      { name: "Ryan Vilade", bats: "R", pos: ["LF", "3B"], g: [12, 11, 11, 12, 12, 12] },
      { name: "Jonathan Aranda", bats: "L", pos: ["1B", "DH"], g: [14, 14, 13, 8, 11, 11, 1, -1] },
      { name: "Junior Caminero", bats: "R", pos: ["3B"], g: [14, 16, 12, 11, 12, 13] },
      { name: "Ben Williamson", bats: "R", pos: ["2B", "3B"], g: [12, 10, 11, 12, 13, 12] },
      { name: "Jonny DeLuca", bats: "R", pos: ["RF", "CF"], g: [12, 11, 11, 15, 13, 12] },
      { name: "Nick Fortes", bats: "R", pos: ["C"], g: [11, 9, 11, 8, 13, 13] },
      { name: "Cedric Mullins", bats: "L", pos: ["CF"], g: [12, 12, 12, 15, 14, 12, 1, -1] },
      { name: "Carson Williams", bats: "R", pos: ["SS"], g: [12, 13, 11, 13, 14, 14] },
    ],
    pits: [
      { name: "Drew Rasmussen", throws: "R", role: "SP", g: [15, 15, 13, 13] },
      { name: "Joe Boyle", throws: "R", role: "SP", g: [14, 10, 11, 13] },
      { name: "Steven Matz", throws: "L", role: "SP", g: [13, 13, 13, 13, 1, 0] },
      { name: "Nick Martinez", throws: "R", role: "SP", g: [13, 14, 12, 14] },
      { name: "Shane McClanahan", throws: "L", role: "SP", g: [16, 14, 12, 13, 1, 0] },
      { name: "Pete Fairbanks", throws: "R", role: "RP", g: [16, 12, 11, 8] },
      { name: "Garrett Cleavinger", throws: "L", role: "RP", g: [14, 12, 12, 7, 1, 0] },
      { name: "Edwin Uceta", throws: "R", role: "RP", g: [14, 12, 11, 8] },
    ],
  },
  {
    id: "red-sox-2026",
    pfx: "bos26",
    city: "Boston",
    nickname: "Red Sox",
    abbrev: "BOS",
    blurb:
      "2026 Red Sox — Roman Anthony up top, Crochet-Suárez-Gray as a real five-man. LockedGM pack.",
    lineup: [
      "Roman Anthony",
      "Trevor Story",
      "Jarren Duran",
      "Willson Contreras",
      "Caleb Durbin",
      "Wilyer Abreu",
      "Isiah Kiner-Falefa",
      "Carlos Narvaez",
      "Ceddanne Rafaela",
    ],
    defense: {
      C: "Carlos Narvaez",
      "1B": "Willson Contreras",
      "2B": "Isiah Kiner-Falefa",
      "3B": "Caleb Durbin",
      SS: "Trevor Story",
      LF: "Roman Anthony",
      CF: "Ceddanne Rafaela",
      RF: "Wilyer Abreu",
    },
    rotation: [
      "Garrett Crochet",
      "Ranger Suarez",
      "Sonny Gray",
      "Brayan Bello",
      "Connelly Early",
    ],
    bullpen: ["Aroldis Chapman", "Justin Slaten", "Greg Weissert"],
    bats: [
      { name: "Roman Anthony", bats: "L", pos: ["LF", "RF"], g: [14, 14, 14, 13, 12, 13, 1, -1] },
      { name: "Trevor Story", bats: "R", pos: ["SS"], g: [13, 14, 11, 14, 14, 14] },
      { name: "Jarren Duran", bats: "L", pos: ["DH", "CF", "LF"], g: [14, 13, 12, 16, 13, 12, 1, -1] },
      { name: "Willson Contreras", bats: "R", pos: ["1B", "C"], g: [13, 15, 13, 8, 11, 13] },
      { name: "Caleb Durbin", bats: "R", pos: ["3B", "2B"], g: [13, 11, 12, 13, 13, 12] },
      { name: "Wilyer Abreu", bats: "L", pos: ["RF"], g: [12, 14, 13, 11, 13, 14, 1, -1] },
      { name: "Isiah Kiner-Falefa", bats: "R", pos: ["2B", "SS", "3B"], g: [13, 8, 10, 13, 13, 12] },
      { name: "Carlos Narvaez", bats: "R", pos: ["C"], g: [12, 11, 11, 8, 13, 13] },
      { name: "Ceddanne Rafaela", bats: "R", pos: ["CF", "SS"], g: [12, 11, 9, 15, 16, 14] },
    ],
    pits: [
      { name: "Garrett Crochet", throws: "L", role: "SP", g: [18, 15, 12, 16, 1, 0] },
      { name: "Ranger Suarez", throws: "L", role: "SP", g: [15, 15, 15, 15, 1, 0] },
      { name: "Sonny Gray", throws: "R", role: "SP", g: [15, 15, 13, 15] },
      { name: "Brayan Bello", throws: "R", role: "SP", g: [14, 13, 14, 15] },
      { name: "Connelly Early", throws: "L", role: "SP", g: [14, 12, 11, 13, 1, 0] },
      { name: "Aroldis Chapman", throws: "L", role: "RP", g: [17, 11, 11, 7, 1, 0] },
      { name: "Justin Slaten", throws: "R", role: "RP", g: [14, 14, 12, 8] },
      { name: "Greg Weissert", throws: "R", role: "RP", g: [13, 13, 13, 7] },
    ],
  },
  {
    id: "guardians-2026",
    pfx: "cle26",
    city: "Cleveland",
    nickname: "Guardians",
    abbrev: "CLE",
    blurb:
      "2026 Guardians — Ramírez still the face, Bibee on Opening Day. LockedGM five-man pack.",
    lineup: [
      "Steven Kwan",
      "Chase DeLauter",
      "Jose Ramirez",
      "Kyle Manzardo",
      "Bo Naylor",
      "Rhys Hoskins",
      "Daniel Schneemann",
      "Gabriel Arias",
      "Brayan Rocchio",
    ],
    defense: {
      C: "Bo Naylor",
      "1B": "Rhys Hoskins",
      "2B": "Brayan Rocchio",
      "3B": "Jose Ramirez",
      SS: "Gabriel Arias",
      LF: "Steven Kwan",
      CF: "Daniel Schneemann",
      RF: "Chase DeLauter",
    },
    rotation: [
      "Tanner Bibee",
      "Gavin Williams",
      "Slade Cecconi",
      "Joey Cantillo",
      "Parker Messick",
    ],
    bullpen: ["Cade Smith", "Hunter Gaddis", "Tim Herrin"],
    bats: [
      { name: "Steven Kwan", bats: "L", pos: ["LF"], g: [16, 9, 14, 13, 15, 13, 1, -1] },
      { name: "Chase DeLauter", bats: "L", pos: ["RF"], g: [13, 14, 12, 11, 12, 13, 1, -1] },
      { name: "Jose Ramirez", bats: "S", pos: ["3B"], g: [16, 16, 14, 16, 14, 14] },
      { name: "Kyle Manzardo", bats: "L", pos: ["DH", "1B"], g: [13, 15, 13, 8, 10, 11, 1, -1] },
      { name: "Bo Naylor", bats: "L", pos: ["C"], g: [12, 13, 12, 9, 13, 13, 1, -1] },
      { name: "Rhys Hoskins", bats: "R", pos: ["1B"], g: [12, 15, 14, 7, 11, 12] },
      { name: "Daniel Schneemann", bats: "L", pos: ["CF", "SS", "2B"], g: [12, 11, 12, 13, 12, 12, 1, -1] },
      { name: "Gabriel Arias", bats: "R", pos: ["SS", "3B"], g: [12, 13, 10, 11, 13, 14] },
      { name: "Brayan Rocchio", bats: "S", pos: ["2B", "SS"], g: [12, 10, 11, 13, 13, 12] },
    ],
    pits: [
      { name: "Tanner Bibee", throws: "R", role: "SP", g: [15, 14, 11, 15] },
      { name: "Gavin Williams", throws: "R", role: "SP", g: [15, 12, 11, 14] },
      { name: "Slade Cecconi", throws: "R", role: "SP", g: [13, 13, 12, 14] },
      { name: "Joey Cantillo", throws: "L", role: "SP", g: [13, 12, 11, 13, 1, 0] },
      { name: "Parker Messick", throws: "L", role: "SP", g: [13, 12, 12, 13, 1, 0] },
      { name: "Cade Smith", throws: "R", role: "RP", g: [17, 14, 11, 8] },
      { name: "Hunter Gaddis", throws: "R", role: "RP", g: [14, 14, 12, 8] },
      { name: "Tim Herrin", throws: "L", role: "RP", g: [13, 12, 13, 7, 1, 0] },
    ],
  },
  {
    id: "royals-2026",
    pfx: "kc26",
    city: "Kansas City",
    nickname: "Royals",
    abbrev: "KC",
    blurb:
      "2026 Royals — Witt Jr. still the engine, Ragans on a third straight Opening Day. LockedGM five-man pack.",
    lineup: [
      "Maikel Garcia",
      "Bobby Witt Jr.",
      "Lane Thomas",
      "Salvador Perez",
      "Vinnie Pasquantino",
      "Starling Marte",
      "Jonathan India",
      "Isaac Collins",
      "Carter Jensen",
    ],
    defense: {
      C: "Salvador Perez",
      "1B": "Vinnie Pasquantino",
      "2B": "Jonathan India",
      "3B": "Maikel Garcia",
      SS: "Bobby Witt Jr.",
      LF: "Isaac Collins",
      CF: "Lane Thomas",
      RF: "Starling Marte",
    },
    rotation: [
      "Cole Ragans",
      "Michael Wacha",
      "Seth Lugo",
      "Kris Bubic",
      "Noah Cameron",
    ],
    bullpen: ["Carlos Estevez", "Lucas Erceg", "John Schreiber"],
    bats: [
      { name: "Maikel Garcia", bats: "R", pos: ["3B", "2B"], g: [14, 11, 13, 15, 14, 13] },
      { name: "Bobby Witt Jr.", bats: "R", pos: ["SS"], g: [17, 16, 14, 18, 16, 16] },
      { name: "Lane Thomas", bats: "R", pos: ["CF", "RF"], g: [12, 13, 12, 14, 13, 13] },
      { name: "Salvador Perez", bats: "R", pos: ["C", "DH"], g: [13, 14, 9, 6, 12, 14] },
      { name: "Vinnie Pasquantino", bats: "L", pos: ["1B"], g: [14, 14, 14, 7, 11, 11, 1, -1] },
      { name: "Starling Marte", bats: "R", pos: ["RF", "DH"], g: [13, 12, 11, 13, 11, 13] },
      { name: "Jonathan India", bats: "R", pos: ["2B"], g: [13, 12, 14, 12, 12, 12] },
      { name: "Isaac Collins", bats: "S", pos: ["LF"], g: [12, 11, 12, 13, 12, 11] },
      { name: "Carter Jensen", bats: "L", pos: ["DH", "C"], g: [12, 13, 12, 8, 10, 12, 1, -1] },
    ],
    pits: [
      { name: "Cole Ragans", throws: "L", role: "SP", g: [17, 14, 11, 15, 1, 0] },
      { name: "Michael Wacha", throws: "R", role: "SP", g: [14, 15, 12, 15] },
      { name: "Seth Lugo", throws: "R", role: "SP", g: [14, 14, 12, 16] },
      { name: "Kris Bubic", throws: "L", role: "SP", g: [14, 14, 13, 14, 1, 0] },
      { name: "Noah Cameron", throws: "L", role: "SP", g: [13, 13, 12, 14, 1, 0] },
      { name: "Carlos Estevez", throws: "R", role: "RP", g: [15, 14, 11, 8] },
      { name: "Lucas Erceg", throws: "R", role: "RP", g: [15, 13, 13, 8] },
      { name: "John Schreiber", throws: "R", role: "RP", g: [13, 13, 13, 7] },
    ],
  },
  {
    id: "tigers-2026",
    pfx: "det26",
    city: "Detroit",
    nickname: "Tigers",
    abbrev: "DET",
    blurb:
      "2026 Tigers — Skubal, Valdez, and Verlander stacked; McGonigle debuts. LockedGM five-man pack.",
    lineup: [
      "Kerry Carpenter",
      "Gleyber Torres",
      "Colt Keith",
      "Riley Greene",
      "Spencer Torkelson",
      "Kevin McGonigle",
      "Dillon Dingler",
      "Parker Meadows",
      "Javier Baez",
    ],
    defense: {
      C: "Dillon Dingler",
      "1B": "Spencer Torkelson",
      "2B": "Gleyber Torres",
      "3B": "Kevin McGonigle",
      SS: "Javier Baez",
      LF: "Riley Greene",
      CF: "Parker Meadows",
      RF: "Kerry Carpenter",
    },
    rotation: [
      "Tarik Skubal",
      "Framber Valdez",
      "Jack Flaherty",
      "Justin Verlander",
      "Casey Mize",
    ],
    bullpen: ["Kenley Jansen", "Kyle Finnegan", "Will Vest"],
    bats: [
      { name: "Kerry Carpenter", bats: "L", pos: ["RF", "DH"], g: [13, 15, 11, 10, 11, 12, 2, -2] },
      { name: "Gleyber Torres", bats: "R", pos: ["2B"], g: [14, 13, 14, 10, 12, 12] },
      { name: "Colt Keith", bats: "L", pos: ["DH", "2B"], g: [13, 13, 12, 9, 11, 11, 1, -1] },
      { name: "Riley Greene", bats: "L", pos: ["LF"], g: [14, 16, 13, 12, 11, 12, 1, -1] },
      { name: "Spencer Torkelson", bats: "R", pos: ["1B"], g: [12, 15, 13, 8, 11, 12] },
      { name: "Kevin McGonigle", bats: "L", pos: ["3B", "SS"], g: [14, 12, 13, 13, 13, 13, 1, -1] },
      { name: "Dillon Dingler", bats: "R", pos: ["C"], g: [12, 12, 11, 8, 13, 13] },
      { name: "Parker Meadows", bats: "L", pos: ["CF"], g: [11, 12, 12, 15, 15, 13, 1, -1] },
      { name: "Javier Baez", bats: "R", pos: ["SS"], g: [12, 12, 8, 13, 14, 15] },
    ],
    pits: [
      { name: "Tarik Skubal", throws: "L", role: "SP", g: [20, 17, 12, 16, 1, 0] },
      { name: "Framber Valdez", throws: "L", role: "SP", g: [16, 14, 17, 16, 1, 0] },
      { name: "Jack Flaherty", throws: "R", role: "SP", g: [15, 13, 11, 14] },
      { name: "Justin Verlander", throws: "R", role: "SP", g: [14, 14, 11, 13] },
      { name: "Casey Mize", throws: "R", role: "SP", g: [14, 13, 13, 14] },
      { name: "Kenley Jansen", throws: "R", role: "RP", g: [15, 14, 10, 7] },
      { name: "Kyle Finnegan", throws: "R", role: "RP", g: [14, 13, 12, 8] },
      { name: "Will Vest", throws: "R", role: "RP", g: [14, 14, 13, 8] },
    ],
  },
  {
    id: "twins-2026",
    pfx: "min26",
    city: "Minnesota",
    nickname: "Twins",
    abbrev: "MIN",
    blurb:
      "2026 Twins — Buxton in center, Joe Ryan leading a rotation without Pablo López. LockedGM five-man pack.",
    lineup: [
      "Austin Martin",
      "Byron Buxton",
      "Luke Keaschall",
      "Ryan Jeffers",
      "Matt Wallner",
      "Josh Bell",
      "Victor Caratini",
      "Royce Lewis",
      "Brooks Lee",
    ],
    defense: {
      C: "Ryan Jeffers",
      "1B": "Victor Caratini",
      "2B": "Luke Keaschall",
      "3B": "Royce Lewis",
      SS: "Brooks Lee",
      LF: "Austin Martin",
      CF: "Byron Buxton",
      RF: "Matt Wallner",
    },
    rotation: [
      "Joe Ryan",
      "Bailey Ober",
      "Taj Bradley",
      "Simeon Woods Richardson",
      "Mick Abel",
    ],
    bullpen: ["Jhoan Duran", "Griffin Jax", "Cole Sands"],
    bats: [
      { name: "Austin Martin", bats: "R", pos: ["LF", "2B"], g: [12, 10, 12, 14, 12, 12] },
      { name: "Byron Buxton", bats: "R", pos: ["CF"], g: [13, 16, 11, 17, 16, 15] },
      { name: "Luke Keaschall", bats: "R", pos: ["2B"], g: [13, 12, 12, 13, 12, 12] },
      { name: "Ryan Jeffers", bats: "R", pos: ["C"], g: [12, 14, 12, 8, 12, 13] },
      { name: "Matt Wallner", bats: "L", pos: ["RF"], g: [11, 16, 14, 9, 11, 13, 2, -2] },
      { name: "Josh Bell", bats: "S", pos: ["DH", "1B"], g: [13, 14, 14, 7, 10, 11] },
      { name: "Victor Caratini", bats: "S", pos: ["1B", "C"], g: [13, 11, 12, 7, 12, 12] },
      { name: "Royce Lewis", bats: "R", pos: ["3B"], g: [13, 15, 11, 13, 12, 13] },
      { name: "Brooks Lee", bats: "S", pos: ["SS", "2B", "3B"], g: [13, 12, 11, 11, 12, 12] },
    ],
    pits: [
      { name: "Joe Ryan", throws: "R", role: "SP", g: [16, 15, 10, 15] },
      { name: "Bailey Ober", throws: "R", role: "SP", g: [14, 14, 11, 15] },
      { name: "Taj Bradley", throws: "R", role: "SP", g: [15, 12, 11, 14] },
      { name: "Simeon Woods Richardson", throws: "R", role: "SP", g: [13, 13, 12, 14] },
      { name: "Mick Abel", throws: "R", role: "SP", g: [14, 12, 11, 13] },
      { name: "Jhoan Duran", throws: "R", role: "RP", g: [18, 13, 13, 8] },
      { name: "Griffin Jax", throws: "R", role: "RP", g: [15, 14, 12, 8] },
      { name: "Cole Sands", throws: "R", role: "RP", g: [13, 13, 12, 8] },
    ],
  },
  {
    id: "white-sox-2026",
    pfx: "cws26",
    city: "Chicago",
    nickname: "White Sox",
    abbrev: "CWS",
    blurb:
      "2026 White Sox — Murakami in the heart, Shane Smith on Opening Day. LockedGM five-man pack.",
    lineup: [
      "Chase Meidroth",
      "Colson Montgomery",
      "Miguel Vargas",
      "Andrew Benintendi",
      "Austin Hays",
      "Munetaka Murakami",
      "Everson Pereira",
      "Edgar Quero",
      "Luisangel Acuna",
    ],
    defense: {
      C: "Edgar Quero",
      "1B": "Munetaka Murakami",
      "2B": "Chase Meidroth",
      "3B": "Miguel Vargas",
      SS: "Colson Montgomery",
      LF: "Austin Hays",
      CF: "Luisangel Acuna",
      RF: "Everson Pereira",
    },
    rotation: [
      "Shane Smith",
      "Sean Burke",
      "Anthony Kay",
      "Davis Martin",
      "Erick Fedde",
    ],
    bullpen: ["Grant Taylor", "Jordan Leasure", "Brandon Eisert"],
    bats: [
      { name: "Chase Meidroth", bats: "R", pos: ["2B", "SS"], g: [13, 9, 13, 12, 13, 12] },
      { name: "Colson Montgomery", bats: "L", pos: ["SS"], g: [12, 16, 12, 10, 12, 14, 1, -1] },
      { name: "Miguel Vargas", bats: "R", pos: ["3B", "1B"], g: [13, 15, 14, 10, 12, 12] },
      { name: "Andrew Benintendi", bats: "L", pos: ["DH", "LF"], g: [13, 13, 12, 10, 11, 12, 1, -1] },
      { name: "Austin Hays", bats: "R", pos: ["LF"], g: [13, 13, 10, 11, 13, 13] },
      { name: "Munetaka Murakami", bats: "L", pos: ["1B", "3B"], g: [12, 17, 13, 8, 11, 13, 1, -1] },
      { name: "Everson Pereira", bats: "R", pos: ["RF"], g: [12, 13, 10, 13, 12, 13] },
      { name: "Edgar Quero", bats: "S", pos: ["C"], g: [12, 11, 12, 8, 12, 12] },
      { name: "Luisangel Acuna", bats: "R", pos: ["CF", "2B"], g: [12, 10, 11, 15, 13, 12] },
    ],
    pits: [
      { name: "Shane Smith", throws: "R", role: "SP", g: [14, 13, 12, 14] },
      { name: "Sean Burke", throws: "R", role: "SP", g: [13, 12, 12, 14] },
      { name: "Anthony Kay", throws: "L", role: "SP", g: [13, 12, 12, 13, 1, 0] },
      { name: "Davis Martin", throws: "R", role: "SP", g: [13, 13, 12, 14] },
      { name: "Erick Fedde", throws: "R", role: "SP", g: [13, 13, 12, 14] },
      { name: "Grant Taylor", throws: "R", role: "RP", g: [15, 12, 11, 8] },
      { name: "Jordan Leasure", throws: "R", role: "RP", g: [14, 12, 10, 7] },
      { name: "Brandon Eisert", throws: "L", role: "RP", g: [12, 13, 13, 7, 1, 0] },
    ],
  },
  {
    id: "angels-2026",
    pfx: "laa26",
    city: "Los Angeles",
    nickname: "Angels",
    abbrev: "LAA",
    blurb:
      "2026 Angels — Trout back in center, Neto up top, Soriano on Opening Day. LockedGM five-man pack.",
    lineup: [
      "Zach Neto",
      "Mike Trout",
      "Nolan Schanuel",
      "Jorge Soler",
      "Yoan Moncada",
      "Jo Adell",
      "Josh Lowe",
      "Logan O'Hoppe",
      "Oswald Peraza",
    ],
    defense: {
      C: "Logan O'Hoppe",
      "1B": "Nolan Schanuel",
      "2B": "Oswald Peraza",
      "3B": "Yoan Moncada",
      SS: "Zach Neto",
      LF: "Josh Lowe",
      CF: "Mike Trout",
      RF: "Jo Adell",
    },
    rotation: [
      "Jose Soriano",
      "Yusei Kikuchi",
      "Reid Detmers",
      "Ryan Johnson",
      "Jack Kochanowicz",
    ],
    bullpen: ["Ben Joyce", "Robert Stephenson", "Brock Burke"],
    bats: [
      { name: "Zach Neto", bats: "R", pos: ["SS"], g: [13, 13, 12, 14, 14, 13] },
      { name: "Mike Trout", bats: "R", pos: ["CF", "DH"], g: [14, 17, 16, 12, 13, 14] },
      { name: "Nolan Schanuel", bats: "L", pos: ["1B"], g: [14, 11, 15, 9, 12, 11, 1, -1] },
      { name: "Jorge Soler", bats: "R", pos: ["DH", "RF"], g: [12, 16, 14, 8, 10, 13] },
      { name: "Yoan Moncada", bats: "S", pos: ["3B"], g: [12, 13, 13, 10, 13, 14] },
      { name: "Jo Adell", bats: "R", pos: ["RF"], g: [12, 15, 10, 13, 12, 14] },
      { name: "Josh Lowe", bats: "L", pos: ["LF", "RF"], g: [13, 13, 12, 14, 12, 12, 1, -1] },
      { name: "Logan O'Hoppe", bats: "R", pos: ["C"], g: [12, 14, 11, 8, 13, 13] },
      { name: "Oswald Peraza", bats: "R", pos: ["2B", "SS", "3B"], g: [12, 11, 11, 13, 13, 13] },
    ],
    pits: [
      { name: "Jose Soriano", throws: "R", role: "SP", g: [15, 12, 15, 15] },
      { name: "Yusei Kikuchi", throws: "L", role: "SP", g: [14, 12, 11, 15, 1, 0] },
      { name: "Reid Detmers", throws: "L", role: "SP", g: [14, 12, 11, 14, 1, 0] },
      { name: "Ryan Johnson", throws: "R", role: "SP", g: [13, 12, 12, 13] },
      { name: "Jack Kochanowicz", throws: "R", role: "SP", g: [12, 13, 14, 14] },
      { name: "Ben Joyce", throws: "R", role: "RP", g: [16, 12, 12, 7] },
      { name: "Robert Stephenson", throws: "R", role: "RP", g: [15, 12, 10, 7] },
      { name: "Brock Burke", throws: "L", role: "RP", g: [13, 13, 13, 7, 1, 0] },
    ],
  },
  {
    id: "astros-2026",
    pfx: "hou26",
    city: "Houston",
    nickname: "Astros",
    abbrev: "HOU",
    blurb:
      "2026 Astros — Altuve and Alvarez still the spine, Hunter Brown on Opening Day. LockedGM five-man pack.",
    lineup: [
      "Jose Altuve",
      "Yordan Alvarez",
      "Isaac Paredes",
      "Carlos Correa",
      "Joey Loperfido",
      "Cam Smith",
      "Christian Walker",
      "Yainer Diaz",
      "Jake Meyers",
    ],
    defense: {
      C: "Yainer Diaz",
      "1B": "Christian Walker",
      "2B": "Jose Altuve",
      "3B": "Isaac Paredes",
      SS: "Carlos Correa",
      LF: "Joey Loperfido",
      CF: "Jake Meyers",
      RF: "Cam Smith",
    },
    rotation: [
      "Hunter Brown",
      "Mike Burrows",
      "Cristian Javier",
      "Tatsuya Imai",
      "Lance McCullers Jr.",
    ],
    bullpen: ["Josh Hader", "Bryan Abreu", "Bryan King"],
    bats: [
      { name: "Jose Altuve", bats: "R", pos: ["2B", "LF"], g: [15, 13, 13, 12, 12, 11] },
      { name: "Yordan Alvarez", bats: "L", pos: ["DH", "LF"], g: [16, 19, 15, 8, 10, 13, 1, -1] },
      { name: "Isaac Paredes", bats: "R", pos: ["3B", "1B"], g: [13, 15, 15, 8, 12, 12] },
      { name: "Carlos Correa", bats: "R", pos: ["SS"], g: [14, 13, 13, 10, 14, 15] },
      { name: "Joey Loperfido", bats: "L", pos: ["LF", "CF"], g: [12, 13, 11, 13, 12, 12, 1, -1] },
      { name: "Cam Smith", bats: "R", pos: ["RF"], g: [13, 14, 12, 12, 12, 13] },
      { name: "Christian Walker", bats: "R", pos: ["1B"], g: [13, 15, 12, 8, 14, 12] },
      { name: "Yainer Diaz", bats: "R", pos: ["C"], g: [14, 14, 9, 8, 12, 13] },
      { name: "Jake Meyers", bats: "R", pos: ["CF"], g: [12, 10, 11, 14, 15, 13] },
    ],
    pits: [
      { name: "Hunter Brown", throws: "R", role: "SP", g: [17, 14, 13, 16] },
      { name: "Mike Burrows", throws: "R", role: "SP", g: [13, 12, 12, 14] },
      { name: "Cristian Javier", throws: "R", role: "SP", g: [14, 12, 10, 14] },
      { name: "Tatsuya Imai", throws: "R", role: "SP", g: [14, 13, 11, 14] },
      { name: "Lance McCullers Jr.", throws: "R", role: "SP", g: [14, 12, 14, 13] },
      { name: "Josh Hader", throws: "L", role: "RP", g: [18, 13, 10, 8, 1, 0] },
      { name: "Bryan Abreu", throws: "R", role: "RP", g: [16, 12, 12, 8] },
      { name: "Bryan King", throws: "L", role: "RP", g: [14, 13, 13, 7, 1, 0] },
    ],
  },
  {
    id: "athletics-2026",
    pfx: "ath26",
    city: "Sacramento",
    nickname: "Athletics",
    abbrev: "ATH",
    blurb:
      "2026 Athletics in Sacramento — Kurtz leading off, Severino on Opening Day. LockedGM five-man pack.",
    lineup: [
      "Nick Kurtz",
      "Shea Langeliers",
      "Tyler Soderstrom",
      "Brent Rooker",
      "Jacob Wilson",
      "Lawrence Butler",
      "Max Muncy",
      "Jeff McNeil",
      "Denzel Clarke",
    ],
    defense: {
      C: "Shea Langeliers",
      "1B": "Nick Kurtz",
      "2B": "Jeff McNeil",
      "3B": "Max Muncy",
      SS: "Jacob Wilson",
      LF: "Tyler Soderstrom",
      CF: "Denzel Clarke",
      RF: "Lawrence Butler",
    },
    rotation: [
      "Luis Severino",
      "Jeffrey Springs",
      "Luis Morales",
      "Jacob Lopez",
      "Aaron Civale",
    ],
    bullpen: ["Mason Miller", "Tyler Ferguson", "Michel Otanez"],
    bats: [
      { name: "Nick Kurtz", bats: "L", pos: ["1B"], g: [14, 16, 14, 10, 12, 12, 1, -1] },
      { name: "Shea Langeliers", bats: "R", pos: ["C"], g: [12, 16, 11, 8, 12, 14] },
      { name: "Tyler Soderstrom", bats: "L", pos: ["LF", "1B"], g: [13, 15, 12, 9, 11, 12, 1, -1] },
      { name: "Brent Rooker", bats: "R", pos: ["DH"], g: [13, 17, 13, 8, 9, 12] },
      { name: "Jacob Wilson", bats: "R", pos: ["SS"], g: [15, 10, 12, 12, 14, 13] },
      { name: "Lawrence Butler", bats: "L", pos: ["RF"], g: [13, 14, 12, 14, 12, 13, 1, -1] },
      { name: "Max Muncy", bats: "R", pos: ["3B", "SS"], g: [12, 11, 11, 12, 12, 12] },
      { name: "Jeff McNeil", bats: "L", pos: ["2B", "RF"], g: [14, 11, 13, 11, 13, 12, 1, -1] },
      { name: "Denzel Clarke", bats: "R", pos: ["CF"], g: [11, 11, 11, 16, 15, 13] },
    ],
    pits: [
      { name: "Luis Severino", throws: "R", role: "SP", g: [14, 13, 12, 15] },
      { name: "Jeffrey Springs", throws: "L", role: "SP", g: [14, 14, 11, 14, 1, 0] },
      { name: "Luis Morales", throws: "R", role: "SP", g: [14, 12, 11, 13] },
      { name: "Jacob Lopez", throws: "L", role: "SP", g: [13, 12, 12, 13, 1, 0] },
      { name: "Aaron Civale", throws: "R", role: "SP", g: [13, 14, 12, 14] },
      { name: "Mason Miller", throws: "R", role: "RP", g: [19, 13, 11, 8] },
      { name: "Tyler Ferguson", throws: "R", role: "RP", g: [13, 13, 12, 7] },
      { name: "Michel Otanez", throws: "R", role: "RP", g: [14, 11, 11, 7] },
    ],
  },
  {
    id: "mariners-2026",
    pfx: "sea26",
    city: "Seattle",
    nickname: "Mariners",
    abbrev: "SEA",
    blurb:
      "2026 Mariners — Raleigh and Julio in the heart, Gilbert-Kirby-Woo still the ceiling. LockedGM five-man pack.",
    lineup: [
      "Brendan Donovan",
      "Cal Raleigh",
      "Julio Rodriguez",
      "Josh Naylor",
      "Randy Arozarena",
      "Luke Raley",
      "Dominic Canzone",
      "Cole Young",
      "Leo Rivas",
    ],
    defense: {
      C: "Cal Raleigh",
      "1B": "Josh Naylor",
      "2B": "Cole Young",
      "3B": "Brendan Donovan",
      SS: "Leo Rivas",
      LF: "Randy Arozarena",
      CF: "Julio Rodriguez",
      RF: "Luke Raley",
    },
    rotation: [
      "Logan Gilbert",
      "George Kirby",
      "Bryan Woo",
      "Luis Castillo",
      "Bryce Miller",
    ],
    bullpen: ["Andres Munoz", "Matt Brash", "Gabe Speier"],
    bats: [
      { name: "Brendan Donovan", bats: "L", pos: ["3B", "2B", "LF"], g: [14, 11, 14, 11, 13, 12, 1, -1] },
      { name: "Cal Raleigh", bats: "S", pos: ["C"], g: [13, 18, 14, 8, 13, 14] },
      { name: "Julio Rodriguez", bats: "R", pos: ["CF"], g: [15, 16, 13, 16, 14, 15] },
      { name: "Josh Naylor", bats: "L", pos: ["1B"], g: [15, 15, 12, 9, 12, 11, 1, -1] },
      { name: "Randy Arozarena", bats: "R", pos: ["LF"], g: [13, 14, 14, 14, 12, 13] },
      { name: "Luke Raley", bats: "L", pos: ["RF", "1B"], g: [12, 14, 12, 12, 12, 12, 2, -2] },
      { name: "Dominic Canzone", bats: "L", pos: ["DH", "RF"], g: [13, 13, 11, 10, 11, 12, 1, -1] },
      { name: "Cole Young", bats: "L", pos: ["2B"], g: [13, 11, 12, 12, 12, 12, 1, -1] },
      { name: "Leo Rivas", bats: "S", pos: ["SS", "2B"], g: [12, 8, 12, 13, 13, 12] },
    ],
    pits: [
      { name: "Logan Gilbert", throws: "R", role: "SP", g: [17, 16, 11, 16] },
      { name: "George Kirby", throws: "R", role: "SP", g: [16, 18, 12, 15] },
      { name: "Bryan Woo", throws: "R", role: "SP", g: [16, 16, 12, 15] },
      { name: "Luis Castillo", throws: "R", role: "SP", g: [15, 14, 13, 16] },
      { name: "Bryce Miller", throws: "R", role: "SP", g: [15, 14, 12, 14] },
      { name: "Andres Munoz", throws: "R", role: "RP", g: [18, 14, 13, 8] },
      { name: "Matt Brash", throws: "R", role: "RP", g: [16, 12, 13, 7] },
      { name: "Gabe Speier", throws: "L", role: "RP", g: [14, 14, 12, 7, 1, 0] },
    ],
  },
  {
    id: "rangers-2026",
    pfx: "tex26",
    city: "Texas",
    nickname: "Rangers",
    abbrev: "TEX",
    blurb:
      "2026 Rangers — Nimmo and Langford set the table for Seager; deGrom still the ace. LockedGM five-man pack.",
    lineup: [
      "Brandon Nimmo",
      "Wyatt Langford",
      "Corey Seager",
      "Jake Burger",
      "Andrew McCutchen",
      "Josh Jung",
      "Josh Smith",
      "Danny Jansen",
      "Sam Haggerty",
    ],
    defense: {
      C: "Danny Jansen",
      "1B": "Jake Burger",
      "2B": "Josh Smith",
      "3B": "Josh Jung",
      SS: "Corey Seager",
      LF: "Sam Haggerty",
      CF: "Wyatt Langford",
      RF: "Brandon Nimmo",
    },
    rotation: [
      "Jacob deGrom",
      "Nathan Eovaldi",
      "MacKenzie Gore",
      "Jack Leiter",
      "Kumar Rocker",
    ],
    bullpen: ["Robert Garcia", "Chris Martin", "Jacob Latz"],
    bats: [
      { name: "Brandon Nimmo", bats: "L", pos: ["RF", "LF", "CF"], g: [14, 13, 14, 12, 13, 12, 1, -1] },
      { name: "Wyatt Langford", bats: "R", pos: ["CF", "LF"], g: [14, 15, 13, 14, 13, 13] },
      { name: "Corey Seager", bats: "L", pos: ["SS"], g: [16, 16, 14, 9, 13, 14, 1, -1] },
      { name: "Jake Burger", bats: "R", pos: ["1B", "3B"], g: [13, 16, 10, 7, 10, 12] },
      { name: "Andrew McCutchen", bats: "R", pos: ["DH"], g: [13, 13, 14, 10, 9, 12] },
      { name: "Josh Jung", bats: "R", pos: ["3B"], g: [13, 14, 11, 9, 13, 13] },
      { name: "Josh Smith", bats: "L", pos: ["2B", "3B", "SS"], g: [13, 11, 13, 12, 13, 12, 1, -1] },
      { name: "Danny Jansen", bats: "R", pos: ["C"], g: [12, 13, 13, 7, 13, 13] },
      { name: "Sam Haggerty", bats: "S", pos: ["LF", "2B"], g: [12, 9, 12, 16, 12, 11] },
    ],
    pits: [
      { name: "Jacob deGrom", throws: "R", role: "SP", g: [19, 17, 12, 14] },
      { name: "Nathan Eovaldi", throws: "R", role: "SP", g: [15, 15, 13, 15] },
      { name: "MacKenzie Gore", throws: "L", role: "SP", g: [15, 13, 11, 15, 1, 0] },
      { name: "Jack Leiter", throws: "R", role: "SP", g: [14, 12, 11, 14] },
      { name: "Kumar Rocker", throws: "R", role: "SP", g: [14, 11, 13, 13] },
      { name: "Robert Garcia", throws: "L", role: "RP", g: [15, 13, 12, 8, 1, 0] },
      { name: "Chris Martin", throws: "R", role: "RP", g: [14, 15, 13, 7] },
      { name: "Jacob Latz", throws: "L", role: "RP", g: [13, 13, 12, 8, 1, 0] },
    ],
  },
  {
    id: "braves-2026",
    pfx: "atl26",
    city: "Atlanta",
    nickname: "Braves",
    abbrev: "ATL",
    blurb:
      "2026 Braves — Acuña and Olson still the punch; Sale leads a rotation thinned by the IL. LockedGM five-man pack.",
    lineup: [
      "Ronald Acuna Jr.",
      "Drake Baldwin",
      "Ozzie Albies",
      "Matt Olson",
      "Austin Riley",
      "Eli White",
      "Mauricio Dubon",
      "Jonah Heim",
      "Michael Harris II",
    ],
    defense: {
      C: "Jonah Heim",
      "1B": "Matt Olson",
      "2B": "Ozzie Albies",
      "3B": "Austin Riley",
      SS: "Mauricio Dubon",
      LF: "Eli White",
      CF: "Michael Harris II",
      RF: "Ronald Acuna Jr.",
    },
    rotation: [
      "Chris Sale",
      "Reynaldo Lopez",
      "Grant Holmes",
      "Bryce Elder",
      "Jose Suarez",
    ],
    bullpen: ["Raisel Iglesias", "Pierce Johnson", "Dylan Lee"],
    bats: [
      { name: "Ronald Acuna Jr.", bats: "R", pos: ["RF"], g: [16, 17, 15, 17, 13, 15] },
      { name: "Drake Baldwin", bats: "L", pos: ["DH", "C"], g: [14, 14, 13, 8, 11, 12, 1, -1] },
      { name: "Ozzie Albies", bats: "S", pos: ["2B"], g: [14, 13, 11, 14, 14, 13] },
      { name: "Matt Olson", bats: "L", pos: ["1B"], g: [14, 17, 16, 8, 13, 12, 1, -1] },
      { name: "Austin Riley", bats: "R", pos: ["3B"], g: [14, 16, 13, 9, 13, 14] },
      { name: "Eli White", bats: "R", pos: ["LF", "CF"], g: [12, 11, 11, 14, 13, 12] },
      { name: "Mauricio Dubon", bats: "R", pos: ["SS", "2B", "CF"], g: [13, 9, 10, 12, 14, 12] },
      { name: "Jonah Heim", bats: "S", pos: ["C"], g: [12, 12, 11, 7, 13, 14] },
      { name: "Michael Harris II", bats: "L", pos: ["CF"], g: [14, 13, 10, 15, 16, 14, 1, -1] },
    ],
    pits: [
      { name: "Chris Sale", throws: "L", role: "SP", g: [17, 16, 12, 14, 1, 0] },
      { name: "Reynaldo Lopez", throws: "R", role: "SP", g: [14, 13, 11, 14] },
      { name: "Grant Holmes", throws: "R", role: "SP", g: [14, 13, 12, 14] },
      { name: "Bryce Elder", throws: "R", role: "SP", g: [13, 13, 14, 15] },
      { name: "Jose Suarez", throws: "L", role: "SP", g: [12, 12, 12, 13, 1, 0] },
      { name: "Raisel Iglesias", throws: "R", role: "RP", g: [16, 15, 11, 8] },
      { name: "Pierce Johnson", throws: "R", role: "RP", g: [14, 13, 12, 7] },
      { name: "Dylan Lee", throws: "L", role: "RP", g: [13, 14, 12, 7, 1, 0] },
    ],
  },
  {
    id: "marlins-2026",
    pfx: "mia26",
    city: "Miami",
    nickname: "Marlins",
    abbrev: "MIA",
    blurb:
      "2026 Marlins — Alcantara and Eury still the story; Stowers opens on the IL. LockedGM five-man pack.",
    lineup: [
      "Austin Slater",
      "Agustin Ramirez",
      "Jakob Marsee",
      "Otto Lopez",
      "Connor Norby",
      "Heriberto Hernandez",
      "Xavier Edwards",
      "Owen Caissie",
      "Javier Sanoja",
    ],
    defense: {
      C: "Agustin Ramirez",
      "1B": "Connor Norby",
      "2B": "Xavier Edwards",
      "3B": "Javier Sanoja",
      SS: "Otto Lopez",
      LF: "Heriberto Hernandez",
      CF: "Jakob Marsee",
      RF: "Austin Slater",
    },
    rotation: [
      "Sandy Alcantara",
      "Eury Perez",
      "Max Meyer",
      "Chris Paddack",
      "Janson Junk",
    ],
    bullpen: ["Calvin Faucher", "Anthony Bender", "Ronny Henriquez"],
    bats: [
      { name: "Austin Slater", bats: "R", pos: ["RF", "LF"], g: [12, 12, 13, 12, 12, 12] },
      { name: "Agustin Ramirez", bats: "R", pos: ["C"], g: [13, 14, 11, 9, 12, 13] },
      { name: "Jakob Marsee", bats: "L", pos: ["CF"], g: [13, 11, 13, 15, 13, 12, 1, -1] },
      { name: "Otto Lopez", bats: "R", pos: ["SS", "2B"], g: [13, 10, 11, 13, 13, 12] },
      { name: "Connor Norby", bats: "R", pos: ["1B", "2B", "3B"], g: [12, 13, 11, 11, 11, 12] },
      { name: "Heriberto Hernandez", bats: "R", pos: ["LF"], g: [12, 14, 12, 10, 11, 12] },
      { name: "Xavier Edwards", bats: "S", pos: ["2B", "SS"], g: [14, 7, 13, 16, 13, 12] },
      { name: "Owen Caissie", bats: "L", pos: ["DH", "RF"], g: [12, 14, 12, 10, 11, 13, 1, -1] },
      { name: "Javier Sanoja", bats: "R", pos: ["3B", "2B"], g: [12, 10, 11, 12, 12, 12] },
    ],
    pits: [
      { name: "Sandy Alcantara", throws: "R", role: "SP", g: [16, 14, 14, 16] },
      { name: "Eury Perez", throws: "R", role: "SP", g: [17, 13, 11, 14] },
      { name: "Max Meyer", throws: "R", role: "SP", g: [14, 13, 13, 14] },
      { name: "Chris Paddack", throws: "R", role: "SP", g: [13, 14, 11, 13] },
      { name: "Janson Junk", throws: "R", role: "SP", g: [13, 13, 12, 13] },
      { name: "Calvin Faucher", throws: "R", role: "RP", g: [14, 13, 12, 8] },
      { name: "Anthony Bender", throws: "R", role: "RP", g: [14, 13, 13, 7] },
      { name: "Ronny Henriquez", throws: "R", role: "RP", g: [14, 12, 11, 7] },
    ],
  },
  {
    id: "mets-2026",
    pfx: "nym26",
    city: "New York",
    nickname: "Mets",
    abbrev: "NYM",
    blurb:
      "2026 Mets — Soto and Lindor stay; Bichette, Robert, Peralta, and Williams are the winter. LockedGM five-man pack.",
    lineup: [
      "Francisco Lindor",
      "Juan Soto",
      "Bo Bichette",
      "Jorge Polanco",
      "Luis Robert Jr.",
      "Brett Baty",
      "Marcus Semien",
      "Carson Benge",
      "Francisco Alvarez",
    ],
    defense: {
      C: "Francisco Alvarez",
      "1B": "Jorge Polanco",
      "2B": "Marcus Semien",
      "3B": "Bo Bichette",
      SS: "Francisco Lindor",
      LF: "Juan Soto",
      CF: "Luis Robert Jr.",
      RF: "Carson Benge",
    },
    rotation: [
      "Freddy Peralta",
      "David Peterson",
      "Nolan McLean",
      "Clay Holmes",
      "Kodai Senga",
    ],
    bullpen: ["Devin Williams", "Luke Weaver", "Reed Garrett"],
    bats: [
      { name: "Francisco Lindor", bats: "S", pos: ["SS"], g: [15, 15, 14, 15, 16, 15] },
      { name: "Juan Soto", bats: "L", pos: ["LF", "RF"], g: [16, 17, 19, 11, 12, 15, 1, -1] },
      { name: "Bo Bichette", bats: "R", pos: ["3B", "SS"], g: [16, 14, 12, 13, 12, 13] },
      { name: "Jorge Polanco", bats: "S", pos: ["1B", "2B", "DH"], g: [14, 14, 13, 9, 11, 12] },
      { name: "Luis Robert Jr.", bats: "R", pos: ["CF"], g: [13, 15, 11, 16, 15, 14] },
      { name: "Brett Baty", bats: "L", pos: ["DH", "3B"], g: [12, 13, 12, 10, 11, 12, 1, -1] },
      { name: "Marcus Semien", bats: "R", pos: ["2B"], g: [14, 13, 13, 13, 15, 13] },
      { name: "Carson Benge", bats: "L", pos: ["RF"], g: [13, 13, 13, 12, 12, 13, 1, -1] },
      { name: "Francisco Alvarez", bats: "R", pos: ["C"], g: [12, 15, 12, 8, 13, 15] },
    ],
    pits: [
      { name: "Freddy Peralta", throws: "R", role: "SP", g: [16, 14, 10, 15] },
      { name: "David Peterson", throws: "L", role: "SP", g: [14, 13, 14, 15, 1, 0] },
      { name: "Nolan McLean", throws: "R", role: "SP", g: [14, 13, 12, 14] },
      { name: "Clay Holmes", throws: "R", role: "SP", g: [14, 13, 15, 14] },
      { name: "Kodai Senga", throws: "R", role: "SP", g: [16, 13, 11, 14] },
      { name: "Devin Williams", throws: "R", role: "RP", g: [18, 13, 12, 8] },
      { name: "Luke Weaver", throws: "R", role: "RP", g: [15, 14, 11, 8] },
      { name: "Reed Garrett", throws: "R", role: "RP", g: [14, 13, 12, 8] },
    ],
  },
  {
    id: "nationals-2026",
    pfx: "wsh26",
    city: "Washington",
    nickname: "Nationals",
    abbrev: "WSH",
    blurb:
      "2026 Nationals — James Wood drives the order; Cavalli finally gets Opening Day. LockedGM five-man pack.",
    lineup: [
      "James Wood",
      "Andres Chaparro",
      "Brady House",
      "Daylen Lile",
      "Joey Wiemer",
      "CJ Abrams",
      "Nasim Nunez",
      "Keibert Ruiz",
      "Jacob Young",
    ],
    defense: {
      C: "Keibert Ruiz",
      "1B": "Andres Chaparro",
      "2B": "Nasim Nunez",
      "3B": "Brady House",
      SS: "CJ Abrams",
      LF: "James Wood",
      CF: "Jacob Young",
      RF: "Joey Wiemer",
    },
    rotation: [
      "Cade Cavalli",
      "Foster Griffin",
      "Zack Littell",
      "Miles Mikolas",
      "Jake Irvin",
    ],
    bullpen: ["Jose A. Ferrer", "Kyle Finnegan", "Brad Lord"],
    bats: [
      { name: "James Wood", bats: "L", pos: ["LF"], g: [14, 17, 14, 13, 12, 14, 1, -1] },
      { name: "Andres Chaparro", bats: "R", pos: ["1B"], g: [12, 14, 12, 8, 11, 12] },
      { name: "Brady House", bats: "R", pos: ["3B"], g: [12, 14, 11, 10, 12, 13] },
      { name: "Daylen Lile", bats: "L", pos: ["DH", "RF"], g: [13, 12, 12, 13, 11, 12, 1, -1] },
      { name: "Joey Wiemer", bats: "R", pos: ["RF", "CF"], g: [11, 12, 11, 13, 14, 14] },
      { name: "CJ Abrams", bats: "L", pos: ["SS"], g: [14, 13, 11, 16, 13, 13, 1, -1] },
      { name: "Nasim Nunez", bats: "S", pos: ["2B", "SS"], g: [12, 8, 12, 15, 13, 12] },
      { name: "Keibert Ruiz", bats: "S", pos: ["C"], g: [13, 11, 10, 8, 13, 13] },
      { name: "Jacob Young", bats: "R", pos: ["CF"], g: [12, 8, 11, 16, 15, 13] },
    ],
    pits: [
      { name: "Cade Cavalli", throws: "R", role: "SP", g: [15, 12, 12, 14] },
      { name: "Foster Griffin", throws: "L", role: "SP", g: [13, 13, 12, 14, 1, 0] },
      { name: "Zack Littell", throws: "R", role: "SP", g: [13, 14, 12, 15] },
      { name: "Miles Mikolas", throws: "R", role: "SP", g: [12, 14, 13, 15] },
      { name: "Jake Irvin", throws: "R", role: "SP", g: [13, 13, 12, 15] },
      { name: "Jose A. Ferrer", throws: "L", role: "RP", g: [14, 13, 14, 8, 1, 0] },
      { name: "Kyle Finnegan", throws: "R", role: "RP", g: [14, 13, 12, 8] },
      { name: "Brad Lord", throws: "R", role: "RP", g: [13, 13, 12, 8] },
    ],
  },
  {
    id: "phillies-2026",
    pfx: "phi26",
    city: "Philadelphia",
    nickname: "Phillies",
    abbrev: "PHI",
    blurb:
      "2026 Phillies — Turner, Schwarber, Harper still the middle; Sánchez on Opening Day with Wheeler rehabbing. LockedGM five-man pack.",
    lineup: [
      "Trea Turner",
      "Kyle Schwarber",
      "Bryce Harper",
      "Alec Bohm",
      "Bryson Stott",
      "Adolis Garcia",
      "Brandon Marsh",
      "J.T. Realmuto",
      "Justin Crawford",
    ],
    defense: {
      C: "J.T. Realmuto",
      "1B": "Bryce Harper",
      "2B": "Bryson Stott",
      "3B": "Alec Bohm",
      SS: "Trea Turner",
      LF: "Brandon Marsh",
      CF: "Justin Crawford",
      RF: "Adolis Garcia",
    },
    rotation: [
      "Cristopher Sanchez",
      "Jesus Luzardo",
      "Aaron Nola",
      "Taijuan Walker",
      "Andrew Painter",
    ],
    bullpen: ["Orion Kerkering", "Jordan Romano", "Matt Strahm"],
    bats: [
      { name: "Trea Turner", bats: "R", pos: ["SS"], g: [16, 14, 12, 17, 14, 14] },
      { name: "Kyle Schwarber", bats: "L", pos: ["DH"], g: [13, 18, 16, 8, 8, 11, 1, -1] },
      { name: "Bryce Harper", bats: "L", pos: ["1B"], g: [15, 16, 16, 10, 12, 13, 1, -1] },
      { name: "Alec Bohm", bats: "R", pos: ["3B"], g: [14, 13, 11, 9, 12, 13] },
      { name: "Bryson Stott", bats: "L", pos: ["2B"], g: [14, 11, 13, 14, 14, 13, 1, -1] },
      { name: "Adolis Garcia", bats: "R", pos: ["RF"], g: [12, 15, 10, 13, 13, 15] },
      { name: "Brandon Marsh", bats: "L", pos: ["LF", "CF"], g: [13, 12, 13, 14, 13, 13, 1, -1] },
      { name: "J.T. Realmuto", bats: "R", pos: ["C"], g: [13, 12, 11, 12, 15, 15] },
      { name: "Justin Crawford", bats: "L", pos: ["CF"], g: [13, 10, 12, 16, 13, 12, 1, -1] },
    ],
    pits: [
      { name: "Cristopher Sanchez", throws: "L", role: "SP", g: [16, 15, 16, 16, 1, 0] },
      { name: "Jesus Luzardo", throws: "L", role: "SP", g: [16, 13, 12, 15, 1, 0] },
      { name: "Aaron Nola", throws: "R", role: "SP", g: [14, 15, 12, 15] },
      { name: "Taijuan Walker", throws: "R", role: "SP", g: [12, 13, 12, 14] },
      { name: "Andrew Painter", throws: "R", role: "SP", g: [15, 13, 11, 14] },
      { name: "Orion Kerkering", throws: "R", role: "RP", g: [16, 13, 13, 8] },
      { name: "Jordan Romano", throws: "R", role: "RP", g: [15, 13, 11, 8] },
      { name: "Matt Strahm", throws: "L", role: "RP", g: [14, 14, 11, 7, 1, 0] },
    ],
  },
  {
    id: "brewers-2026",
    pfx: "mil26",
    city: "Milwaukee",
    nickname: "Brewers",
    abbrev: "MIL",
    blurb:
      "2026 Brewers — Chourio and Pratt in the grass after the June call-up; Misiorowski leads a young five-man. LockedGM pack.",
    lineup: [
      "Brice Turang",
      "Jackson Chourio",
      "William Contreras",
      "Christian Yelich",
      "Andrew Vaughn",
      "Cooper Pratt",
      "Sal Frelick",
      "Garrett Mitchell",
      "Jake Bauers",
    ],
    defense: {
      C: "William Contreras",
      "1B": "Andrew Vaughn",
      "2B": "Brice Turang",
      "3B": "Joey Ortiz",
      SS: "Cooper Pratt",
      LF: "Jake Bauers",
      CF: "Jackson Chourio",
      RF: "Sal Frelick",
    },
    rotation: [
      "Jacob Misiorowski",
      "Chad Patrick",
      "Brandon Sproat",
      "Kyle Harrison",
      "Brandon Woodruff",
    ],
    bullpen: ["Trevor Megill", "Abner Uribe", "Jared Koenig"],
    bats: [
      { name: "Brice Turang", bats: "L", pos: ["2B"], g: [14, 10, 13, 16, 15, 13, 1, -1] },
      { name: "Jackson Chourio", bats: "R", pos: ["CF", "RF"], g: [14, 15, 12, 16, 14, 14] },
      { name: "William Contreras", bats: "R", pos: ["C"], g: [15, 14, 14, 9, 13, 14] },
      { name: "Christian Yelich", bats: "L", pos: ["DH", "LF"], g: [14, 14, 15, 13, 11, 13, 1, -1] },
      { name: "Andrew Vaughn", bats: "R", pos: ["1B"], g: [13, 14, 11, 7, 11, 11] },
      { name: "Cooper Pratt", bats: "R", pos: ["SS"], g: [13, 11, 13, 14, 13, 13] },
      { name: "Jake Bauers", bats: "L", pos: ["LF", "1B"], g: [11, 13, 13, 11, 11, 12, 1, -1] },
      { name: "Sal Frelick", bats: "L", pos: ["RF", "CF"], g: [14, 9, 13, 15, 15, 14, 1, -1] },
      { name: "David Hamilton", bats: "L", pos: ["3B", "SS", "2B"], g: [12, 10, 11, 16, 13, 12, 1, -1] },
      { name: "Garrett Mitchell", bats: "L", pos: ["CF"], g: [12, 12, 12, 16, 14, 13, 1, -1] },
      { name: "Joey Ortiz", bats: "R", pos: ["SS", "3B"], g: [12, 10, 12, 12, 14, 13] },
    ],
    pits: [
      { name: "Jacob Misiorowski", throws: "R", role: "SP", g: [17, 12, 11, 14] },
      { name: "Chad Patrick", throws: "R", role: "SP", g: [13, 13, 12, 14] },
      { name: "Brandon Sproat", throws: "R", role: "SP", g: [14, 13, 12, 14] },
      { name: "Kyle Harrison", throws: "L", role: "SP", g: [14, 12, 11, 14, 1, 0] },
      { name: "Brandon Woodruff", throws: "R", role: "SP", g: [16, 15, 12, 13] },
      { name: "Trevor Megill", throws: "R", role: "RP", g: [16, 13, 11, 8] },
      { name: "Abner Uribe", throws: "R", role: "RP", g: [15, 12, 13, 8] },
      { name: "Jared Koenig", throws: "L", role: "RP", g: [13, 13, 13, 7, 1, 0] },
    ],
  },
  {
    id: "cardinals-2026",
    pfx: "stl26",
    city: "St. Louis",
    nickname: "Cardinals",
    abbrev: "STL",
    blurb:
      "2026 Cardinals — Wetherholt leading off in his debut after the Donovan trade. LockedGM five-man pack.",
    lineup: [
      "JJ Wetherholt",
      "Ivan Herrera",
      "Alec Burleson",
      "Masyn Winn",
      "Nolan Gorman",
      "Jordan Walker",
      "Nathan Church",
      "Pedro Pages",
      "Victor Scott II",
    ],
    defense: {
      C: "Pedro Pages",
      "1B": "Alec Burleson",
      "2B": "JJ Wetherholt",
      "3B": "Nolan Gorman",
      SS: "Masyn Winn",
      LF: "Nathan Church",
      CF: "Victor Scott II",
      RF: "Jordan Walker",
    },
    rotation: [
      "Matthew Liberatore",
      "Michael McGreevy",
      "Dustin May",
      "Kyle Leahy",
      "Andre Pallante",
    ],
    bullpen: ["JoJo Romero", "Riley O'Brien", "Ryan Fernandez"],
    bats: [
      { name: "JJ Wetherholt", bats: "L", pos: ["2B", "SS"], g: [14, 13, 14, 13, 13, 12, 1, -1] },
      { name: "Ivan Herrera", bats: "R", pos: ["DH", "C"], g: [14, 13, 13, 9, 11, 12] },
      { name: "Alec Burleson", bats: "L", pos: ["1B", "LF"], g: [14, 13, 11, 8, 11, 11, 1, -1] },
      { name: "Masyn Winn", bats: "R", pos: ["SS"], g: [13, 11, 12, 14, 14, 15] },
      { name: "Nolan Gorman", bats: "L", pos: ["3B", "2B"], g: [11, 15, 13, 9, 11, 12, 1, -1] },
      { name: "Jordan Walker", bats: "R", pos: ["RF"], g: [12, 14, 10, 12, 11, 14] },
      { name: "Nathan Church", bats: "L", pos: ["LF", "CF"], g: [12, 11, 12, 13, 12, 12, 1, -1] },
      { name: "Pedro Pages", bats: "R", pos: ["C"], g: [11, 11, 10, 8, 13, 13] },
      { name: "Victor Scott II", bats: "L", pos: ["CF"], g: [12, 9, 11, 17, 14, 12, 1, -1] },
    ],
    pits: [
      { name: "Matthew Liberatore", throws: "L", role: "SP", g: [14, 13, 13, 15, 1, 0] },
      { name: "Michael McGreevy", throws: "R", role: "SP", g: [13, 14, 13, 14] },
      { name: "Dustin May", throws: "R", role: "SP", g: [14, 12, 14, 13] },
      { name: "Kyle Leahy", throws: "R", role: "SP", g: [13, 13, 12, 13] },
      { name: "Andre Pallante", throws: "R", role: "SP", g: [13, 13, 16, 14] },
      { name: "JoJo Romero", throws: "L", role: "RP", g: [14, 13, 13, 8, 1, 0] },
      { name: "Riley O'Brien", throws: "R", role: "RP", g: [14, 12, 12, 7] },
      { name: "Ryan Fernandez", throws: "R", role: "RP", g: [13, 13, 12, 7] },
    ],
  },
  {
    id: "cubs-2026",
    pfx: "chc26",
    city: "Chicago",
    nickname: "Cubs",
    abbrev: "CHC",
    blurb:
      "2026 Cubs — Bregman in the infield, Boyd on Opening Day, PCA in center. LockedGM five-man pack.",
    lineup: [
      "Michael Busch",
      "Alex Bregman",
      "Ian Happ",
      "Pete Crow-Armstrong",
      "Nico Hoerner",
      "Carson Kelly",
      "Moises Ballesteros",
      "Dansby Swanson",
      "Matt Shaw",
    ],
    defense: {
      C: "Carson Kelly",
      "1B": "Michael Busch",
      "2B": "Nico Hoerner",
      "3B": "Alex Bregman",
      SS: "Dansby Swanson",
      LF: "Ian Happ",
      CF: "Pete Crow-Armstrong",
      RF: "Matt Shaw",
    },
    rotation: [
      "Matthew Boyd",
      "Cade Horton",
      "Edward Cabrera",
      "Shota Imanaga",
      "Jameson Taillon",
    ],
    bullpen: ["Porter Hodge", "Ryan Pressly", "Brad Keller"],
    bats: [
      { name: "Michael Busch", bats: "L", pos: ["1B"], g: [13, 15, 14, 8, 12, 11, 1, -1] },
      { name: "Alex Bregman", bats: "R", pos: ["3B"], g: [14, 14, 16, 9, 15, 14] },
      { name: "Ian Happ", bats: "S", pos: ["LF"], g: [13, 14, 15, 11, 13, 13] },
      { name: "Pete Crow-Armstrong", bats: "L", pos: ["CF"], g: [13, 13, 10, 17, 17, 14, 1, -1] },
      { name: "Nico Hoerner", bats: "R", pos: ["2B"], g: [15, 9, 13, 14, 15, 13] },
      { name: "Carson Kelly", bats: "R", pos: ["C"], g: [12, 12, 13, 7, 13, 13] },
      { name: "Moises Ballesteros", bats: "L", pos: ["DH", "C"], g: [13, 13, 12, 8, 10, 12, 1, -1] },
      { name: "Dansby Swanson", bats: "R", pos: ["SS"], g: [13, 13, 12, 13, 15, 15] },
      { name: "Matt Shaw", bats: "R", pos: ["RF", "3B", "2B"], g: [12, 12, 12, 12, 12, 12] },
    ],
    pits: [
      { name: "Matthew Boyd", throws: "L", role: "SP", g: [15, 15, 12, 15, 1, 0] },
      { name: "Cade Horton", throws: "R", role: "SP", g: [15, 13, 12, 14] },
      { name: "Edward Cabrera", throws: "R", role: "SP", g: [15, 11, 12, 14] },
      { name: "Shota Imanaga", throws: "L", role: "SP", g: [15, 15, 10, 15, 1, 0] },
      { name: "Jameson Taillon", throws: "R", role: "SP", g: [13, 14, 12, 15] },
      { name: "Porter Hodge", throws: "R", role: "RP", g: [15, 13, 12, 8] },
      { name: "Ryan Pressly", throws: "R", role: "RP", g: [14, 14, 13, 7] },
      { name: "Brad Keller", throws: "R", role: "RP", g: [13, 13, 13, 8] },
    ],
  },
  {
    id: "pirates-2026",
    pfx: "pit26",
    city: "Pittsburgh",
    nickname: "Pirates",
    abbrev: "PIT",
    blurb:
      "2026 Pirates — Griffin at short after the April debut; Skenes still the ace. LockedGM five-man pack.",
    lineup: [
      "Oneil Cruz",
      "Konnor Griffin",
      "Brandon Lowe",
      "Bryan Reynolds",
      "Marcell Ozuna",
      "Ryan O'Hearn",
      "Spencer Horwitz",
      "Nick Gonzales",
      "Henry Davis",
    ],
    defense: {
      C: "Henry Davis",
      "1B": "Spencer Horwitz",
      "2B": "Brandon Lowe",
      "3B": "Nick Gonzales",
      SS: "Konnor Griffin",
      LF: "Bryan Reynolds",
      CF: "Oneil Cruz",
      RF: "Ryan O'Hearn",
    },
    rotation: [
      "Paul Skenes",
      "Mitch Keller",
      "Bubba Chandler",
      "Braxton Ashcraft",
      "Jose Urquidy",
    ],
    bullpen: ["David Bednar", "Dennis Santana", "Colin Holderman"],
    bats: [
      { name: "Oneil Cruz", bats: "L", pos: ["CF", "SS"], g: [13, 16, 12, 16, 12, 16, 1, -1] },
      { name: "Konnor Griffin", bats: "R", pos: ["SS"], g: [14, 14, 13, 16, 14, 15] },
      { name: "Brandon Lowe", bats: "L", pos: ["2B"], g: [13, 16, 13, 10, 12, 12, 2, -2] },
      { name: "Bryan Reynolds", bats: "S", pos: ["LF", "RF"], g: [14, 14, 13, 11, 12, 13] },
      { name: "Marcell Ozuna", bats: "R", pos: ["DH"], g: [13, 16, 14, 7, 8, 12] },
      { name: "Ryan O'Hearn", bats: "L", pos: ["RF", "1B"], g: [14, 13, 13, 8, 11, 12, 1, -1] },
      { name: "Jared Triolo", bats: "R", pos: ["SS", "3B", "1B"], g: [12, 10, 12, 12, 13, 13] },
      { name: "Spencer Horwitz", bats: "L", pos: ["1B", "2B"], g: [13, 12, 14, 8, 11, 11, 1, -1] },
      { name: "Nick Gonzales", bats: "R", pos: ["3B", "2B"], g: [13, 12, 11, 11, 12, 12] },
      { name: "Henry Davis", bats: "R", pos: ["C"], g: [11, 12, 11, 9, 12, 14] },
    ],
    pits: [
      { name: "Paul Skenes", throws: "R", role: "SP", g: [19, 16, 12, 16] },
      { name: "Mitch Keller", throws: "R", role: "SP", g: [14, 14, 13, 16] },
      { name: "Bubba Chandler", throws: "R", role: "SP", g: [16, 13, 11, 14] },
      { name: "Braxton Ashcraft", throws: "R", role: "SP", g: [14, 13, 13, 14] },
      { name: "Jose Urquidy", throws: "R", role: "SP", g: [13, 14, 11, 13] },
      { name: "David Bednar", throws: "R", role: "RP", g: [16, 14, 11, 8] },
      { name: "Dennis Santana", throws: "R", role: "RP", g: [14, 13, 13, 8] },
      { name: "Colin Holderman", throws: "R", role: "RP", g: [13, 13, 13, 7] },
    ],
  },
  {
    id: "reds-2026",
    pfx: "cin26",
    city: "Cincinnati",
    nickname: "Reds",
    abbrev: "CIN",
    blurb:
      "2026 Reds — Elly in the hole, Suárez behind him; Abbott leads while Greene opens on the IL. LockedGM five-man pack.",
    lineup: [
      "TJ Friedl",
      "Matt McLain",
      "Elly De La Cruz",
      "Sal Stewart",
      "Eugenio Suarez",
      "Spencer Steer",
      "Tyler Stephenson",
      "Noelvi Marte",
      "Ke'Bryan Hayes",
    ],
    defense: {
      C: "Tyler Stephenson",
      "1B": "Sal Stewart",
      "2B": "Matt McLain",
      "3B": "Ke'Bryan Hayes",
      SS: "Elly De La Cruz",
      LF: "Spencer Steer",
      CF: "TJ Friedl",
      RF: "Noelvi Marte",
    },
    rotation: [
      "Andrew Abbott",
      "Nick Lodolo",
      "Brady Singer",
      "Rhett Lowder",
      "Chase Burns",
    ],
    bullpen: ["Emilio Pagan", "Tony Santillan", "Graham Ashcraft"],
    bats: [
      { name: "TJ Friedl", bats: "L", pos: ["CF"], g: [13, 12, 14, 15, 14, 12, 1, -1] },
      { name: "Matt McLain", bats: "R", pos: ["2B", "SS"], g: [13, 13, 13, 14, 13, 13] },
      { name: "Elly De La Cruz", bats: "S", pos: ["SS"], g: [14, 16, 12, 19, 13, 16] },
      { name: "Sal Stewart", bats: "R", pos: ["1B", "3B"], g: [13, 14, 13, 9, 11, 12] },
      { name: "Eugenio Suarez", bats: "R", pos: ["DH", "3B"], g: [12, 17, 12, 8, 11, 13] },
      { name: "Spencer Steer", bats: "R", pos: ["LF", "1B"], g: [13, 13, 13, 10, 12, 12] },
      { name: "Tyler Stephenson", bats: "R", pos: ["C"], g: [13, 13, 13, 7, 12, 13] },
      { name: "Noelvi Marte", bats: "R", pos: ["RF", "3B"], g: [13, 13, 11, 13, 12, 13] },
      { name: "Ke'Bryan Hayes", bats: "R", pos: ["3B"], g: [13, 10, 11, 12, 17, 15] },
    ],
    pits: [
      { name: "Andrew Abbott", throws: "L", role: "SP", g: [14, 14, 11, 15, 1, 0] },
      { name: "Nick Lodolo", throws: "L", role: "SP", g: [15, 13, 12, 14, 1, 0] },
      { name: "Brady Singer", throws: "R", role: "SP", g: [14, 14, 14, 15] },
      { name: "Rhett Lowder", throws: "R", role: "SP", g: [14, 14, 13, 14] },
      { name: "Chase Burns", throws: "R", role: "SP", g: [16, 12, 11, 13] },
      { name: "Emilio Pagan", throws: "R", role: "RP", g: [15, 14, 10, 8] },
      { name: "Tony Santillan", throws: "R", role: "RP", g: [14, 13, 12, 8] },
      { name: "Graham Ashcraft", throws: "R", role: "RP", g: [13, 12, 14, 8] },
    ],
  },
  {
    id: "diamondbacks-2026",
    pfx: "az26",
    city: "Arizona",
    nickname: "Diamondbacks",
    abbrev: "AZ",
    blurb:
      "2026 D-backs — Marte, Carroll, Perdomo set the tone; Gallen is back on Opening Day. LockedGM five-man pack.",
    lineup: [
      "Ketel Marte",
      "Corbin Carroll",
      "Geraldo Perdomo",
      "Gabriel Moreno",
      "Pavin Smith",
      "Nolan Arenado",
      "Carlos Santana",
      "Alek Thomas",
      "Jordan Lawlar",
    ],
    defense: {
      C: "Gabriel Moreno",
      "1B": "Carlos Santana",
      "2B": "Ketel Marte",
      "3B": "Nolan Arenado",
      SS: "Geraldo Perdomo",
      LF: "Jordan Lawlar",
      CF: "Alek Thomas",
      RF: "Corbin Carroll",
    },
    rotation: [
      "Zac Gallen",
      "Ryne Nelson",
      "Eduardo Rodriguez",
      "Michael Soroka",
      "Brandon Pfaadt",
    ],
    bullpen: ["Justin Martinez", "Shelby Miller", "Kevin Ginkel"],
    bats: [
      { name: "Ketel Marte", bats: "S", pos: ["2B"], g: [15, 15, 14, 12, 13, 13] },
      { name: "Corbin Carroll", bats: "L", pos: ["RF", "CF"], g: [14, 15, 14, 17, 14, 14, 1, -1] },
      { name: "Geraldo Perdomo", bats: "S", pos: ["SS"], g: [14, 10, 15, 14, 15, 14] },
      { name: "Gabriel Moreno", bats: "R", pos: ["C"], g: [14, 11, 12, 10, 15, 14] },
      { name: "Pavin Smith", bats: "L", pos: ["DH", "1B", "RF"], g: [12, 14, 14, 9, 11, 12, 1, -1] },
      { name: "Nolan Arenado", bats: "R", pos: ["3B"], g: [13, 13, 12, 8, 16, 16] },
      { name: "Carlos Santana", bats: "S", pos: ["1B"], g: [12, 13, 14, 7, 13, 12] },
      { name: "Alek Thomas", bats: "L", pos: ["CF"], g: [12, 11, 10, 14, 14, 13, 1, -1] },
      { name: "Jordan Lawlar", bats: "R", pos: ["LF", "SS", "3B"], g: [12, 12, 12, 14, 13, 13] },
    ],
    pits: [
      { name: "Zac Gallen", throws: "R", role: "SP", g: [16, 15, 12, 16] },
      { name: "Ryne Nelson", throws: "R", role: "SP", g: [14, 14, 12, 15] },
      { name: "Eduardo Rodriguez", throws: "L", role: "SP", g: [14, 13, 12, 15, 1, 0] },
      { name: "Michael Soroka", throws: "R", role: "SP", g: [14, 13, 13, 14] },
      { name: "Brandon Pfaadt", throws: "R", role: "SP", g: [14, 14, 12, 15] },
      { name: "Justin Martinez", throws: "R", role: "RP", g: [17, 11, 14, 8] },
      { name: "Shelby Miller", throws: "R", role: "RP", g: [14, 13, 11, 7] },
      { name: "Kevin Ginkel", throws: "R", role: "RP", g: [13, 13, 12, 7] },
    ],
  },
  {
    id: "giants-2026",
    pfx: "sf26",
    city: "San Francisco",
    nickname: "Giants",
    abbrev: "SF",
    blurb:
      "2026 Giants — Arraez and Devers arrive; Webb still the ace. LockedGM five-man pack.",
    lineup: [
      "Luis Arraez",
      "Matt Chapman",
      "Rafael Devers",
      "Willy Adames",
      "Jung Hoo Lee",
      "Heliot Ramos",
      "Casey Schmitt",
      "Patrick Bailey",
      "Harrison Bader",
    ],
    defense: {
      C: "Patrick Bailey",
      "1B": "Casey Schmitt",
      "2B": "Luis Arraez",
      "3B": "Matt Chapman",
      SS: "Willy Adames",
      LF: "Heliot Ramos",
      CF: "Harrison Bader",
      RF: "Jung Hoo Lee",
    },
    rotation: [
      "Logan Webb",
      "Robbie Ray",
      "Tyler Mahle",
      "Adrian Houser",
      "Landen Roupp",
    ],
    bullpen: ["Camilo Doval", "Ryan Walker", "Tyler Rogers"],
    bats: [
      { name: "Luis Arraez", bats: "L", pos: ["2B", "1B"], g: [18, 9, 12, 9, 12, 11, 1, -1] },
      { name: "Matt Chapman", bats: "R", pos: ["3B"], g: [13, 15, 14, 10, 17, 16] },
      { name: "Rafael Devers", bats: "L", pos: ["DH", "3B"], g: [14, 17, 15, 8, 10, 13, 1, -1] },
      { name: "Willy Adames", bats: "R", pos: ["SS"], g: [13, 15, 13, 12, 14, 15] },
      { name: "Jung Hoo Lee", bats: "L", pos: ["RF", "CF"], g: [14, 11, 13, 12, 14, 13, 1, -1] },
      { name: "Heliot Ramos", bats: "R", pos: ["LF"], g: [13, 14, 11, 11, 12, 13] },
      { name: "Casey Schmitt", bats: "R", pos: ["1B", "3B", "2B"], g: [12, 12, 11, 9, 13, 13] },
      { name: "Patrick Bailey", bats: "S", pos: ["C"], g: [12, 10, 11, 8, 16, 15] },
      { name: "Harrison Bader", bats: "R", pos: ["CF"], g: [12, 12, 11, 14, 16, 14] },
    ],
    pits: [
      { name: "Logan Webb", throws: "R", role: "SP", g: [16, 16, 17, 16] },
      { name: "Robbie Ray", throws: "L", role: "SP", g: [16, 13, 10, 15, 1, 0] },
      { name: "Tyler Mahle", throws: "R", role: "SP", g: [14, 14, 11, 14] },
      { name: "Adrian Houser", throws: "R", role: "SP", g: [13, 13, 14, 14] },
      { name: "Landen Roupp", throws: "R", role: "SP", g: [14, 12, 12, 14] },
      { name: "Camilo Doval", throws: "R", role: "RP", g: [16, 12, 14, 8] },
      { name: "Ryan Walker", throws: "R", role: "RP", g: [16, 14, 13, 8] },
      { name: "Tyler Rogers", throws: "R", role: "RP", g: [13, 15, 16, 7] },
    ],
  },
  {
    id: "padres-2026",
    pfx: "sd26",
    city: "San Diego",
    nickname: "Padres",
    abbrev: "SD",
    blurb:
      "2026 Padres — Tatis, Machado, Merrill still the core; Pivetta on Opening Day. LockedGM five-man pack.",
    lineup: [
      "Fernando Tatis Jr.",
      "Xander Bogaerts",
      "Manny Machado",
      "Jackson Merrill",
      "Miguel Andujar",
      "Gavin Sheets",
      "Ramon Laureano",
      "Freddy Fermin",
      "Jake Cronenworth",
    ],
    defense: {
      C: "Freddy Fermin",
      "1B": "Gavin Sheets",
      "2B": "Jake Cronenworth",
      "3B": "Manny Machado",
      SS: "Xander Bogaerts",
      LF: "Ramon Laureano",
      CF: "Jackson Merrill",
      RF: "Fernando Tatis Jr.",
    },
    rotation: [
      "Nick Pivetta",
      "Michael King",
      "Randy Vasquez",
      "German Marquez",
      "Walker Buehler",
    ],
    bullpen: ["Robert Suarez", "Jason Adam", "Jeremiah Estrada"],
    bats: [
      { name: "Fernando Tatis Jr.", bats: "R", pos: ["RF"], g: [15, 16, 14, 16, 15, 16] },
      { name: "Xander Bogaerts", bats: "R", pos: ["SS"], g: [14, 12, 13, 11, 13, 13] },
      { name: "Manny Machado", bats: "R", pos: ["3B"], g: [15, 15, 13, 10, 15, 15] },
      { name: "Jackson Merrill", bats: "L", pos: ["CF"], g: [15, 14, 12, 13, 14, 13, 1, -1] },
      { name: "Miguel Andujar", bats: "R", pos: ["DH", "LF"], g: [14, 12, 10, 9, 11, 12] },
      { name: "Gavin Sheets", bats: "L", pos: ["1B", "RF"], g: [13, 14, 11, 8, 11, 12, 1, -1] },
      { name: "Ramon Laureano", bats: "R", pos: ["LF", "RF", "CF"], g: [12, 13, 12, 13, 14, 14] },
      { name: "Freddy Fermin", bats: "R", pos: ["C"], g: [13, 11, 11, 8, 13, 13] },
      { name: "Jake Cronenworth", bats: "L", pos: ["2B", "1B"], g: [13, 12, 14, 11, 13, 12, 1, -1] },
    ],
    pits: [
      { name: "Nick Pivetta", throws: "R", role: "SP", g: [15, 14, 10, 15] },
      { name: "Michael King", throws: "R", role: "SP", g: [16, 14, 13, 15] },
      { name: "Randy Vasquez", throws: "R", role: "SP", g: [13, 12, 13, 14] },
      { name: "German Marquez", throws: "R", role: "SP", g: [13, 13, 13, 14] },
      { name: "Walker Buehler", throws: "R", role: "SP", g: [13, 13, 12, 13] },
      { name: "Robert Suarez", throws: "R", role: "RP", g: [16, 14, 12, 8] },
      { name: "Jason Adam", throws: "R", role: "RP", g: [15, 14, 12, 8] },
      { name: "Jeremiah Estrada", throws: "R", role: "RP", g: [16, 12, 11, 8] },
    ],
  },
  {
    id: "rockies-2026",
    pfx: "col26",
    city: "Colorado",
    nickname: "Rockies",
    abbrev: "COL",
    blurb:
      "2026 Rockies — Tovar still the glove at short; Freeland on Opening Day. LockedGM five-man pack.",
    lineup: [
      "Jake McCarthy",
      "Hunter Goodman",
      "Willi Castro",
      "Ezequiel Tovar",
      "TJ Rumfield",
      "Jordan Beck",
      "Brenton Doyle",
      "Edouard Julien",
      "Kyle Karros",
    ],
    defense: {
      C: "Hunter Goodman",
      "1B": "TJ Rumfield",
      "2B": "Willi Castro",
      "3B": "Kyle Karros",
      SS: "Ezequiel Tovar",
      LF: "Jake McCarthy",
      CF: "Brenton Doyle",
      RF: "Jordan Beck",
    },
    rotation: [
      "Kyle Freeland",
      "Michael Lorenzen",
      "Jose Quintana",
      "Tomoyuki Sugano",
      "Ryan Feltner",
    ],
    bullpen: ["Victor Vodnik", "Tyler Kinley", "Jake Bird"],
    bats: [
      { name: "Jake McCarthy", bats: "L", pos: ["LF", "RF"], g: [13, 10, 12, 16, 13, 12, 1, -1] },
      { name: "Hunter Goodman", bats: "R", pos: ["C", "DH"], g: [13, 15, 10, 8, 11, 13] },
      { name: "Willi Castro", bats: "S", pos: ["2B", "SS", "LF"], g: [13, 11, 12, 14, 12, 12] },
      { name: "Ezequiel Tovar", bats: "R", pos: ["SS"], g: [13, 13, 9, 13, 16, 15] },
      { name: "TJ Rumfield", bats: "L", pos: ["1B"], g: [13, 13, 13, 8, 11, 11, 1, -1] },
      { name: "Jordan Beck", bats: "R", pos: ["RF", "LF"], g: [12, 13, 11, 12, 12, 13] },
      { name: "Brenton Doyle", bats: "R", pos: ["CF"], g: [12, 13, 10, 15, 16, 15] },
      { name: "Edouard Julien", bats: "L", pos: ["DH", "2B"], g: [12, 13, 15, 10, 10, 11, 1, -1] },
      { name: "Kyle Karros", bats: "R", pos: ["3B"], g: [12, 12, 12, 10, 12, 12] },
    ],
    pits: [
      { name: "Kyle Freeland", throws: "L", role: "SP", g: [13, 14, 13, 15, 1, 0] },
      { name: "Michael Lorenzen", throws: "R", role: "SP", g: [13, 13, 12, 14] },
      { name: "Jose Quintana", throws: "L", role: "SP", g: [13, 14, 13, 14, 1, 0] },
      { name: "Tomoyuki Sugano", throws: "R", role: "SP", g: [14, 14, 12, 14] },
      { name: "Ryan Feltner", throws: "R", role: "SP", g: [13, 13, 12, 14] },
      { name: "Victor Vodnik", throws: "R", role: "RP", g: [14, 13, 13, 8] },
      { name: "Tyler Kinley", throws: "R", role: "RP", g: [14, 12, 11, 7] },
      { name: "Jake Bird", throws: "R", role: "RP", g: [13, 12, 14, 8] },
    ],
  },
];

export const MLB_2026_TEAMS: ClassicTeam[] = SPECS.map((spec) =>
  finalizeClassicTeam(
    buildMlb2026Team(applyCallupPatch(spec, MLB_2026_CALLUPS[spec.id])),
  ),
);

export const MLB_2026_TEAM_IDS = MLB_2026_TEAMS.map((t) => t.id);
