import type { BatterRatings, PitcherRatings } from "../types";
import type { LoosePlayer, LooseTeam } from "../roster-build";

function bat(
  contact: number,
  power: number,
  eye: number,
  speed: number,
  defense: number,
  arm: number,
  platoonVsL = 0,
  platoonVsR = 0,
): BatterRatings {
  return { contact, power, eye, speed, defense, arm, platoonVsL, platoonVsR };
}

function pit(
  stuff: number,
  control: number,
  gb: number,
  stamina: number,
  platoonVsL = 0,
  platoonVsR = 0,
): PitcherRatings {
  return { stuff, control, gb, stamina, platoonVsL, platoonVsR };
}

const players: LoosePlayer[] = [
  {
    id: "cin75-rose",
    name: "Pete Rose",
    bats: "S",
    throws: "R",
    positions: ["3B", "LF"],
    batter: bat(18, 10, 13, 12, 13, 12, 0, 0),
  },
  {
    id: "cin75-morgan",
    name: "Joe Morgan",
    bats: "L",
    throws: "R",
    positions: ["2B"],
    batter: bat(16, 13, 18, 17, 15, 13, 2, -1),
  },
  {
    id: "cin75-bench",
    name: "Johnny Bench",
    bats: "R",
    throws: "R",
    positions: ["C"],
    batter: bat(14, 16, 13, 8, 18, 18, 0, 1),
  },
  {
    id: "cin75-perez",
    name: "Tony Pérez",
    bats: "R",
    throws: "R",
    positions: ["1B"],
    batter: bat(14, 15, 12, 7, 12, 11, 0, 0),
  },
  {
    id: "cin75-foster",
    name: "George Foster",
    bats: "R",
    throws: "R",
    positions: ["LF"],
    batter: bat(14, 17, 11, 10, 12, 13, 0, 1),
  },
  {
    id: "cin75-concepcion",
    name: "Dave Concepción",
    bats: "R",
    throws: "R",
    positions: ["SS"],
    batter: bat(13, 9, 10, 13, 16, 15, 0, 0),
  },
  {
    id: "cin75-griffey",
    name: "Ken Griffey",
    bats: "L",
    throws: "L",
    positions: ["RF"],
    batter: bat(15, 11, 11, 15, 13, 14, 2, -1),
  },
  {
    id: "cin75-geronimo",
    name: "César Gerónimo",
    bats: "L",
    throws: "L",
    positions: ["CF"],
    batter: bat(12, 8, 10, 14, 17, 16, 1, -1),
  },
  {
    id: "cin75-chaney",
    name: "Darrel Chaney",
    bats: "S",
    throws: "R",
    positions: ["SS", "2B"],
    batter: bat(10, 6, 9, 10, 12, 12, 0, 0),
  },
  {
    id: "cin75-gullett",
    name: "Don Gullett",
    bats: "R",
    throws: "L",
    positions: ["P"],
    batter: bat(6, 3, 4, 6, 8, 8),
    pitcher: { ...pit(16, 13, 12, 16, 1, 0), role: "SP" },
  },
  {
    id: "cin75-nolan",
    name: "Gary Nolan",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(14, 15, 11, 15, 0, 0), role: "SP" },
  },
  {
    id: "cin75-billingham",
    name: "Jack Billingham",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(13, 13, 13, 15, 0, 0), role: "SP" },
  },
  {
    id: "cin75-norman",
    name: "Fred Norman",
    bats: "S",
    throws: "L",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(13, 12, 12, 14, 1, 0), role: "SP" },
  },
  {
    id: "cin75-eastwick",
    name: "Rawly Eastwick",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(15, 13, 11, 9, 0, 0), role: "RP" },
  },
  {
    id: "cin75-mcenery",
    name: "Will McEnaney",
    bats: "L",
    throws: "L",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(13, 14, 12, 8, 1, 0), role: "RP" },
  },
  {
    id: "cin75-carroll",
    name: "Clay Carroll",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(12, 13, 14, 9, 0, 0), role: "RP" },
  },
];

/** 1975 Cincinnati Reds — Big Red Machine classic pack. */
export const REDS_1975_LOOSE: LooseTeam = {
  id: "reds-1975",
  year: 1975,
  city: "Cincinnati",
  nickname: "Reds",
  abbrev: "CIN '75",
  blurb:
    "Big Red Machine classic pack — Rose, Morgan, Bench, and company for matchup labs.",
  salaryCap: 92,
  lineup: [
    "cin75-rose",
    "cin75-morgan",
    "cin75-bench",
    "cin75-perez",
    "cin75-foster",
    "cin75-concepcion",
    "cin75-griffey",
    "cin75-geronimo",
    "cin75-chaney",
  ],
  defense: {
    C: "cin75-bench",
    "1B": "cin75-perez",
    "2B": "cin75-morgan",
    "3B": "cin75-rose",
    SS: "cin75-concepcion",
    LF: "cin75-foster",
    CF: "cin75-geronimo",
    RF: "cin75-griffey",
  },
  rotation: [
    "cin75-gullett",
    "cin75-nolan",
    "cin75-billingham",
    "cin75-norman",
  ],
  bullpen: ["cin75-eastwick", "cin75-mcenery", "cin75-carroll"],
  players,
};
