import type { LoosePlayer, LooseTeam } from "../roster-build";
import { bat, pit } from "./pack-helpers";

const players: LoosePlayer[] = [
  {
    id: "kc85-brett",
    name: "George Brett",
    bats: "L",
    throws: "R",
    positions: ["3B", "1B"],
    batter: bat(18, 15, 14, 11, 14, 13, 2, -1),
  },
  {
    id: "kc85-wilson",
    name: "Willie Wilson",
    bats: "S",
    throws: "R",
    positions: ["CF", "LF"],
    batter: bat(15, 8, 10, 19, 15, 14, 0, 0),
  },
  {
    id: "kc85-white",
    name: "Frank White",
    bats: "R",
    throws: "R",
    positions: ["2B"],
    batter: bat(13, 11, 9, 12, 17, 14, 0, 1),
  },
  {
    id: "kc85-balboni",
    name: "Steve Balboni",
    bats: "R",
    throws: "R",
    positions: ["1B", "DH"],
    batter: bat(12, 17, 10, 5, 10, 10, 0, 1),
  },
  {
    id: "kc85-mcrae",
    name: "Hal McRae",
    bats: "R",
    throws: "R",
    positions: ["DH"],
    batter: bat(14, 12, 12, 8, 8, 9, 0, 0),
  },
  {
    id: "kc85-lsmith",
    name: "Lonnie Smith",
    bats: "R",
    throws: "R",
    positions: ["LF"],
    batter: bat(14, 10, 12, 17, 11, 12, 0, 0),
  },
  {
    id: "kc85-sundberg",
    name: "Jim Sundberg",
    bats: "R",
    throws: "R",
    positions: ["C"],
    batter: bat(12, 8, 11, 6, 16, 15, 0, 0),
  },
  {
    id: "kc85-sheridan",
    name: "Pat Sheridan",
    bats: "L",
    throws: "R",
    positions: ["RF", "CF"],
    batter: bat(12, 11, 10, 12, 12, 12, 1, -1),
  },
  {
    id: "kc85-motley",
    name: "Darryl Motley",
    bats: "R",
    throws: "R",
    positions: ["RF", "LF"],
    batter: bat(12, 12, 9, 11, 11, 12, 0, 0),
  },
  {
    id: "kc85-biancalana",
    name: "Buddy Biancalana",
    bats: "S",
    throws: "R",
    positions: ["SS"],
    batter: bat(11, 7, 9, 12, 13, 13, 0, 0),
  },
  {
    id: "kc85-saberhagen",
    name: "Bret Saberhagen",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(18, 16, 12, 17, 0, 1), role: "SP" },
  },
  {
    id: "kc85-leibrandt",
    name: "Charlie Leibrandt",
    bats: "R",
    throws: "L",
    positions: ["P"],
    batter: bat(5, 2, 4, 5, 8, 8),
    pitcher: { ...pit(14, 15, 13, 16, 1, 0), role: "SP" },
  },
  {
    id: "kc85-jackson",
    name: "Danny Jackson",
    bats: "R",
    throws: "L",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(15, 12, 14, 15, 1, 0), role: "SP" },
  },
  {
    id: "kc85-black",
    name: "Bud Black",
    bats: "L",
    throws: "L",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(13, 14, 12, 15, 1, 0), role: "SP" },
  },
  {
    id: "kc85-quisenberry",
    name: "Dan Quisenberry",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(14, 17, 16, 10, 0, 0), role: "RP" },
  },
  {
    id: "kc85-farr",
    name: "Steve Farr",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(13, 12, 12, 9, 0, 0), role: "RP" },
  },
  {
    id: "kc85-gubicza",
    name: "Mark Gubicza",
    bats: "R",
    throws: "R",
    positions: ["P"],
    batter: bat(4, 2, 3, 5, 8, 8),
    pitcher: { ...pit(14, 11, 13, 14, 0, 0), role: "SP" },
  },
];

/** 1985 Kansas City Royals — AL West champs / WS winners (LockedGM grades). */
export const ROYALS_1985_LOOSE: LooseTeam = {
  id: "royals-1985",
  year: 1985,
  city: "Kansas City",
  nickname: "Royals",
  abbrev: "KC '85",
  blurb:
    "Brett, Saberhagen, and Quisenberry — LockedGM pack for the 1985 AL West champions.",
  salaryCap: 92,
  lineup: [
    "kc85-lsmith",
    "kc85-wilson",
    "kc85-brett",
    "kc85-mcrae",
    "kc85-balboni",
    "kc85-white",
    "kc85-sheridan",
    "kc85-sundberg",
    "kc85-biancalana",
  ],
  defense: {
    C: "kc85-sundberg",
    "1B": "kc85-balboni",
    "2B": "kc85-white",
    "3B": "kc85-brett",
    SS: "kc85-biancalana",
    LF: "kc85-lsmith",
    CF: "kc85-wilson",
    RF: "kc85-sheridan",
  },
  rotation: [
    "kc85-saberhagen",
    "kc85-leibrandt",
    "kc85-jackson",
    "kc85-black",
  ],
  bullpen: ["kc85-quisenberry", "kc85-farr", "kc85-gubicza"],
  players,
};
