/**
 * Curated YouTube video IDs for in-panel LockedGM highlight embeds.
 * Keys must match college-football-top300 seed names exactly.
 */
export const COLLEGE_FOOTBALL_CLIP_IDS: Record<string, string> = {
  "Jeremiah Smith": "9aNiWy-wEl4",
  "Leonard Moore": "ItklW9DSAjE",
  "Charlie Becker": "BcyX1wBwjpA",
  "Colin Simmons": "jWrBqLAlnM0",
  "Dylan Stewart": "jrvKigamMIg",
  "Dante Moore": "bRPBe-K-LMU",
  "Arch Manning": "w-vOF50lfNo",
  "Cam Coleman": "KsJx4qexGn8",
  "Jordan Seaton": "ffYuH2IQE7A",
  "Trevor Goosby": "_22c-VgmmDo",
  "Carter Smith": "aJU6pj7B2Io",
  "Jadan Baugh": "RRbDBFXNFuk",
  "Kewan Lacy": "zVu7Mu1O7TY",
  "David Stone": "YHBeNlVfZ0c",
  "Ellis Robinson IV": "6_pJonC858I",
  "Kelley Jones": "2f-wV3U--Xs",
  "Brice Pollock": "jkP3QI2qph4",
  "Jamari Johnson": "dvd9U-RnQ3I",
  "KJ Bolden": "xRosAiBTFiw",
  "Will Echoles": "1jeHU65WP3Y",
  "Omarion Miller": "cOcWK9cmVCE",
  "Ahmad Moten Sr.": "HMRWsH3eV-g",
  "Mario Craver": "Wi2uv8G9hXY",
  "Zabien Brown": "rI7-4woTSbg",
  "Vicari Swain": "mMeU18ftso8",
  "Austin Siereveld": "iG6XATMuOAk",
  "Greg Johnson": "Cdz0si2ryIk",
  "Zach Lutmer": "DRJnHTOAzsc",
  "OJ Frederique Jr.": "E1aZ_U8t1w0",
  "A'Mauri Washington": "C6vL9TnbyDk",
  "Ashton Hampton": "4maK8RMmJwM",
  "Quincy Rhodes Jr.": "dmUwAmjuLDo",
  "Kenyatta Jackson Jr.": "NGb5g1cs8XQ",
  "Koi Perich": "aqcg2BMSNow",
  "Jelani McDonald": "9XZRul7dU1Q",
  "Melvin Siani": "IF0JCz4btCA",
  "Kade Pieper": "jjEat-TQnXw",
  "Bray Hubbard": "cIyccFFA_m0",
  "Tavion Gadson": "xdr_KUpKWfU",
  "Jaylen McClain": "51tSsCdhaUY",
  "Amare Thomas": "7EAbFX5gefc",
  "Yhonzae Pierre": "xS8k5axhso8",
  "Kyngstonn Viliamu-Asa": "tU4uu9Ea_ow",
  "Mateen Ibirogba": "fPTaEpAf13o",
  "Clev Lubin": "h2nARY2Nx4w",
  "CJ Carr": "Ta721pR7bfA",
  "Matayo Uiagalelei": "6axDSzIsUZw",
  "Nick Marsh": "PAYKDtGhaoE",
  "Wyatt Young": "_9ExbMmuAE8",
  "LJ Martin": "LyIGFUDxFKM",
  "Xavier Scott": "7KLW9GFeI10",
  "Trevor Lauck": "T2ZwZYpsHIs",
  "Iapani Laloulu": "irwAkL1-YBY",
  "Anto Saka": "EFhwVIMOj1c",
  "Bear Alexander": "z3gWT1KiJag",
  "AJ Holmes Jr.": "5EqhniE0t84",
  "Whit Weeks": "YBhtRZz3e3M",
  "Sammy Brown": "fVIIpNufZNg",
  "Trinidad Chambliss": "FonctfTwdXA",
  "Braelin Moore": "XtwlnyXdt2o",
  "Isaac Brown": "a_-asEifW64",
  "Kayin Lee": "jzr8d7DXlrQ",
  "Antwan Raymond": "qgyjSsRkDkg",
  "John Henry Daley": "sh_ycND6GJk",
  "Eric Singleton Jr.": "werDFptKNqw",
  "Ryan Coleman-Williams": "iSoRk820xZk",
  "Chris Cole": "QZ3wwnUr1Vo",
  "Trey'Dez Green": "lB_2dMs-Zy8",
  "T.J. Moore": "F3-XN5h_ag4",
  "Ahmad Hardy": "dVKp_hokIB8",
  "Anthony Smith": "4TbMlXhHXaQ",
  "Tre Richardson": "dLuVgt9ZOo4",
  "PJ Williams": "px5GosxoECM",
  "Jacarrius Peak": "hgRhj4DkoaU",
  "Lance Heard": "2Swp3YxBssk",
  "Raleek Brown": "_CwFIW7DvdY",
  "Bryant Wesco Jr.": "dPx1LuTJF-k",
  "Niki Prongos": "HQVVE4ISXxc",
  "Teitum Tuioti": "yxFGLEMihjE",
  "Cayden Green": "8YJiJtHpoUo",
  "Rasheem Biles": "pWuTddj-fKs",
  "Jayden Maiava": "fEYI4HBY4dU",
  "Peyton Bowen": "Pl5dawLYeWU",
  "Justice Haynes": "dBTU0tlDfbM",
  "DJ Hicks": "V6818Lt5cqQ",
  "KJ Duff": "N5lowYTCUuE",
  "Ben Roberts": "82RH4_Feu3c",
  "Christian Alliegro": "hlKGmHyb6BM",
  "Hollywood Smothers": "dWxqMODQwXM",
  "Darian Mensah": "-QK2Qv4uyD8",
  "Amare Ferrell": "ubBNyzQgIoo",
  "Taylor Wein": "d9RnnbFyI00",
  "Desmeal Leigh": "kh-gLJjydGc",
  "Brendan Sorsby": "deck-FUx7Jg",
  "Cooper Barkate": "UKq2lBTOoU4",
  "Devan Thompkins": "HtGhQ9zeM6I",
  "Xavier Chaplin": "3VCdBgW-XWI",
  "Suntarine Perkins": "KOvRJdBqlRc",
  "Jermaine Mathews Jr.": "qC7wtNuLihE",
  "Elijah Paige": "DxiuyYfPcuA",
  "Earl Little Jr.": "riLTLhxHbgs",
  "DJ McKinney": "Pwaf8QScJsI",
  "Josh Hoover": "wO7CB_pAaC4",
  "Joe Cotton": "A5vB9MNknuU",
  "Jontez Williams": "ikZwv5CILWc",
  "Ryan Wingo": "z2wTvd3xR9I",
  "J'Mond Tapp": "mhotpQAIzYs",
  "Anthony Donkoh": "dD70A3edtkk",
  "Alani Noa": "H5KvHoNsWHk",
  "Issa Ouattara": "ZffCGTTiZgE",
  "Cade Uluave": "ycXG6Fmqphk",
  "James Smith": "KG_MNMSMJ24",
  "Tony Rojas": "hMcTOlKBpIk",
  "Bryce Thornton": "QD3YQ8TxD4k",
  "Owen Heinecke": "iVCvSbx8cBY",
  "Evan Johnson": "vh84TMbo0jY",
  "Jalen Mayo": "5iNMKZqED5Q",
  "Julian Sayin": "1s3GlRNaqgY",
  "Princewill Umanmielen": "TV0oDG3NsII",
  "Davaughn Patterson": "QPLM4Plvst8",
  "Xavier Atkins": "ZdxuFHgkFrw",
  "Terry Moore": "eT1XZVoSVCE",
  "Keon Sabb": "448S8HTBiXk",
  "LaNorris Sellers": "nX_yvNocpGc",
  "Kameryn Crawford": "xIspiDRZbrU",
  "Damon Wilson II": "Cv0I4r7kvyc",
  "Drew Azzopardi": "kmyp8hJ0Woc",
  "McKale Boley": "_uFTtHPqtRg",
  "Devin McCuin": "bqspSxLTUGA",
  "Shadre Hurst": "eMYFIWonIsA",
  "Cam Cook": "zWj48HlaPt0",
  "Myles Graham": "QZt8wY-t3V8",
  "Isaiah Sategna III": "hJSy9AeKJgQ",
  "Ty Benefield": "vTbZx3RvAos",
  "Boubacar Traore": "FQzRBUBw2mE",
  "Will Heldt": "ppk5NGK6Gdg",
  "Carson Hinzman": "Vo9oKu3HH3E",
  "Benjamin Brahmer": "10jgm9A5lxo",
  "Arion Carter": "gO08UPFmPrA",
  "Luke Reynolds": "8my-aLiEuRc",
  "Waymond Jordan": "nZZiMbGFf04",
  "Kemari Copeland": "liIlONgDhas",
  "Christian Gray": "Aqz9nscvWMM",
  "Tyree Adams": "9Scp2gmBx5E",
  "Griffin Wilde": "w6gyRSxHjIY",
  "Jayden Virgin-Morgan": "nLVdi19B9MA",
  "Keanu Tanuvasa": "Zb1OU43zx9A",
  "Jeremiah Hasley": "4eQHMyFgD-o",
  "Reed Harris": "LI1GRpGAaj8",
  "Austin Romaine": "qCNz-l8foyE",
  "Tobi Osunsanmi": "txmY6Um008A",
  "Mark Fletcher Jr.": "1h_BaH2ApNQ",
  "Trell Harris": "osQtMLjrzu8",
  "Kip Lewis": "Si4KsbE_Ca8",
  "Deuce Alexander": "vbqd2qcLpx0",
  "Howard Sampson": "j2wP8jwuyUU",
  "Jaden Greathouse": "eqhNQI-n-ew",
  "Jyaire Hill": "E9PkK66GO24",
  "Ikenna Ezeogu": "Eb7nBIVlmbI",
  "Isaac Smith": "SS0jW0UbHc8",
  "Joenel Aguero": "74irYFN7SQ8",
  "Raylen Wilson": "q6nq7lLsaIQ",
  "Horace Lockett": "oSFSOYOyQh0",
  "Luke Montgomery": "rbCPhM3EN3s",
  "Melkart Abou-Jaoude": "C_i8kaLT-WY",
  "Ryan Baer": "6egKWHYzzEc",
  "Faletau Satuala": "C0uziLimnAA",
  "Smith Snowden": "TdsRSRA5Bk4",
  "Sam Leavitt": "Uxkop6LuN_Y",
  "John Mateer": "tZLmSlcgcOk",
  "Chris Peal": "fh7HbbVjHi4",
  "Terrance Carter Jr.": "w_e0xt8eHQI",
  "AJ Harris": "2tj2srXBjFI",
  "Brett Norfleet": "QZsPa0jm3iA",
  "Coleton Price": "qp3ILqoOUU8",
  "Nate Frazier": "PqTtMalhaKo",
  "Dezz Ricks": "aYHtE-r3s5w",
  "Alex McLaughlin": "BKrDTJRHTXY",
  "Wayshawn Parker": "-WAYcua6g4M",
  "Duce Robinson": "7FJI2oLgD4w",
  "Ja'Bril Rawls": "klWCUR47BrY",
  "Hero Kanu": "GgZcqOrUx58",
  "Ty Bryant": "Ii9zmW9jDws",
  "Jackson Bennee": "T-5emsL65zY",
  "Earnest Greene III": "sl3sZOySY-I",
  "Stephiylan Green": "dYJeYsx4_lY",
  "Drew Bobo": "HxSx21PVRgE",
  "Nico Iamaleava": "9KcjoMgenRk",
  "Katin Houser": "5qnOzisVioE",
  "Miles Capers": "inEBV1tJY9U",
  "Trey White": "zAlqxLz5CsE",
  "Isaiah Glasker": "tRQH5A8RNQ4",
  "CJ Fite": "KKma78aLbBw",
  "Da'Shawn Womack": "HpOcdvSsqp0",
  "Isaiah Horton": "St9OHyPOomc",
  "Jordan Marshall": "ELqf41DEqdc",
  "Qua Russaw": "XGR5jO4wt6w",
  "Byrum Brown": "MdwHhmoSJcA",
  "Lawson Luckie": "pZ2yqOEdduk",
  "Wendell Moe Jr.": "8DFxndl87Zg",
  "Kam Robinson": "-u9hD8tVOWY",
  "Zeke Berry": "CKIt7yj8i4E",
  "CJ Mims": "uteqS_lFMt8",
  "Daniel Wingate": "ikZwv5CILWc",
  "Trey Pierce": "isZF9DMM028",
  "Jake Renfro": "66pbJH-zOYc",
  "Jaden Craig": "INLKJXhFGek",
  "Darius Taylor": "PSGdBF3EHS0",
  "Noah Fifita": "gUk3COsBpb8",
  "Mi'Quise Humphrey-Grace": "UwycRoq0zCI",
  "Boo Carter": "lBSPvCazBIM",
  "Daymion Sanford": "JS-W4G3eL94",
  "DeAndre Moore Jr.": "odl2WDJSTGU",
  "Keaton Thomas": "W5GWgArsOc0",
  "Khalil Barnes": "R8kq6LaxR6Y",
  "Carson Hansen": "q-wgCdak4u4",
  "Eli Finley": "cts1zobmx78",
  "Evan Link": "yuhAoB7YF3c",
  "Steve Angeli": "ZjDG5LcrwrQ",
  "Patrick Kutas": "16Jgi3_8Nvc",
  "Jahiem Lawson": "T7FEpT6LTPE",
  "Theo Melin Ohrstrom": "VPH9R7jFSGw",
  "Rueben Owens II": "2PGxyjVWitc",
  "Gunner Stockton": "Ubuimjm01CU",
  "Audavion Collins": "4wBLMWAB3bk",
  "Rahtrel Perry": "d4PQI6AtlZ0",
  "Mohamed Toure": "yiYL9trWDQA",
  "Rocco Becht": "ektx9drOyEM",
  "Kevin Jennings": "MSXVZXP5fOg",
  "Brandon Inniss": "Tbo9G5Yb3mE",
  "Rod Moore": "Fq-2g0kYceE",
  "Marcel Reed": "vL7LbUlHSPc",
  "Keahnist Thompson": "O3aSChErNJ0",
  "Anthony Evans III": "Ec6EO9hEvZ4",
  "Ashton Beers": "gDhwAO2ntNc",
  "Austin Kawecki": "EW6VPnhguVg",
  "Avery Johnson": "iI1fxyC9Tao",
  "Ben Taylor Whitfield": "pFOC_rkOb4U",
  "Braden Awls": "Xli_ZRDkGbQ",
  "Brauntae Johnson": "1SwUAbBj9mg",
  "Braylan Lovelace": "CyMa45vr5L8",
  "Braylan Shelby": "a_x3HPUzkhg",
  "Caleb Woodson": "vvagUrHV6mg",
  "Cameron Brandt": "aZAWK_cZchQ",
  "Chase Hendricks": "KBMaWbnBUas",
  "Chris Rodgers": "NUpsnR-6yTw",
  "CJ Heard": "gB9LjfLRo_Q",
  "Collin Sadler": "17aWMQu-nco",
  "Connor Robertson": "kZZpv9jbZys",
  "Dalton Brooks": "Gs8mpCqTeGc",
  "Daniel Lyons": "8_mK3jIP7vQ",
  "David Oke": "HsdSglI5J6s",
  "Demond Williams Jr.": "MEvQcO0PBYs",
  "Deshaun Lee": "CscLRl2g3Q0",
  "Drew Evans": "1zxY6IutV7k",
  "E.J. Lightsey": "OgvcnYfQxp8",
  "Elinneus Davis": "O4pK4-EwVSk",
  "Enow Etta": "TuXTelEACuM",
  "Evan Crenshaw": "PNzpw3t4zws",
  "Evan Stewart": "DnWyIbB3ZSU",
  "Gentry Williams": "RNGnPnAHDL4",
  "Hudson Clement": "NfrKiCeOE3Q",
  "Isaac Terrell": "TfyIgQHcEBY",
  "Isaiah Jones": "_wqgGTF5p9c",
  "Jack Dotzler": "VMuJiPZfWsI",
  "Jamal Roberts": "HvEvmfkYM5Q",
  "Jeremiah Cobb": "fZp39bCV6zY",
  "Jeremiah Cooper": "7kCTiXX2N4I",
  "Jide Abasiri": "8IJbWgaYbHs",
  "John Pastore": "iFCWL85dtHk",
  "Jordan Faison": "Pr9wK5FcaDE",
  "Joseph Borjon": "dgOphblm0hM",
  "Josiah Freeman": "JCGpDENtCf8",
  "Kamran James": "3fJxxU4N6yU",
  "KP Price": "xEb0C7cqdJI",
  "Landen Hatchett": "5URKLoTwlA8",
  "Makilan Thomas": "oB4lL8R6g-8",
  "Marcus Ratcliffe": "BTj3ox45Y9g",
  "Matt Bailey": "BgONSNgPLrw",
  "Matt Rose": "WmOqVgm88Zw",
  "Max Tucker": "INtbQbIpiXY",
  "Nic Anderson": "lp_KKOXGEWg",
  "Nick Morris Jr..": "hGX3K8g_DuY",
  "Nick Rinaldi": "nB4o9Znhciw",
  "Noah Rogers": "KetKf36SIjw",
  "Nyck Harbor": "UY5t8hO6Yjs",
  "Peyton Woodring": "5C7wiR3brGU",
  "Russell Davis II": "-2ae7Z4Qp0w",
  "Sedrick Alexander": "jTrLIJ8_PFM",
  "Siale Taupaki": "Mf6_eHeWHms",
  "T.J. Searcy": "No4pwuAF0-Q",
  "Tate Sandell": "cgwGcgAc280",
  "Teague Anderson": "EZKh1KGm8ZA",
  "TJ Dottery": "MgdEHGW3rU0",
  "Tre Smith": "YNjlqFOefGw",
  "Tre'Quon Fegans": "hDhX6wOgB8o",
  "Ty Pennington": "UUzV1LDHkfw",
  "Will James": "n6dCQnDlw5w",
  "Willie Rodriguez": "hgkpLh-pQeQ",
  "Xe'Ree Alexander": "OkzGTa2BqN8",
};
