import type { Prospect } from "./sport-catalog";

/**
 * LockGM High School Basketball — Top 100 scouting board (Class of 2027).
 *
 * Public prospect names from the national HS recruiting landscape;
 * grades, teaser/premium notes, and traits are LockGM originals for
 * Shadow-GM scouting — not copied ranking prose.
 */
export const HS_BASKETBALL_CLASS_YEAR = 2027;

export const HS_BASKETBALL_TOP_100: Prospect[] = [
  {
    id: "hsb001",
    name: 'Beckham Black',
    position: "PG",
    school: 'Southeastern Prep (FL)',
    stage: "high_school",
    rank: 1,
    height: '6\'3"',
    weight: 180,
    metric: null,
    grade: 98,
    capHitM: 0,
    reportTeaser: 'Floor general with advanced pace control.',
    reportPremium: 'Reads help early and pressures the paint. Strength vs pro physicality is the development ask. LockGM track: multi-year HS board.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #1. Multi-year track for college → declare pipeline.',
    traits: ['shot creation', 'pace', 'IQ'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Beckham%20Black%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Beckham%20Black%20Southeastern%20Prep%20(FL)%20highlights',
  },
  {
    id: "hsb002",
    name: 'Marcus Spears Jr.',
    position: "PF",
    school: 'Dynamic Prep (TX)',
    stage: "high_school",
    rank: 2,
    height: '6\'10"',
    weight: 220,
    metric: null,
    grade: 98,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #2. Multi-year track for college → declare pipeline.',
    traits: ['length', 'rim pressure', 'motor'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Marcus%20Spears%20Jr.%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Marcus%20Spears%20Jr.%20Dynamic%20Prep%20(TX)%20highlights',
  },
  {
    id: "hsb003",
    name: 'CJ Rosser',
    position: "PF",
    school: 'Southeastern Prep (FL)',
    stage: "high_school",
    rank: 3,
    height: '6\'10"',
    weight: 200,
    metric: null,
    grade: 98,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #3. Multi-year track for college → declare pipeline.',
    traits: ['handle', 'vision', 'pull-up'],
    highlightUrl: 'https://www.youtube.com/results?search_query=CJ%20Rosser%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=CJ%20Rosser%20Southeastern%20Prep%20(FL)%20highlights',
  },
  {
    id: "hsb004",
    name: 'Adan Diggs',
    position: "SF",
    school: 'Montverde Academy (FL)',
    stage: "high_school",
    rank: 4,
    height: '6\'7"',
    weight: 190,
    metric: null,
    grade: 98,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #4. Multi-year track for college → declare pipeline.',
    traits: ['switch', 'closeout', 'upside'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Adan%20Diggs%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Adan%20Diggs%20Montverde%20Academy%20(FL)%20highlights',
  },
  {
    id: "hsb005",
    name: 'Demarcus Henry',
    position: "SF",
    school: 'Link Academy (MO)',
    stage: "high_school",
    rank: 5,
    height: '6\'7"',
    weight: 220,
    metric: null,
    grade: 97,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #5. Multi-year track for college → declare pipeline.',
    traits: ['spacing', 'vertical', 'timing'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Demarcus%20Henry%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Demarcus%20Henry%20Link%20Academy%20(MO)%20highlights',
  },
  {
    id: "hsb006",
    name: 'Nasir Anderson',
    position: "CG",
    school: 'AZ Compass Prep (AZ)',
    stage: "high_school",
    rank: 6,
    height: '6\'4"',
    weight: 180,
    metric: null,
    grade: 97,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #6. Multi-year track for college → declare pipeline.',
    traits: ['burst', 'compete', 'YACs'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Nasir%20Anderson%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Nasir%20Anderson%20AZ%20Compass%20Prep%20(AZ)%20highlights',
  },
  {
    id: "hsb007",
    name: 'Lewis Uvwo',
    position: "C",
    school: 'Wasatch Academy (UT)',
    stage: "high_school",
    rank: 7,
    height: '6\'11"',
    weight: 225,
    metric: null,
    grade: 97,
    capHitM: 0,
    reportTeaser: 'Rim protector / interior presence with upside.',
    reportPremium: 'Timing as a helper and vertical spacer tools. Switch drops and strength program are next.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #7. Multi-year track for college → declare pipeline.',
    traits: ['PnR', 'pass', 'poise'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Lewis%20Uvwo%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Lewis%20Uvwo%20Wasatch%20Academy%20(UT)%20highlights',
  },
  {
    id: "hsb008",
    name: 'Paul Osaruyi',
    position: "PG",
    school: 'Overtime Elite (GA)',
    stage: "high_school",
    rank: 8,
    height: '6\'3"',
    weight: 215,
    metric: null,
    grade: 97,
    capHitM: 0,
    reportTeaser: 'Floor general with advanced pace control.',
    reportPremium: 'Reads help early and pressures the paint. Strength vs pro physicality is the development ask. LockGM track: multi-year HS board.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #8. Multi-year track for college → declare pipeline.',
    traits: ['frame', 'anchor', 'touch'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Paul%20Osaruyi%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Paul%20Osaruyi%20Overtime%20Elite%20(GA)%20highlights',
  },
  {
    id: "hsb009",
    name: 'Cayden Daughtry',
    position: "PG",
    school: 'Calvary Christian (KY)',
    stage: "high_school",
    rank: 9,
    height: '6\'2"',
    weight: 175,
    metric: null,
    grade: 96,
    capHitM: 0,
    reportTeaser: 'Floor general with advanced pace control.',
    reportPremium: 'Reads help early and pressures the paint. Strength vs pro physicality is the development ask. LockGM track: multi-year HS board.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #9. Multi-year track for college → declare pipeline.',
    traits: ['shot creation', 'pace', 'IQ'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Cayden%20Daughtry%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Cayden%20Daughtry%20Calvary%20Christian%20(KY)%20highlights',
  },
  {
    id: "hsb010",
    name: 'Reese Alston',
    position: "SF",
    school: 'Sunrise Christian (KS)',
    stage: "high_school",
    rank: 10,
    height: '6\'5"',
    weight: 210,
    metric: null,
    grade: 96,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #10. Multi-year track for college → declare pipeline.',
    traits: ['length', 'rim pressure', 'motor'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Reese%20Alston%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Reese%20Alston%20Sunrise%20Christian%20(KS)%20highlights',
  },
  {
    id: "hsb011",
    name: 'Darius Wabbington',
    position: "CG",
    school: 'Centennial (NV)',
    stage: "high_school",
    rank: 11,
    height: '6\'3"',
    weight: 185,
    metric: null,
    grade: 96,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #11. Multi-year track for college → declare pipeline.',
    traits: ['handle', 'vision', 'pull-up'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Darius%20Wabbington%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Darius%20Wabbington%20Centennial%20(NV)%20highlights',
  },
  {
    id: "hsb012",
    name: 'Javon Bardwell',
    position: "C",
    school: 'Oak Hill Academy (VA)',
    stage: "high_school",
    rank: 12,
    height: '6\'11"',
    weight: 255,
    metric: null,
    grade: 96,
    capHitM: 0,
    reportTeaser: 'Rim protector / interior presence with upside.',
    reportPremium: 'Timing as a helper and vertical spacer tools. Switch drops and strength program are next.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #12. Multi-year track for college → declare pipeline.',
    traits: ['switch', 'closeout', 'upside'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Javon%20Bardwell%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Javon%20Bardwell%20Oak%20Hill%20Academy%20(VA)%20highlights',
  },
  {
    id: "hsb013",
    name: 'Jalen Davis',
    position: "CG",
    school: 'IMG Academy (FL)',
    stage: "high_school",
    rank: 13,
    height: '6\'3"',
    weight: 165,
    metric: null,
    grade: 95,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #13. Multi-year track for college → declare pipeline.',
    traits: ['spacing', 'vertical', 'timing'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jalen%20Davis%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jalen%20Davis%20IMG%20Academy%20(FL)%20highlights',
  },
  {
    id: "hsb014",
    name: 'Malachi Jordan',
    position: "SF",
    school: 'Prolific Prep (FL)',
    stage: "high_school",
    rank: 14,
    height: '6\'7"',
    weight: 215,
    metric: null,
    grade: 95,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #14. Multi-year track for college → declare pipeline.',
    traits: ['burst', 'compete', 'YACs'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Malachi%20Jordan%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Malachi%20Jordan%20Prolific%20Prep%20(FL)%20highlights',
  },
  {
    id: "hsb015",
    name: 'Moussa Kamissoko',
    position: "PF",
    school: 'Long Island Lutheran (NY)',
    stage: "high_school",
    rank: 15,
    height: '6\'9"',
    weight: 215,
    metric: null,
    grade: 95,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #15. Multi-year track for college → declare pipeline.',
    traits: ['PnR', 'pass', 'poise'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Moussa%20Kamissoko%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Moussa%20Kamissoko%20Long%20Island%20Lutheran%20(NY)%20highlights',
  },
  {
    id: "hsb016",
    name: 'Gabe Nesmith',
    position: "CG",
    school: 'Sierra Canyon (CA)',
    stage: "high_school",
    rank: 16,
    height: '6\'4"',
    weight: 185,
    metric: null,
    grade: 95,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #16. Multi-year track for college → declare pipeline.',
    traits: ['frame', 'anchor', 'touch'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Gabe%20Nesmith%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Gabe%20Nesmith%20Sierra%20Canyon%20(CA)%20highlights',
  },
  {
    id: "hsb017",
    name: 'Davion Thompson',
    position: "PF",
    school: 'Duncanville (TX)',
    stage: "high_school",
    rank: 17,
    height: '6\'6"',
    weight: 239,
    metric: null,
    grade: 94,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #17. Multi-year track for college → declare pipeline.',
    traits: ['shot creation', 'pace', 'IQ'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Davion%20Thompson%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Davion%20Thompson%20Duncanville%20(TX)%20highlights',
  },
  {
    id: "hsb018",
    name: 'NaVorro Bowman Jr.',
    position: "C",
    school: 'DeMatha Catholic (MD)',
    stage: "high_school",
    rank: 18,
    height: '6\'10"',
    weight: 225,
    metric: null,
    grade: 94,
    capHitM: 0,
    reportTeaser: 'Rim protector / interior presence with upside.',
    reportPremium: 'Timing as a helper and vertical spacer tools. Switch drops and strength program are next.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #18. Multi-year track for college → declare pipeline.',
    traits: ['length', 'rim pressure', 'motor'],
    highlightUrl: 'https://www.youtube.com/results?search_query=NaVorro%20Bowman%20Jr.%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=NaVorro%20Bowman%20Jr.%20DeMatha%20Catholic%20(MD)%20highlights',
  },
  {
    id: "hsb019",
    name: 'Chase Branham',
    position: "SF",
    school: 'Link Academy (MO)',
    stage: "high_school",
    rank: 19,
    height: '6\'7"',
    weight: 180,
    metric: null,
    grade: 94,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #19. Multi-year track for college → declare pipeline.',
    traits: ['handle', 'vision', 'pull-up'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Chase%20Branham%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Chase%20Branham%20Link%20Academy%20(MO)%20highlights',
  },
  {
    id: "hsb020",
    name: 'Ahmad Hudson',
    position: "PG",
    school: 'Combine Academy (NC)',
    stage: "high_school",
    rank: 20,
    height: '6\'1"',
    weight: 165,
    metric: null,
    grade: 94,
    capHitM: 0,
    reportTeaser: 'Floor general with advanced pace control.',
    reportPremium: 'Reads help early and pressures the paint. Strength vs pro physicality is the development ask. LockGM track: multi-year HS board.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #20. Multi-year track for college → declare pipeline.',
    traits: ['switch', 'closeout', 'upside'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Ahmad%20Hudson%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Ahmad%20Hudson%20Combine%20Academy%20(NC)%20highlights',
  },
  {
    id: "hsb021",
    name: 'Jarvis Hayes Jr.',
    position: "SF",
    school: 'Wheeler (GA)',
    stage: "high_school",
    rank: 21,
    height: '6\'6"',
    weight: 190,
    metric: null,
    grade: 93,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #21. Multi-year track for college → declare pipeline.',
    traits: ['spacing', 'vertical', 'timing'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jarvis%20Hayes%20Jr.%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jarvis%20Hayes%20Jr.%20Wheeler%20(GA)%20highlights',
  },
  {
    id: "hsb022",
    name: 'Dawson Battie',
    position: "C",
    school: 'Link Academy (MO)',
    stage: "high_school",
    rank: 22,
    height: '7\'0"',
    weight: 220,
    metric: null,
    grade: 93,
    capHitM: 0,
    reportTeaser: 'Rim protector / interior presence with upside.',
    reportPremium: 'Timing as a helper and vertical spacer tools. Switch drops and strength program are next.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #22. Multi-year track for college → declare pipeline.',
    traits: ['burst', 'compete', 'YACs'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Dawson%20Battie%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Dawson%20Battie%20Link%20Academy%20(MO)%20highlights',
  },
  {
    id: "hsb023",
    name: 'Kager Knueppel',
    position: "SF",
    school: 'Wisconsin Lutheran (WI)',
    stage: "high_school",
    rank: 23,
    height: '6\'7"',
    weight: 225,
    metric: null,
    grade: 93,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #23. Multi-year track for college → declare pipeline.',
    traits: ['PnR', 'pass', 'poise'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Kager%20Knueppel%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Kager%20Knueppel%20Wisconsin%20Lutheran%20(WI)%20highlights',
  },
  {
    id: "hsb024",
    name: 'Dooney Johnson',
    position: "CG",
    school: 'Oak Hill Academy (VA)',
    stage: "high_school",
    rank: 24,
    height: '6\'4"',
    weight: 185,
    metric: null,
    grade: 93,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #24. Multi-year track for college → declare pipeline.',
    traits: ['frame', 'anchor', 'touch'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Dooney%20Johnson%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Dooney%20Johnson%20Oak%20Hill%20Academy%20(VA)%20highlights',
  },
  {
    id: "hsb025",
    name: 'Scottie Adkinson',
    position: "PF",
    school: 'Brewster Academy (NH)',
    stage: "high_school",
    rank: 25,
    height: '6\'8"',
    weight: 230,
    metric: null,
    grade: 92,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #25. Multi-year track for college → declare pipeline.',
    traits: ['shot creation', 'pace', 'IQ'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Scottie%20Adkinson%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Scottie%20Adkinson%20Brewster%20Academy%20(NH)%20highlights',
  },
  {
    id: "hsb026",
    name: 'Chase Lumpkin',
    position: "CG",
    school: 'Perry (AZ)',
    stage: "high_school",
    rank: 26,
    height: '6\'3"',
    weight: 190,
    metric: null,
    grade: 92,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #26. Multi-year track for college → declare pipeline.',
    traits: ['length', 'rim pressure', 'motor'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Chase%20Lumpkin%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Chase%20Lumpkin%20Perry%20(AZ)%20highlights',
  },
  {
    id: "hsb027",
    name: 'Devin Cleveland',
    position: "CG",
    school: 'Montverde Academy (FL)',
    stage: "high_school",
    rank: 27,
    height: '6\'5"',
    weight: 185,
    metric: null,
    grade: 92,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #27. Multi-year track for college → declare pipeline.',
    traits: ['handle', 'vision', 'pull-up'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Devin%20Cleveland%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Devin%20Cleveland%20Montverde%20Academy%20(FL)%20highlights',
  },
  {
    id: "hsb028",
    name: 'Zion Green',
    position: "PF",
    school: 'Wasatch Academy (UT)',
    stage: "high_school",
    rank: 28,
    height: '6\'6"',
    weight: 205,
    metric: null,
    grade: 92,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #28. Multi-year track for college → declare pipeline.',
    traits: ['switch', 'closeout', 'upside'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Zion%20Green%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Zion%20Green%20Wasatch%20Academy%20(UT)%20highlights',
  },
  {
    id: "hsb029",
    name: 'Antonio Pemberton',
    position: "CG",
    school: 'Cathedral (IN)',
    stage: "high_school",
    rank: 29,
    height: '6\'2"',
    weight: 190,
    metric: null,
    grade: 91,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #29. Multi-year track for college → declare pipeline.',
    traits: ['spacing', 'vertical', 'timing'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Antonio%20Pemberton%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Antonio%20Pemberton%20Cathedral%20(IN)%20highlights',
  },
  {
    id: "hsb030",
    name: 'Micah Gordon',
    position: "CG",
    school: 'St. John Bosco (CA)',
    stage: "high_school",
    rank: 30,
    height: '6\'3"',
    weight: 165,
    metric: null,
    grade: 91,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #30. Multi-year track for college → declare pipeline.',
    traits: ['burst', 'compete', 'YACs'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Micah%20Gordon%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Micah%20Gordon%20St.%20John%20Bosco%20(CA)%20highlights',
  },
  {
    id: "hsb031",
    name: 'Jaxson Davis',
    position: "PG",
    school: 'Sunrise Christian (KS)',
    stage: "high_school",
    rank: 31,
    height: '6\'1"',
    weight: 160,
    metric: null,
    grade: 91,
    capHitM: 0,
    reportTeaser: 'Floor general with advanced pace control.',
    reportPremium: 'Reads help early and pressures the paint. Strength vs pro physicality is the development ask. LockGM track: multi-year HS board.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #31. Multi-year track for college → declare pipeline.',
    traits: ['PnR', 'pass', 'poise'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jaxson%20Davis%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jaxson%20Davis%20Sunrise%20Christian%20(KS)%20highlights',
  },
  {
    id: "hsb032",
    name: 'Darrell Davis',
    position: "PF",
    school: 'AZ Compass Prep (AZ)',
    stage: "high_school",
    rank: 32,
    height: '6\'9"',
    weight: 190,
    metric: null,
    grade: 91,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #32. Multi-year track for college → declare pipeline.',
    traits: ['frame', 'anchor', 'touch'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Darrell%20Davis%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Darrell%20Davis%20AZ%20Compass%20Prep%20(AZ)%20highlights',
  },
  {
    id: "hsb033",
    name: 'Tyran Frazier',
    position: "PG",
    school: 'Overtime Elite (GA)',
    stage: "high_school",
    rank: 33,
    height: '5\'10"',
    weight: 180,
    metric: null,
    grade: 90,
    capHitM: 0,
    reportTeaser: 'Floor general with advanced pace control.',
    reportPremium: 'Reads help early and pressures the paint. Strength vs pro physicality is the development ask. LockGM track: multi-year HS board.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #33. Multi-year track for college → declare pipeline.',
    traits: ['shot creation', 'pace', 'IQ'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Tyran%20Frazier%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Tyran%20Frazier%20Overtime%20Elite%20(GA)%20highlights',
  },
  {
    id: "hsb034",
    name: 'Tyrone Jamison',
    position: "PG",
    school: 'IMG Academy (FL)',
    stage: "high_school",
    rank: 34,
    height: '5\'11"',
    weight: 165,
    metric: null,
    grade: 90,
    capHitM: 0,
    reportTeaser: 'Floor general with advanced pace control.',
    reportPremium: 'Reads help early and pressures the paint. Strength vs pro physicality is the development ask. LockGM track: multi-year HS board.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #34. Multi-year track for college → declare pipeline.',
    traits: ['length', 'rim pressure', 'motor'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Tyrone%20Jamison%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Tyrone%20Jamison%20IMG%20Academy%20(FL)%20highlights',
  },
  {
    id: "hsb035",
    name: 'Josiah Harrington',
    position: "PG",
    school: 'Combine Academy (NC)',
    stage: "high_school",
    rank: 35,
    height: '6\'1"',
    weight: 165,
    metric: null,
    grade: 90,
    capHitM: 0,
    reportTeaser: 'Floor general with advanced pace control.',
    reportPremium: 'Reads help early and pressures the paint. Strength vs pro physicality is the development ask. LockGM track: multi-year HS board.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #35. Multi-year track for college → declare pipeline.',
    traits: ['handle', 'vision', 'pull-up'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Josiah%20Harrington%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Josiah%20Harrington%20Combine%20Academy%20(NC)%20highlights',
  },
  {
    id: "hsb036",
    name: 'King Rachal',
    position: "PF",
    school: 'Link Academy (MO)',
    stage: "high_school",
    rank: 36,
    height: '6\'9"',
    weight: 190,
    metric: null,
    grade: 90,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #36. Multi-year track for college → declare pipeline.',
    traits: ['switch', 'closeout', 'upside'],
    highlightUrl: 'https://www.youtube.com/results?search_query=King%20Rachal%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=King%20Rachal%20Link%20Academy%20(MO)%20highlights',
  },
  {
    id: "hsb037",
    name: 'Asa Montgomery',
    position: "CG",
    school: 'Sierra Canyon (CA)',
    stage: "high_school",
    rank: 37,
    height: '6\'2"',
    weight: 185,
    metric: null,
    grade: 89,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #37. Multi-year track for college → declare pipeline.',
    traits: ['spacing', 'vertical', 'timing'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Asa%20Montgomery%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Asa%20Montgomery%20Sierra%20Canyon%20(CA)%20highlights',
  },
  {
    id: "hsb038",
    name: 'Jaydn Jenkins',
    position: "SG",
    school: 'Montverde Academy (FL)',
    stage: "high_school",
    rank: 38,
    height: '6\'5"',
    weight: 175,
    metric: null,
    grade: 89,
    capHitM: 0,
    reportTeaser: 'Secondary scorer with shot-making gravity.',
    reportPremium: 'Creates advantages off the bounce and relocates. Contested-catch / off-ball defense still climbing.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #38. Multi-year track for college → declare pipeline.',
    traits: ['burst', 'compete', 'YACs'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jaydn%20Jenkins%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jaydn%20Jenkins%20Montverde%20Academy%20(FL)%20highlights',
  },
  {
    id: "hsb039",
    name: 'Donovan Davis',
    position: "PG",
    school: 'Prolific Prep (FL)',
    stage: "high_school",
    rank: 39,
    height: '6\'0"',
    weight: 165,
    metric: null,
    grade: 89,
    capHitM: 0,
    reportTeaser: 'Floor general with advanced pace control.',
    reportPremium: 'Reads help early and pressures the paint. Strength vs pro physicality is the development ask. LockGM track: multi-year HS board.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #39. Multi-year track for college → declare pipeline.',
    traits: ['PnR', 'pass', 'poise'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Donovan%20Davis%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Donovan%20Davis%20Prolific%20Prep%20(FL)%20highlights',
  },
  {
    id: "hsb040",
    name: 'Cherif Millogo',
    position: "SF",
    school: 'Wasatch Academy (UT)',
    stage: "high_school",
    rank: 40,
    height: '6\'6"',
    weight: 210,
    metric: null,
    grade: 89,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #40. Multi-year track for college → declare pipeline.',
    traits: ['frame', 'anchor', 'touch'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Cherif%20Millogo%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Cherif%20Millogo%20Wasatch%20Academy%20(UT)%20highlights',
  },
  {
    id: "hsb041",
    name: 'Kameron Mercer',
    position: "C",
    school: 'Oak Hill Academy (VA)',
    stage: "high_school",
    rank: 41,
    height: '6\'10"',
    weight: 250,
    metric: null,
    grade: 88,
    capHitM: 0,
    reportTeaser: 'Rim protector / interior presence with upside.',
    reportPremium: 'Timing as a helper and vertical spacer tools. Switch drops and strength program are next.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #41. Multi-year track for college → declare pipeline.',
    traits: ['shot creation', 'pace', 'IQ'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Kameron%20Mercer%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Kameron%20Mercer%20Oak%20Hill%20Academy%20(VA)%20highlights',
  },
  {
    id: "hsb042",
    name: 'Payton Jones',
    position: "PG",
    school: 'Brewster Academy (NH)',
    stage: "high_school",
    rank: 42,
    height: '6\'1"',
    weight: 170,
    metric: null,
    grade: 88,
    capHitM: 0,
    reportTeaser: 'Floor general with advanced pace control.',
    reportPremium: 'Reads help early and pressures the paint. Strength vs pro physicality is the development ask. LockGM track: multi-year HS board.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #42. Multi-year track for college → declare pipeline.',
    traits: ['length', 'rim pressure', 'motor'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Payton%20Jones%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Payton%20Jones%20Brewster%20Academy%20(NH)%20highlights',
  },
  {
    id: "hsb043",
    name: "J'Lon Lyons",
    position: "CG",
    school: 'Centennial (NV)',
    stage: "high_school",
    rank: 43,
    height: '6\'2"',
    weight: 165,
    metric: null,
    grade: 88,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #43. Multi-year track for college → declare pipeline.',
    traits: ['handle', 'vision', 'pull-up'],
    highlightUrl: 'https://www.youtube.com/results?search_query=J%27Lon%20Lyons%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=J%27Lon%20Lyons%20Centennial%20%28NV%29%20highlights',
  },
  {
    id: "hsb044",
    name: 'Caleb Ourigou',
    position: "C",
    school: 'Overtime Elite (GA)',
    stage: "high_school",
    rank: 44,
    height: '7\'2"',
    weight: 210,
    metric: null,
    grade: 88,
    capHitM: 0,
    reportTeaser: 'Rim protector / interior presence with upside.',
    reportPremium: 'Timing as a helper and vertical spacer tools. Switch drops and strength program are next.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #44. Multi-year track for college → declare pipeline.',
    traits: ['switch', 'closeout', 'upside'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Caleb%20Ourigou%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Caleb%20Ourigou%20Overtime%20Elite%20(GA)%20highlights',
  },
  {
    id: "hsb045",
    name: 'Kamsi Awaka',
    position: "CG",
    school: 'AZ Compass Prep (AZ)',
    stage: "high_school",
    rank: 45,
    height: '6\'2"',
    weight: 170,
    metric: null,
    grade: 87,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #45. Multi-year track for college → declare pipeline.',
    traits: ['spacing', 'vertical', 'timing'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Kamsi%20Awaka%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Kamsi%20Awaka%20AZ%20Compass%20Prep%20(AZ)%20highlights',
  },
  {
    id: "hsb046",
    name: 'Oneal Delancy',
    position: "SF",
    school: 'Long Island Lutheran (NY)',
    stage: "high_school",
    rank: 46,
    height: '6\'4"',
    weight: 215,
    metric: null,
    grade: 87,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #46. Multi-year track for college → declare pipeline.',
    traits: ['burst', 'compete', 'YACs'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Oneal%20Delancy%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Oneal%20Delancy%20Long%20Island%20Lutheran%20(NY)%20highlights',
  },
  {
    id: "hsb047",
    name: 'Aaron Britt Jr.',
    position: "SF",
    school: 'Wheeler (GA)',
    stage: "high_school",
    rank: 47,
    height: '6\'7"',
    weight: 185,
    metric: null,
    grade: 87,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #47. Multi-year track for college → declare pipeline.',
    traits: ['PnR', 'pass', 'poise'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Aaron%20Britt%20Jr.%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Aaron%20Britt%20Jr.%20Wheeler%20(GA)%20highlights',
  },
  {
    id: "hsb048",
    name: 'Javion Tyndale',
    position: "SF",
    school: 'Duncanville (TX)',
    stage: "high_school",
    rank: 48,
    height: '6\'6"',
    weight: 190,
    metric: null,
    grade: 87,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #48. Multi-year track for college → declare pipeline.',
    traits: ['frame', 'anchor', 'touch'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Javion%20Tyndale%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Javion%20Tyndale%20Duncanville%20(TX)%20highlights',
  },
  {
    id: "hsb049",
    name: 'Ferlandes Wright',
    position: "SG",
    school: 'DeMatha Catholic (MD)',
    stage: "high_school",
    rank: 49,
    height: '6\'5"',
    weight: 185,
    metric: null,
    grade: 86,
    capHitM: 0,
    reportTeaser: 'Secondary scorer with shot-making gravity.',
    reportPremium: 'Creates advantages off the bounce and relocates. Contested-catch / off-ball defense still climbing.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #49. Multi-year track for college → declare pipeline.',
    traits: ['shot creation', 'pace', 'IQ'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Ferlandes%20Wright%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Ferlandes%20Wright%20DeMatha%20Catholic%20(MD)%20highlights',
  },
  {
    id: "hsb050",
    name: 'Patrick Otey',
    position: "PG",
    school: 'Cathedral (IN)',
    stage: "high_school",
    rank: 50,
    height: '6\'2"',
    weight: 174,
    metric: null,
    grade: 86,
    capHitM: 0,
    reportTeaser: 'Floor general with advanced pace control.',
    reportPremium: 'Reads help early and pressures the paint. Strength vs pro physicality is the development ask. LockGM track: multi-year HS board.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #50. Multi-year track for college → declare pipeline.',
    traits: ['length', 'rim pressure', 'motor'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Patrick%20Otey%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Patrick%20Otey%20Cathedral%20(IN)%20highlights',
  },
  {
    id: "hsb051",
    name: 'Gene Roebuck',
    position: "PF",
    school: 'Perry (AZ)',
    stage: "high_school",
    rank: 51,
    height: '6\'7"',
    weight: 200,
    metric: null,
    grade: 86,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #51. Multi-year track for college → declare pipeline.',
    traits: ['handle', 'vision', 'pull-up'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Gene%20Roebuck%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Gene%20Roebuck%20Perry%20(AZ)%20highlights',
  },
  {
    id: "hsb052",
    name: 'Jack Kohnen',
    position: "PG",
    school: 'Wisconsin Lutheran (WI)',
    stage: "high_school",
    rank: 52,
    height: '6\'0"',
    weight: 190,
    metric: null,
    grade: 86,
    capHitM: 0,
    reportTeaser: 'Floor general with advanced pace control.',
    reportPremium: 'Reads help early and pressures the paint. Strength vs pro physicality is the development ask. LockGM track: multi-year HS board.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #52. Multi-year track for college → declare pipeline.',
    traits: ['switch', 'closeout', 'upside'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jack%20Kohnen%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jack%20Kohnen%20Wisconsin%20Lutheran%20(WI)%20highlights',
  },
  {
    id: "hsb053",
    name: 'Jalen White',
    position: "PF",
    school: 'St. John Bosco (CA)',
    stage: "high_school",
    rank: 53,
    height: '6\'7"',
    weight: 215,
    metric: null,
    grade: 85,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #53. Multi-year track for college → declare pipeline.',
    traits: ['spacing', 'vertical', 'timing'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jalen%20White%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jalen%20White%20St.%20John%20Bosco%20(CA)%20highlights',
  },
  {
    id: "hsb054",
    name: 'Jason Gardner Jr.',
    position: "SF",
    school: 'Sunrise Christian (KS)',
    stage: "high_school",
    rank: 54,
    height: '6\'5"',
    weight: 210,
    metric: null,
    grade: 85,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #54. Multi-year track for college → declare pipeline.',
    traits: ['burst', 'compete', 'YACs'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jason%20Gardner%20Jr.%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jason%20Gardner%20Jr.%20Sunrise%20Christian%20(KS)%20highlights',
  },
  {
    id: "hsb055",
    name: 'Carson Crawford',
    position: "PF",
    school: 'Link Academy (MO)',
    stage: "high_school",
    rank: 55,
    height: '6\'8"',
    weight: 200,
    metric: null,
    grade: 85,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #55. Multi-year track for college → declare pipeline.',
    traits: ['PnR', 'pass', 'poise'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Carson%20Crawford%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Carson%20Crawford%20Link%20Academy%20(MO)%20highlights',
  },
  {
    id: "hsb056",
    name: 'Jalen Brown',
    position: "CG",
    school: 'IMG Academy (FL)',
    stage: "high_school",
    rank: 56,
    height: '6\'2"',
    weight: 190,
    metric: null,
    grade: 85,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #56. Multi-year track for college → declare pipeline.',
    traits: ['frame', 'anchor', 'touch'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jalen%20Brown%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jalen%20Brown%20IMG%20Academy%20(FL)%20highlights',
  },
  {
    id: "hsb057",
    name: 'Jahari Miller',
    position: "SF",
    school: 'Montverde Academy (FL)',
    stage: "high_school",
    rank: 57,
    height: '6\'6"',
    weight: 215,
    metric: null,
    grade: 84,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #57. Multi-year track for college → declare pipeline.',
    traits: ['shot creation', 'pace', 'IQ'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jahari%20Miller%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jahari%20Miller%20Montverde%20Academy%20(FL)%20highlights',
  },
  {
    id: "hsb058",
    name: 'Jeremiah Profit',
    position: "PF",
    school: 'Prolific Prep (FL)',
    stage: "high_school",
    rank: 58,
    height: '6\'7"',
    weight: 220,
    metric: null,
    grade: 84,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #58. Multi-year track for college → declare pipeline.',
    traits: ['length', 'rim pressure', 'motor'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jeremiah%20Profit%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jeremiah%20Profit%20Prolific%20Prep%20(FL)%20highlights',
  },
  {
    id: "hsb059",
    name: 'Geren Holmes',
    position: "C",
    school: 'Wasatch Academy (UT)',
    stage: "high_school",
    rank: 59,
    height: '6\'9"',
    weight: 205,
    metric: null,
    grade: 84,
    capHitM: 0,
    reportTeaser: 'Rim protector / interior presence with upside.',
    reportPremium: 'Timing as a helper and vertical spacer tools. Switch drops and strength program are next.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #59. Multi-year track for college → declare pipeline.',
    traits: ['handle', 'vision', 'pull-up'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Geren%20Holmes%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Geren%20Holmes%20Wasatch%20Academy%20(UT)%20highlights',
  },
  {
    id: "hsb060",
    name: 'Jomar Bernard',
    position: "SF",
    school: 'Oak Hill Academy (VA)',
    stage: "high_school",
    rank: 60,
    height: '6\'6"',
    weight: 190,
    metric: null,
    grade: 84,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #60. Multi-year track for college → declare pipeline.',
    traits: ['switch', 'closeout', 'upside'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jomar%20Bernard%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jomar%20Bernard%20Oak%20Hill%20Academy%20(VA)%20highlights',
  },
  {
    id: "hsb061",
    name: 'Markus Kerr',
    position: "SF",
    school: 'Combine Academy (NC)',
    stage: "high_school",
    rank: 61,
    height: '6\'5"',
    weight: 180,
    metric: null,
    grade: 83,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #61. Multi-year track for college → declare pipeline.',
    traits: ['spacing', 'vertical', 'timing'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Markus%20Kerr%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Markus%20Kerr%20Combine%20Academy%20(NC)%20highlights',
  },
  {
    id: "hsb062",
    name: 'Munir Greig',
    position: "SG",
    school: 'Sierra Canyon (CA)',
    stage: "high_school",
    rank: 62,
    height: '6\'3"',
    weight: 180,
    metric: null,
    grade: 83,
    capHitM: 0,
    reportTeaser: 'Secondary scorer with shot-making gravity.',
    reportPremium: 'Creates advantages off the bounce and relocates. Contested-catch / off-ball defense still climbing.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #62. Multi-year track for college → declare pipeline.',
    traits: ['burst', 'compete', 'YACs'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Munir%20Greig%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Munir%20Greig%20Sierra%20Canyon%20(CA)%20highlights',
  },
  {
    id: "hsb063",
    name: 'Brandon Mason Jr.',
    position: "SG",
    school: 'Centennial (NV)',
    stage: "high_school",
    rank: 63,
    height: '6\'4"',
    weight: 175,
    metric: null,
    grade: 83,
    capHitM: 0,
    reportTeaser: 'Secondary scorer with shot-making gravity.',
    reportPremium: 'Creates advantages off the bounce and relocates. Contested-catch / off-ball defense still climbing.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #63. Multi-year track for college → declare pipeline.',
    traits: ['PnR', 'pass', 'poise'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Brandon%20Mason%20Jr.%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Brandon%20Mason%20Jr.%20Centennial%20(NV)%20highlights',
  },
  {
    id: "hsb064",
    name: 'Keaundre Morris',
    position: "C",
    school: 'Brewster Academy (NH)',
    stage: "high_school",
    rank: 64,
    height: '6\'10"',
    weight: 220,
    metric: null,
    grade: 83,
    capHitM: 0,
    reportTeaser: 'Rim protector / interior presence with upside.',
    reportPremium: 'Timing as a helper and vertical spacer tools. Switch drops and strength program are next.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #64. Multi-year track for college → declare pipeline.',
    traits: ['frame', 'anchor', 'touch'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Keaundre%20Morris%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Keaundre%20Morris%20Brewster%20Academy%20(NH)%20highlights',
  },
  {
    id: "hsb065",
    name: 'Baboucarr Ann',
    position: "PF",
    school: 'AZ Compass Prep (AZ)',
    stage: "high_school",
    rank: 65,
    height: '6\'8"',
    weight: 190,
    metric: null,
    grade: 82,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #65. Multi-year track for college → declare pipeline.',
    traits: ['shot creation', 'pace', 'IQ'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Baboucarr%20Ann%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Baboucarr%20Ann%20AZ%20Compass%20Prep%20(AZ)%20highlights',
  },
  {
    id: "hsb066",
    name: 'Godson Okokoh',
    position: "PG",
    school: 'Overtime Elite (GA)',
    stage: "high_school",
    rank: 66,
    height: '5\'8"',
    weight: 155,
    metric: null,
    grade: 82,
    capHitM: 0,
    reportTeaser: 'Floor general with advanced pace control.',
    reportPremium: 'Reads help early and pressures the paint. Strength vs pro physicality is the development ask. LockGM track: multi-year HS board.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #66. Multi-year track for college → declare pipeline.',
    traits: ['length', 'rim pressure', 'motor'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Godson%20Okokoh%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Godson%20Okokoh%20Overtime%20Elite%20(GA)%20highlights',
  },
  {
    id: "hsb067",
    name: 'Lucai Anderson',
    position: "PG",
    school: 'Duncanville (TX)',
    stage: "high_school",
    rank: 67,
    height: '6\'1"',
    weight: 185,
    metric: null,
    grade: 82,
    capHitM: 0,
    reportTeaser: 'Floor general with advanced pace control.',
    reportPremium: 'Reads help early and pressures the paint. Strength vs pro physicality is the development ask. LockGM track: multi-year HS board.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #67. Multi-year track for college → declare pipeline.',
    traits: ['handle', 'vision', 'pull-up'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Lucai%20Anderson%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Lucai%20Anderson%20Duncanville%20(TX)%20highlights',
  },
  {
    id: "hsb068",
    name: 'Lyris Robinson',
    position: "CG",
    school: 'Wheeler (GA)',
    stage: "high_school",
    rank: 68,
    height: '6\'4"',
    weight: 180,
    metric: null,
    grade: 82,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #68. Multi-year track for college → declare pipeline.',
    traits: ['switch', 'closeout', 'upside'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Lyris%20Robinson%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Lyris%20Robinson%20Wheeler%20(GA)%20highlights',
  },
  {
    id: "hsb069",
    name: 'Quincy Douby Jr.',
    position: "SF",
    school: 'Long Island Lutheran (NY)',
    stage: "high_school",
    rank: 69,
    height: '6\'6"',
    weight: 180,
    metric: null,
    grade: 81,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #69. Multi-year track for college → declare pipeline.',
    traits: ['spacing', 'vertical', 'timing'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Quincy%20Douby%20Jr.%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Quincy%20Douby%20Jr.%20Long%20Island%20Lutheran%20(NY)%20highlights',
  },
  {
    id: "hsb070",
    name: 'Marri Wesley',
    position: "SF",
    school: 'DeMatha Catholic (MD)',
    stage: "high_school",
    rank: 70,
    height: '6\'5"',
    weight: 200,
    metric: null,
    grade: 81,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #70. Multi-year track for college → declare pipeline.',
    traits: ['burst', 'compete', 'YACs'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Marri%20Wesley%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Marri%20Wesley%20DeMatha%20Catholic%20(MD)%20highlights',
  },
  {
    id: "hsb071",
    name: 'Ian Condon',
    position: "SF",
    school: 'Cathedral (IN)',
    stage: "high_school",
    rank: 71,
    height: '6\'5"',
    weight: 175,
    metric: null,
    grade: 81,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #71. Multi-year track for college → declare pipeline.',
    traits: ['PnR', 'pass', 'poise'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Ian%20Condon%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Ian%20Condon%20Cathedral%20(IN)%20highlights',
  },
  {
    id: "hsb072",
    name: 'Jimmie Haywood',
    position: "C",
    school: 'Link Academy (MO)',
    stage: "high_school",
    rank: 72,
    height: '6\'11"',
    weight: 195,
    metric: null,
    grade: 81,
    capHitM: 0,
    reportTeaser: 'Rim protector / interior presence with upside.',
    reportPremium: 'Timing as a helper and vertical spacer tools. Switch drops and strength program are next.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #72. Multi-year track for college → declare pipeline.',
    traits: ['frame', 'anchor', 'touch'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jimmie%20Haywood%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jimmie%20Haywood%20Link%20Academy%20(MO)%20highlights',
  },
  {
    id: "hsb073",
    name: 'Jamaal McKnight Jr.',
    position: "PG",
    school: 'Perry (AZ)',
    stage: "high_school",
    rank: 73,
    height: '6\'1"',
    weight: 170,
    metric: null,
    grade: 80,
    capHitM: 0,
    reportTeaser: 'Floor general with advanced pace control.',
    reportPremium: 'Reads help early and pressures the paint. Strength vs pro physicality is the development ask. LockGM track: multi-year HS board.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #73. Multi-year track for college → declare pipeline.',
    traits: ['shot creation', 'pace', 'IQ'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jamaal%20McKnight%20Jr.%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jamaal%20McKnight%20Jr.%20Perry%20(AZ)%20highlights',
  },
  {
    id: "hsb074",
    name: 'Isaiah Mack-Russell',
    position: "SG",
    school: 'St. John Bosco (CA)',
    stage: "high_school",
    rank: 74,
    height: '6\'4"',
    weight: 170,
    metric: null,
    grade: 80,
    capHitM: 0,
    reportTeaser: 'Secondary scorer with shot-making gravity.',
    reportPremium: 'Creates advantages off the bounce and relocates. Contested-catch / off-ball defense still climbing.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #74. Multi-year track for college → declare pipeline.',
    traits: ['length', 'rim pressure', 'motor'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Isaiah%20Mack-Russell%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Isaiah%20Mack-Russell%20St.%20John%20Bosco%20(CA)%20highlights',
  },
  {
    id: "hsb075",
    name: 'Kamari Whyte',
    position: "PF",
    school: 'Wasatch Academy (UT)',
    stage: "high_school",
    rank: 75,
    height: '6\'8"',
    weight: 245,
    metric: null,
    grade: 80,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #75. Multi-year track for college → declare pipeline.',
    traits: ['handle', 'vision', 'pull-up'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Kamari%20Whyte%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Kamari%20Whyte%20Wasatch%20Academy%20(UT)%20highlights',
  },
  {
    id: "hsb076",
    name: 'Quinton Kitt',
    position: "SF",
    school: 'Sunrise Christian (KS)',
    stage: "high_school",
    rank: 76,
    height: '6\'5"',
    weight: 187,
    metric: null,
    grade: 80,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #76. Multi-year track for college → declare pipeline.',
    traits: ['switch', 'closeout', 'upside'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Quinton%20Kitt%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Quinton%20Kitt%20Sunrise%20Christian%20(KS)%20highlights',
  },
  {
    id: "hsb077",
    name: 'Kellen Brewer',
    position: "PF",
    school: 'Montverde Academy (FL)',
    stage: "high_school",
    rank: 77,
    height: '6\'7"',
    weight: 220,
    metric: null,
    grade: 79,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #77. Multi-year track for college → declare pipeline.',
    traits: ['spacing', 'vertical', 'timing'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Kellen%20Brewer%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Kellen%20Brewer%20Montverde%20Academy%20(FL)%20highlights',
  },
  {
    id: "hsb078",
    name: 'Brandon Woodard',
    position: "CG",
    school: 'IMG Academy (FL)',
    stage: "high_school",
    rank: 78,
    height: '6\'5"',
    weight: 200,
    metric: null,
    grade: 79,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #78. Multi-year track for college → declare pipeline.',
    traits: ['burst', 'compete', 'YACs'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Brandon%20Woodard%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Brandon%20Woodard%20IMG%20Academy%20(FL)%20highlights',
  },
  {
    id: "hsb079",
    name: 'Miguel Orbe',
    position: "PF",
    school: 'Prolific Prep (FL)',
    stage: "high_school",
    rank: 79,
    height: '6\'8"',
    weight: 195,
    metric: null,
    grade: 79,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #79. Multi-year track for college → declare pipeline.',
    traits: ['PnR', 'pass', 'poise'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Miguel%20Orbe%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Miguel%20Orbe%20Prolific%20Prep%20(FL)%20highlights',
  },
  {
    id: "hsb080",
    name: 'Corey Dixon',
    position: "SG",
    school: 'Oak Hill Academy (VA)',
    stage: "high_school",
    rank: 80,
    height: '6\'6"',
    weight: 165,
    metric: null,
    grade: 79,
    capHitM: 0,
    reportTeaser: 'Secondary scorer with shot-making gravity.',
    reportPremium: 'Creates advantages off the bounce and relocates. Contested-catch / off-ball defense still climbing.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #80. Multi-year track for college → declare pipeline.',
    traits: ['frame', 'anchor', 'touch'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Corey%20Dixon%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Corey%20Dixon%20Oak%20Hill%20Academy%20(VA)%20highlights',
  },
  {
    id: "hsb081",
    name: 'Marquis Newson',
    position: "SF",
    school: 'Combine Academy (NC)',
    stage: "high_school",
    rank: 81,
    height: '6\'5"',
    weight: 205,
    metric: null,
    grade: 78,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #81. Multi-year track for college → declare pipeline.',
    traits: ['shot creation', 'pace', 'IQ'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Marquis%20Newson%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Marquis%20Newson%20Combine%20Academy%20(NC)%20highlights',
  },
  {
    id: "hsb082",
    name: 'Keller Daugherty',
    position: "C",
    school: 'Brewster Academy (NH)',
    stage: "high_school",
    rank: 82,
    height: '6\'7"',
    weight: 230,
    metric: null,
    grade: 78,
    capHitM: 0,
    reportTeaser: 'Rim protector / interior presence with upside.',
    reportPremium: 'Timing as a helper and vertical spacer tools. Switch drops and strength program are next.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #82. Multi-year track for college → declare pipeline.',
    traits: ['length', 'rim pressure', 'motor'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Keller%20Daugherty%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Keller%20Daugherty%20Brewster%20Academy%20(NH)%20highlights',
  },
  {
    id: "hsb083",
    name: 'Tony Cornett III',
    position: "PF",
    school: 'AZ Compass Prep (AZ)',
    stage: "high_school",
    rank: 83,
    height: '6\'6"',
    weight: 200,
    metric: null,
    grade: 78,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #83. Multi-year track for college → declare pipeline.',
    traits: ['handle', 'vision', 'pull-up'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Tony%20Cornett%20III%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Tony%20Cornett%20III%20AZ%20Compass%20Prep%20(AZ)%20highlights',
  },
  {
    id: "hsb084",
    name: "K'Nard Callendar",
    position: "SG",
    school: 'Centennial (NV)',
    stage: "high_school",
    rank: 84,
    height: '6\'5"',
    weight: 190,
    metric: null,
    grade: 78,
    capHitM: 0,
    reportTeaser: 'Secondary scorer with shot-making gravity.',
    reportPremium: 'Creates advantages off the bounce and relocates. Contested-catch / off-ball defense still climbing.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #84. Multi-year track for college → declare pipeline.',
    traits: ['switch', 'closeout', 'upside'],
    highlightUrl: 'https://www.youtube.com/results?search_query=K%27Nard%20Callendar%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=K%27Nard%20Callendar%20Centennial%20%28NV%29%20highlights',
  },
  {
    id: "hsb085",
    name: 'Josiah Nance',
    position: "PF",
    school: 'Duncanville (TX)',
    stage: "high_school",
    rank: 85,
    height: '6\'6"',
    weight: 205,
    metric: null,
    grade: 77,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #85. Multi-year track for college → declare pipeline.',
    traits: ['spacing', 'vertical', 'timing'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Josiah%20Nance%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Josiah%20Nance%20Duncanville%20(TX)%20highlights',
  },
  {
    id: "hsb086",
    name: 'Jacoby Briscoe',
    position: "SF",
    school: 'Wheeler (GA)',
    stage: "high_school",
    rank: 86,
    height: '6\'4"',
    weight: 215,
    metric: null,
    grade: 77,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #86. Multi-year track for college → declare pipeline.',
    traits: ['burst', 'compete', 'YACs'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jacoby%20Briscoe%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jacoby%20Briscoe%20Wheeler%20(GA)%20highlights',
  },
  {
    id: "hsb087",
    name: 'Andrew Kretkowski',
    position: "SG",
    school: 'Sierra Canyon (CA)',
    stage: "high_school",
    rank: 87,
    height: '6\'4"',
    weight: 170,
    metric: null,
    grade: 77,
    capHitM: 0,
    reportTeaser: 'Secondary scorer with shot-making gravity.',
    reportPremium: 'Creates advantages off the bounce and relocates. Contested-catch / off-ball defense still climbing.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #87. Multi-year track for college → declare pipeline.',
    traits: ['PnR', 'pass', 'poise'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Andrew%20Kretkowski%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Andrew%20Kretkowski%20Sierra%20Canyon%20(CA)%20highlights',
  },
  {
    id: "hsb088",
    name: 'Tavid Johnson',
    position: "SF",
    school: 'Long Island Lutheran (NY)',
    stage: "high_school",
    rank: 88,
    height: '6\'6"',
    weight: 195,
    metric: null,
    grade: 77,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #88. Multi-year track for college → declare pipeline.',
    traits: ['frame', 'anchor', 'touch'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Tavid%20Johnson%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Tavid%20Johnson%20Long%20Island%20Lutheran%20(NY)%20highlights',
  },
  {
    id: "hsb089",
    name: 'Frashad Tisby',
    position: "SF",
    school: 'DeMatha Catholic (MD)',
    stage: "high_school",
    rank: 89,
    height: '6\'7"',
    weight: 180,
    metric: null,
    grade: 76,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #89. Multi-year track for college → declare pipeline.',
    traits: ['shot creation', 'pace', 'IQ'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Frashad%20Tisby%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Frashad%20Tisby%20DeMatha%20Catholic%20(MD)%20highlights',
  },
  {
    id: "hsb090",
    name: 'Terence Jones',
    position: "PF",
    school: 'Cathedral (IN)',
    stage: "high_school",
    rank: 90,
    height: '6\'7"',
    weight: 190,
    metric: null,
    grade: 76,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #90. Multi-year track for college → declare pipeline.',
    traits: ['length', 'rim pressure', 'motor'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Terence%20Jones%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Terence%20Jones%20Cathedral%20(IN)%20highlights',
  },
  {
    id: "hsb091",
    name: 'Deuce McDuffie',
    position: "SF",
    school: 'Wisconsin Lutheran (WI)',
    stage: "high_school",
    rank: 91,
    height: '6\'7"',
    weight: 175,
    metric: null,
    grade: 76,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #91. Multi-year track for college → declare pipeline.',
    traits: ['handle', 'vision', 'pull-up'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Deuce%20McDuffie%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Deuce%20McDuffie%20Wisconsin%20Lutheran%20(WI)%20highlights',
  },
  {
    id: "hsb092",
    name: 'Marlon Martinez',
    position: "SF",
    school: 'Perry (AZ)',
    stage: "high_school",
    rank: 92,
    height: '6\'5"',
    weight: 180,
    metric: null,
    grade: 76,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #92. Multi-year track for college → declare pipeline.',
    traits: ['switch', 'closeout', 'upside'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Marlon%20Martinez%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Marlon%20Martinez%20Perry%20(AZ)%20highlights',
  },
  {
    id: "hsb093",
    name: 'Silas Graham',
    position: "SG",
    school: 'St. John Bosco (CA)',
    stage: "high_school",
    rank: 93,
    height: '6\'4"',
    weight: 200,
    metric: null,
    grade: 75,
    capHitM: 0,
    reportTeaser: 'Secondary scorer with shot-making gravity.',
    reportPremium: 'Creates advantages off the bounce and relocates. Contested-catch / off-ball defense still climbing.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #93. Multi-year track for college → declare pipeline.',
    traits: ['spacing', 'vertical', 'timing'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Silas%20Graham%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Silas%20Graham%20St.%20John%20Bosco%20(CA)%20highlights',
  },
  {
    id: "hsb094",
    name: 'Caleb Lundy',
    position: "SG",
    school: 'Sunrise Christian (KS)',
    stage: "high_school",
    rank: 94,
    height: '6\'4"',
    weight: 170,
    metric: null,
    grade: 75,
    capHitM: 0,
    reportTeaser: 'Secondary scorer with shot-making gravity.',
    reportPremium: 'Creates advantages off the bounce and relocates. Contested-catch / off-ball defense still climbing.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #94. Multi-year track for college → declare pipeline.',
    traits: ['burst', 'compete', 'YACs'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Caleb%20Lundy%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Caleb%20Lundy%20Sunrise%20Christian%20(KS)%20highlights',
  },
  {
    id: "hsb095",
    name: 'Jayden Conerly',
    position: "PF",
    school: 'Link Academy (MO)',
    stage: "high_school",
    rank: 95,
    height: '6\'8"',
    weight: 210,
    metric: null,
    grade: 75,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #95. Multi-year track for college → declare pipeline.',
    traits: ['PnR', 'pass', 'poise'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jayden%20Conerly%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jayden%20Conerly%20Link%20Academy%20(MO)%20highlights',
  },
  {
    id: "hsb096",
    name: 'Nasir Muhammad-Gray',
    position: "SF",
    school: 'Montverde Academy (FL)',
    stage: "high_school",
    rank: 96,
    height: '6\'6"',
    weight: 180,
    metric: null,
    grade: 75,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #96. Multi-year track for college → declare pipeline.',
    traits: ['frame', 'anchor', 'touch'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Nasir%20Muhammad-Gray%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Nasir%20Muhammad-Gray%20Montverde%20Academy%20(FL)%20highlights',
  },
  {
    id: "hsb097",
    name: 'Tyson Pogi',
    position: "CG",
    school: 'IMG Academy (FL)',
    stage: "high_school",
    rank: 97,
    height: '6\'2"',
    weight: 170,
    metric: null,
    grade: 74,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #97. Multi-year track for college → declare pipeline.',
    traits: ['shot creation', 'pace', 'IQ'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Tyson%20Pogi%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Tyson%20Pogi%20IMG%20Academy%20(FL)%20highlights',
  },
  {
    id: "hsb098",
    name: 'Damon Miles',
    position: "PF",
    school: 'Wasatch Academy (UT)',
    stage: "high_school",
    rank: 98,
    height: '6\'7"',
    weight: 245,
    metric: null,
    grade: 74,
    capHitM: 0,
    reportTeaser: 'Forward who can stretch and finish through contact.',
    reportPremium: 'Finishes above the rim and can step out. Handle under full-court pressure needs reps.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #98. Multi-year track for college → declare pipeline.',
    traits: ['length', 'rim pressure', 'motor'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Damon%20Miles%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Damon%20Miles%20Wasatch%20Academy%20(UT)%20highlights',
  },
  {
    id: "hsb099",
    name: 'Nick Welch Jr.',
    position: "SF",
    school: 'Prolific Prep (FL)',
    stage: "high_school",
    rank: 99,
    height: '6\'6"',
    weight: 200,
    metric: null,
    grade: 74,
    capHitM: 0,
    reportTeaser: 'Wing athlete with two-way tools.',
    reportPremium: 'Length and closeouts jump off tape. Three-point consistency is the projection lever for next level.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #99. Multi-year track for college → declare pipeline.',
    traits: ['handle', 'vision', 'pull-up'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Nick%20Welch%20Jr.%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Nick%20Welch%20Jr.%20Prolific%20Prep%20(FL)%20highlights',
  },
  {
    id: "hsb100",
    name: 'Jimmy McKinney III',
    position: "CG",
    school: 'Oak Hill Academy (VA)',
    stage: "high_school",
    rank: 100,
    height: '6\'1"',
    weight: 165,
    metric: null,
    grade: 74,
    capHitM: 0,
    reportTeaser: 'Combo creator who scores and sets the table.',
    reportPremium: 'Size to see over traps with a real pull-up. Shot selection vs set defenses is the swing skill on film.',
    pipelineNote: 'Class of 2027 — LockGM HS board rank #100. Multi-year track for college → declare pipeline.',
    traits: ['switch', 'closeout', 'upside'],
    highlightUrl: 'https://www.youtube.com/results?search_query=Jimmy%20McKinney%20III%20basketball%20highlights',
    highlightAltUrl: 'https://www.youtube.com/results?search_query=Jimmy%20McKinney%20III%20Oak%20Hill%20Academy%20(VA)%20highlights',
  },
];

export function hsBasketballTop100Count(): number {
  return HS_BASKETBALL_TOP_100.length;
}

