/**
 * Curated YouTube video IDs for 2027 NFL free-agent highlight embeds.
 * Keys must match nfl-2027-free-agents seed names exactly.
 */
export const NFL_2027_FA_CLIP_IDS: Record<string, string> = {
  "Puka Nacua": "d-y98Qsfd4E",
  "George Pickens": "dFWHjDooCPU",
  "Baker Mayfield": "8YDU0Fb5kpo",
  "Kobie Turner": "oOIcL9B9f4o",
  "Tucker Kraft": "CXzlPV_YNxc",
  "Byron Young": "UW8YHBymLec",
  "Sam LaPorta": "4dj7zNK8xpI",
  "Quenton Nelson": "q9P-6bu1qjg",
  "Brian Branch": "omC2lcvSCGI",
  "Tuli Tuipulotu": "HS1GTVBU08E",
  "Steve Avila": "jjMB0zjZnS8",
  "Joey Porter Jr.": "sAbujlgasDk",
  "Kyler Murray": "RhL8oot8Wg4",
  "YaYa Diaby": "-yO8airgrTs",
  "Kevin Dotson": "81fxrPmLX9s",
  "Riley Moss": "fV7k0sa8gnI",
  "Chase Brown": "YIs4bsmYrps",
  "Parker Washington": "fXtlBJLdIxo",
  "Moro Ojomo": "DKQVN31BuCE",
  "Andrew Van Ginkel": "Q7Qr72cdIZI",
  "Mike Onwenu": "Gh93XXJJjk0",
  "Davante Adams": "bl_ZMqjLLN0",
  "Vita Vea": "9RRwSoBYCIk",
  "Leonard Williams": "MWXJbNWHAeg",
  "Marlon Humphrey": "BYwngcnZSTU",
  "Jessie Bates III": "nZO2yRgT1gI",
  "Kayvon Thibodeaux": "PYEM1zvgXRM",
  "D'Andre Swift": "_13RjQUFoh4",
  "Tariq Woolen": "eQprDRz94JY",
  "Ikem Ekwonu": "GvZLIiW9tOg",
  "DeForest Buckner": "fJfYeu-vgfE",
  "Mac Jones": "GzmXUpcU950",
  "T.J. Hockenson": "m_4TXNxBFGU",
  "Justin Fields": "GOPBFb2XHd4",
  "Daron Payne": "qJKpd6wUllU",
  "Anthony Richardson": "tnBvlHXappE",
  "Chris Godwin": "QvAHy5R15-Q",
  "Patrick Queen": "DqEyI-Rm4PI",
  "Evan Engram": "Gh0GuSGgwBY",
  "Deshaun Watson": "zRd56S1wljU",
  "Keeanu Benton": "6MJ__jR8THk",
  "Aaron Rodgers": "ngGhr3W8mIk",
  "D.J. Turner": "abou3eVD9OE",
  "Dorance Armstrong": "Iyh3OXC7WIk",
  "Khalil Mack": "ISWEq15okpo",
  "Tyrique Stevenson": "d6T1yEt97l8",
  "Jermaine Johnson": "ktct71YpUiY",
  "Michael Wilson": "F7WyYCwlaRo",
  "Jacoby Brissett": "KyLKXYvKSq4",
  "Rashee Rice": "3Cl7MMFX7MU",
  "Jaylon Moore": "lUonXnjXssg",
  "Uchenna Nwosu": "o_aHXYsAQXE",
  "Arik Armstead": "F2uIowFgNk4",
  "Josh Downs": "-sbV-EuyAZU",
  "Grover Stewart": "6sdSxi_U-bE",
  "Michael Jackson": "t6B5LPT_uoY",
  "Tre Tucker": "q56rY3ikHRI",
  "DaVon Hamilton": "8bfB-iADt-8",
  "John Michael Schmitz": "7BmKy2Mr1ck",
  "Malcolm Koonce": "uAlsfz0kCWk",
  "K\u2019Lavon Chaisson": "n6XMEX3IBLc",
  "Kayshon Boutte": "dzIwkqH0XGU",
  "David Onyemata": "oBthbf7LXr8",
  "Frankie Luvu": "6E22thkxKgM",
  "A'Shawn Robinson": "yL896wenpNw",
  "Jon Runyan": "dHfB-AZWooI",
  "Kristian Fulton": "3xx4zLSCm_Y",
  "Maliek Collins": "CgonaTElccA",
  "Myles Murphy": "YeD2K1Ln_Fo",
  "Ethan Pocic": "BOLOf4TCUQs",
  "Colby Parkinson": "2DNoVAjuxrk",
  "Daxton Hill": "qZZfWN6w8UA",
  "Jeremy Chinn": "QyV3YQwWjJc",
  "Ezra Cleveland": "sfI8eQwgtWs",
  "Greg Newsome": "-zZ1NpDnXqg",
  "Jauan Jennings": "0s3idHfgVZU",
  "Baron Browning": "Gh42sbXSktE",
  "Blake Cashman": "JzyK5e2y47s",
  "Cameron Jordan": "sfI8eQwgtWs",
  "Harrison Phillips": "i2eRIyvY3b4",
};
