/**
 * LockedGM Classic Matchup — baseball simulation with proprietary LockedGM grades.
 *
 * Dice + LockedGM ratings resolution. Player-facing copy uses LockedGM branding only.
 */

export type {
  AtBatOutcome,
  BatterLine,
  BatterRatings,
  ClassicTeam,
  FieldPos,
  GameResult,
  Hand,
  HighlightKind,
  ManagerCard,
  PitcherLine,
  PitcherRatings,
  PitcherRestBook,
  PitcherRestEntry,
  PitchingPlan,
  PitchRole,
  PlayEvent,
  Player,
  SimOptions,
  TeamBox,
} from "./types";

export { createRng } from "./rng";
export { resolveAtBat, outcomeLabel, radioCallFor } from "./resolve-ab";
export {
  simulateGame,
  simulateSeries,
  simulateBestOf,
  startLiveGame,
  formatIp,
  countOutsRecorded,
  boxHomeRuns,
  type BestOfGame,
  type BestOfSeriesResult,
  type LiveGame,
  type LiveStep,
} from "./game";
export {
  emptyRestBook,
  canEnter,
  recordOutings,
  dropGradeTiers,
  fatiguedPitcher,
  pickBullpenArm,
  pickSeriesStarter,
  bullpenRoleLabel,
  FATIGUE_TIER_DROP,
  FATIGUE_BF_THRESHOLD,
  FIREMAN_THREE_IP_OUTS,
} from "./fatigue";
export {
  findPinchHitRecommendation,
  matchupScore,
  PINCH_HIT_FROM_INNING,
  CLEAR_SPLIT_EDGE,
  type PinchHitRecommendation,
} from "./pinch-hit";
export { platoonMatchupAdj } from "./resolve-ab";
export {
  CLASSIC_TEAMS,
  BREWERS_1985,
  YANKEES_1927,
  REDS_1975,
  BLUE_JAYS_1985,
  ROYALS_1985,
  CARDINALS_1985,
  DODGERS_1985,
  BREWERS_1982,
  ANGELS_1982,
  CARDINALS_1982,
  BRAVES_1982,
  PLAYOFF_1985_TEAM_IDS,
  PLAYOFF_1982_TEAM_IDS,
  classicTeamById,
  classicTeamLabel,
} from "./teams";
export {
  PLAYOFF_1985_TEAMS,
  PLAYOFF_1985_ALCS,
  PLAYOFF_1985_NLCS,
  PLAYOFF_1982_TEAMS,
  PLAYOFF_1982_ALCS,
  PLAYOFF_1982_NLCS,
  simulatePlayoffs1985,
  simulatePlayoffs1982,
  playoffSeriesScoreLine,
  type PlayoffBracketResult,
  type PlayoffRoundResult,
  type PlayoffRoundId,
  type PlayoffRoundDef,
} from "./playoffs";
export {
  ROSTER_SIZE,
  DEFAULT_SALARY_CAP,
  DEFAULT_STARTER_INNINGS_TARGET,
  checkSalaryCap,
  teamPayroll,
  tryAddPlayer,
  applyManagerCard,
  validateLineup,
  validateDefense,
  validatePitching,
  fieldersForPosition,
  rosterPitchers,
  selectStartingPitcher,
  moveBullpenArm,
  setBullpenSlot,
  setStarterInningsTarget,
  defaultPitchingPlan,
  defaultManagerCard,
  teamDefenseRating,
  FIELD_ORDER,
} from "./salary";
export {
  MODERN_FIVE_MAN_YEAR,
  CLASSIC_ROTATION_SIZE,
  MODERN_ROTATION_SIZE,
  PLAYOFF_WINS_NEEDED,
  PLAYOFF_MAX_GAMES,
  rotationSizeForYear,
  rotationSizeForTeam,
  rotationLabel,
  seriesRotation,
} from "./rotation";
export {
  FIELD_POSITIONS,
  OOP_DEFENSE_RATING,
  OOP_ERROR_MULT,
  eligibleFieldPositions,
  isEligibleAt,
  primaryFieldPosition,
  eligibilityBadge,
  effectiveDefenseAt,
  isOutOfPosition,
  listDefenseAssignments,
  countOutOfPosition,
} from "./eligibility";
export {
  createClassicLeague,
  claimTeam,
  simulateLeagueRound,
  simulateLeaguePlayoffs,
  humanSlot,
  updateHumanCard,
  makeCapBusterFreeAgent,
  attemptSignFreeAgent,
  leagueStandings,
  aiSetLineup,
  type LeagueState,
  type LeagueSlot,
  type LeaguePlayoffs,
} from "./league";
